<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Ancient_Greek_Musical_Notation: string
{
    #[Info(id: 0x1D200, name: 'GREEK VOCAL NOTATION SYMBOL-1', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_1 = "\u{1D200}";

    #[Info(id: 0x1D201, name: 'GREEK VOCAL NOTATION SYMBOL-2', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_2 = "\u{1D201}";

    #[Info(id: 0x1D202, name: 'GREEK VOCAL NOTATION SYMBOL-3', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_3 = "\u{1D202}";

    #[Info(id: 0x1D203, name: 'GREEK VOCAL NOTATION SYMBOL-4', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_4 = "\u{1D203}";

    #[Info(id: 0x1D204, name: 'GREEK VOCAL NOTATION SYMBOL-5', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_5 = "\u{1D204}";

    #[Info(id: 0x1D205, name: 'GREEK VOCAL NOTATION SYMBOL-6', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_6 = "\u{1D205}";

    #[Info(id: 0x1D206, name: 'GREEK VOCAL NOTATION SYMBOL-7', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_7 = "\u{1D206}";

    #[Info(id: 0x1D207, name: 'GREEK VOCAL NOTATION SYMBOL-8', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_8 = "\u{1D207}";

    #[Info(id: 0x1D208, name: 'GREEK VOCAL NOTATION SYMBOL-9', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_9 = "\u{1D208}";

    #[Info(id: 0x1D209, name: 'GREEK VOCAL NOTATION SYMBOL-10', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_10 = "\u{1D209}";

    #[Info(id: 0x1D20A, name: 'GREEK VOCAL NOTATION SYMBOL-11', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_11 = "\u{1D20A}";

    #[Info(id: 0x1D20B, name: 'GREEK VOCAL NOTATION SYMBOL-12', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_12 = "\u{1D20B}";

    #[Info(id: 0x1D20C, name: 'GREEK VOCAL NOTATION SYMBOL-13', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_13 = "\u{1D20C}";

    #[Info(id: 0x1D20D, name: 'GREEK VOCAL NOTATION SYMBOL-14', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_14 = "\u{1D20D}";

    #[Info(id: 0x1D20E, name: 'GREEK VOCAL NOTATION SYMBOL-15', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_15 = "\u{1D20E}";

    #[Info(id: 0x1D20F, name: 'GREEK VOCAL NOTATION SYMBOL-16', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_16 = "\u{1D20F}";

    #[Info(id: 0x1D210, name: 'GREEK VOCAL NOTATION SYMBOL-17', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_17 = "\u{1D210}";

    #[Info(id: 0x1D211, name: 'GREEK VOCAL NOTATION SYMBOL-18', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_18 = "\u{1D211}";

    #[Info(id: 0x1D212, name: 'GREEK VOCAL NOTATION SYMBOL-19', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_19 = "\u{1D212}";

    #[Info(id: 0x1D213, name: 'GREEK VOCAL NOTATION SYMBOL-20', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_20 = "\u{1D213}";

    #[Info(id: 0x1D214, name: 'GREEK VOCAL NOTATION SYMBOL-21', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_21 = "\u{1D214}";

    #[Info(id: 0x1D215, name: 'GREEK VOCAL NOTATION SYMBOL-22', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_22 = "\u{1D215}";

    #[Info(id: 0x1D216, name: 'GREEK VOCAL NOTATION SYMBOL-23', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_23 = "\u{1D216}";

    #[Info(id: 0x1D217, name: 'GREEK VOCAL NOTATION SYMBOL-24', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_24 = "\u{1D217}";

    #[Info(id: 0x1D218, name: 'GREEK VOCAL NOTATION SYMBOL-50', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_50 = "\u{1D218}";

    #[Info(id: 0x1D219, name: 'GREEK VOCAL NOTATION SYMBOL-51', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_51 = "\u{1D219}";

    #[Info(id: 0x1D21A, name: 'GREEK VOCAL NOTATION SYMBOL-52', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_52 = "\u{1D21A}";

    #[Info(id: 0x1D21B, name: 'GREEK VOCAL NOTATION SYMBOL-53', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_53 = "\u{1D21B}";

    #[Info(id: 0x1D21C, name: 'GREEK VOCAL NOTATION SYMBOL-54', category: Cat::Other_Symbol)]
    case GREEK_VOCAL_NOTATION_SYMBOL_54 = "\u{1D21C}";

    #[Info(id: 0x1D21D, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-1', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_1 = "\u{1D21D}";

    #[Info(id: 0x1D21E, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-2', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_2 = "\u{1D21E}";

    #[Info(id: 0x1D21F, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-4', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_4 = "\u{1D21F}";

    #[Info(id: 0x1D220, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-5', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_5 = "\u{1D220}";

    #[Info(id: 0x1D221, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-7', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_7 = "\u{1D221}";

    #[Info(id: 0x1D222, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-8', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_8 = "\u{1D222}";

    #[Info(id: 0x1D223, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-11', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_11 = "\u{1D223}";

    #[Info(id: 0x1D224, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-12', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_12 = "\u{1D224}";

    #[Info(id: 0x1D225, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-13', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_13 = "\u{1D225}";

    #[Info(id: 0x1D226, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-14', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_14 = "\u{1D226}";

    #[Info(id: 0x1D227, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-17', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_17 = "\u{1D227}";

    #[Info(id: 0x1D228, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-18', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_18 = "\u{1D228}";

    #[Info(id: 0x1D229, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-19', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_19 = "\u{1D229}";

    #[Info(id: 0x1D22A, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-23', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_23 = "\u{1D22A}";

    #[Info(id: 0x1D22B, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-24', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_24 = "\u{1D22B}";

    #[Info(id: 0x1D22C, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-25', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_25 = "\u{1D22C}";

    #[Info(id: 0x1D22D, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-26', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_26 = "\u{1D22D}";

    #[Info(id: 0x1D22E, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-27', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_27 = "\u{1D22E}";

    #[Info(id: 0x1D22F, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-29', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_29 = "\u{1D22F}";

    #[Info(id: 0x1D230, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-30', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_30 = "\u{1D230}";

    #[Info(id: 0x1D231, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-32', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_32 = "\u{1D231}";

    #[Info(id: 0x1D232, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-36', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_36 = "\u{1D232}";

    #[Info(id: 0x1D233, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-37', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_37 = "\u{1D233}";

    #[Info(id: 0x1D234, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-38', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_38 = "\u{1D234}";

    #[Info(id: 0x1D235, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-39', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_39 = "\u{1D235}";

    #[Info(id: 0x1D236, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-40', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_40 = "\u{1D236}";

    #[Info(id: 0x1D237, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-42', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_42 = "\u{1D237}";

    #[Info(id: 0x1D238, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-43', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_43 = "\u{1D238}";

    #[Info(id: 0x1D239, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-45', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_45 = "\u{1D239}";

    #[Info(id: 0x1D23A, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-47', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_47 = "\u{1D23A}";

    #[Info(id: 0x1D23B, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-48', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_48 = "\u{1D23B}";

    #[Info(id: 0x1D23C, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-49', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_49 = "\u{1D23C}";

    #[Info(id: 0x1D23D, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-50', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_50 = "\u{1D23D}";

    #[Info(id: 0x1D23E, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-51', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_51 = "\u{1D23E}";

    #[Info(id: 0x1D23F, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-52', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_52 = "\u{1D23F}";

    #[Info(id: 0x1D240, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-53', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_53 = "\u{1D240}";

    #[Info(id: 0x1D241, name: 'GREEK INSTRUMENTAL NOTATION SYMBOL-54', category: Cat::Other_Symbol)]
    case GREEK_INSTRUMENTAL_NOTATION_SYMBOL_54 = "\u{1D241}";

    #[Info(id: 0x1D242, name: 'COMBINING GREEK MUSICAL TRISEME', category: Cat::Nonspacing_Mark)]
    case COMBINING_GREEK_MUSICAL_TRISEME = "\u{1D242}";

    #[Info(id: 0x1D243, name: 'COMBINING GREEK MUSICAL TETRASEME', category: Cat::Nonspacing_Mark)]
    case COMBINING_GREEK_MUSICAL_TETRASEME = "\u{1D243}";

    #[Info(id: 0x1D244, name: 'COMBINING GREEK MUSICAL PENTASEME', category: Cat::Nonspacing_Mark)]
    case COMBINING_GREEK_MUSICAL_PENTASEME = "\u{1D244}";

    #[Info(id: 0x1D245, name: 'GREEK MUSICAL LEIMMA', category: Cat::Other_Symbol)]
    case GREEK_MUSICAL_LEIMMA = "\u{1D245}";
}
