<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Cherokee_Supplement: string
{
    #[Info(id: 43888, name: 'CHEROKEE SMALL LETTER A', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_A = "\u{AB70}";

    #[Info(id: 43889, name: 'CHEROKEE SMALL LETTER E', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_E = "\u{AB71}";

    #[Info(id: 43890, name: 'CHEROKEE SMALL LETTER I', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_I = "\u{AB72}";

    #[Info(id: 43891, name: 'CHEROKEE SMALL LETTER O', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_O = "\u{AB73}";

    #[Info(id: 43892, name: 'CHEROKEE SMALL LETTER U', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_U = "\u{AB74}";

    #[Info(id: 43893, name: 'CHEROKEE SMALL LETTER V', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_V = "\u{AB75}";

    #[Info(id: 43894, name: 'CHEROKEE SMALL LETTER GA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_GA = "\u{AB76}";

    #[Info(id: 43895, name: 'CHEROKEE SMALL LETTER KA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_KA = "\u{AB77}";

    #[Info(id: 43896, name: 'CHEROKEE SMALL LETTER GE', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_GE = "\u{AB78}";

    #[Info(id: 43897, name: 'CHEROKEE SMALL LETTER GI', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_GI = "\u{AB79}";

    #[Info(id: 43898, name: 'CHEROKEE SMALL LETTER GO', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_GO = "\u{AB7A}";

    #[Info(id: 43899, name: 'CHEROKEE SMALL LETTER GU', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_GU = "\u{AB7B}";

    #[Info(id: 43900, name: 'CHEROKEE SMALL LETTER GV', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_GV = "\u{AB7C}";

    #[Info(id: 43901, name: 'CHEROKEE SMALL LETTER HA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_HA = "\u{AB7D}";

    #[Info(id: 43902, name: 'CHEROKEE SMALL LETTER HE', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_HE = "\u{AB7E}";

    #[Info(id: 43903, name: 'CHEROKEE SMALL LETTER HI', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_HI = "\u{AB7F}";

    #[Info(id: 43904, name: 'CHEROKEE SMALL LETTER HO', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_HO = "\u{AB80}";

    #[Info(id: 43905, name: 'CHEROKEE SMALL LETTER HU', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_HU = "\u{AB81}";

    #[Info(id: 43906, name: 'CHEROKEE SMALL LETTER HV', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_HV = "\u{AB82}";

    #[Info(id: 43907, name: 'CHEROKEE SMALL LETTER LA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_LA = "\u{AB83}";

    #[Info(id: 43908, name: 'CHEROKEE SMALL LETTER LE', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_LE = "\u{AB84}";

    #[Info(id: 43909, name: 'CHEROKEE SMALL LETTER LI', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_LI = "\u{AB85}";

    #[Info(id: 43910, name: 'CHEROKEE SMALL LETTER LO', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_LO = "\u{AB86}";

    #[Info(id: 43911, name: 'CHEROKEE SMALL LETTER LU', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_LU = "\u{AB87}";

    #[Info(id: 43912, name: 'CHEROKEE SMALL LETTER LV', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_LV = "\u{AB88}";

    #[Info(id: 43913, name: 'CHEROKEE SMALL LETTER MA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_MA = "\u{AB89}";

    #[Info(id: 43914, name: 'CHEROKEE SMALL LETTER ME', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_ME = "\u{AB8A}";

    #[Info(id: 43915, name: 'CHEROKEE SMALL LETTER MI', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_MI = "\u{AB8B}";

    #[Info(id: 43916, name: 'CHEROKEE SMALL LETTER MO', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_MO = "\u{AB8C}";

    #[Info(id: 43917, name: 'CHEROKEE SMALL LETTER MU', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_MU = "\u{AB8D}";

    #[Info(id: 43918, name: 'CHEROKEE SMALL LETTER NA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_NA = "\u{AB8E}";

    #[Info(id: 43919, name: 'CHEROKEE SMALL LETTER HNA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_HNA = "\u{AB8F}";

    #[Info(id: 43920, name: 'CHEROKEE SMALL LETTER NAH', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_NAH = "\u{AB90}";

    #[Info(id: 43921, name: 'CHEROKEE SMALL LETTER NE', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_NE = "\u{AB91}";

    #[Info(id: 43922, name: 'CHEROKEE SMALL LETTER NI', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_NI = "\u{AB92}";

    #[Info(id: 43923, name: 'CHEROKEE SMALL LETTER NO', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_NO = "\u{AB93}";

    #[Info(id: 43924, name: 'CHEROKEE SMALL LETTER NU', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_NU = "\u{AB94}";

    #[Info(id: 43925, name: 'CHEROKEE SMALL LETTER NV', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_NV = "\u{AB95}";

    #[Info(id: 43926, name: 'CHEROKEE SMALL LETTER QUA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_QUA = "\u{AB96}";

    #[Info(id: 43927, name: 'CHEROKEE SMALL LETTER QUE', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_QUE = "\u{AB97}";

    #[Info(id: 43928, name: 'CHEROKEE SMALL LETTER QUI', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_QUI = "\u{AB98}";

    #[Info(id: 43929, name: 'CHEROKEE SMALL LETTER QUO', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_QUO = "\u{AB99}";

    #[Info(id: 43930, name: 'CHEROKEE SMALL LETTER QUU', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_QUU = "\u{AB9A}";

    #[Info(id: 43931, name: 'CHEROKEE SMALL LETTER QUV', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_QUV = "\u{AB9B}";

    #[Info(id: 43932, name: 'CHEROKEE SMALL LETTER SA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_SA = "\u{AB9C}";

    #[Info(id: 43933, name: 'CHEROKEE SMALL LETTER S', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_S = "\u{AB9D}";

    #[Info(id: 43934, name: 'CHEROKEE SMALL LETTER SE', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_SE = "\u{AB9E}";

    #[Info(id: 43935, name: 'CHEROKEE SMALL LETTER SI', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_SI = "\u{AB9F}";

    #[Info(id: 43936, name: 'CHEROKEE SMALL LETTER SO', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_SO = "\u{ABA0}";

    #[Info(id: 43937, name: 'CHEROKEE SMALL LETTER SU', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_SU = "\u{ABA1}";

    #[Info(id: 43938, name: 'CHEROKEE SMALL LETTER SV', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_SV = "\u{ABA2}";

    #[Info(id: 43939, name: 'CHEROKEE SMALL LETTER DA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_DA = "\u{ABA3}";

    #[Info(id: 43940, name: 'CHEROKEE SMALL LETTER TA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TA = "\u{ABA4}";

    #[Info(id: 43941, name: 'CHEROKEE SMALL LETTER DE', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_DE = "\u{ABA5}";

    #[Info(id: 43942, name: 'CHEROKEE SMALL LETTER TE', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TE = "\u{ABA6}";

    #[Info(id: 43943, name: 'CHEROKEE SMALL LETTER DI', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_DI = "\u{ABA7}";

    #[Info(id: 43944, name: 'CHEROKEE SMALL LETTER TI', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TI = "\u{ABA8}";

    #[Info(id: 43945, name: 'CHEROKEE SMALL LETTER DO', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_DO = "\u{ABA9}";

    #[Info(id: 43946, name: 'CHEROKEE SMALL LETTER DU', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_DU = "\u{ABAA}";

    #[Info(id: 43947, name: 'CHEROKEE SMALL LETTER DV', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_DV = "\u{ABAB}";

    #[Info(id: 43948, name: 'CHEROKEE SMALL LETTER DLA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_DLA = "\u{ABAC}";

    #[Info(id: 43949, name: 'CHEROKEE SMALL LETTER TLA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TLA = "\u{ABAD}";

    #[Info(id: 43950, name: 'CHEROKEE SMALL LETTER TLE', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TLE = "\u{ABAE}";

    #[Info(id: 43951, name: 'CHEROKEE SMALL LETTER TLI', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TLI = "\u{ABAF}";

    #[Info(id: 43952, name: 'CHEROKEE SMALL LETTER TLO', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TLO = "\u{ABB0}";

    #[Info(id: 43953, name: 'CHEROKEE SMALL LETTER TLU', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TLU = "\u{ABB1}";

    #[Info(id: 43954, name: 'CHEROKEE SMALL LETTER TLV', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TLV = "\u{ABB2}";

    #[Info(id: 43955, name: 'CHEROKEE SMALL LETTER TSA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TSA = "\u{ABB3}";

    #[Info(id: 43956, name: 'CHEROKEE SMALL LETTER TSE', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TSE = "\u{ABB4}";

    #[Info(id: 43957, name: 'CHEROKEE SMALL LETTER TSI', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TSI = "\u{ABB5}";

    #[Info(id: 43958, name: 'CHEROKEE SMALL LETTER TSO', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TSO = "\u{ABB6}";

    #[Info(id: 43959, name: 'CHEROKEE SMALL LETTER TSU', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TSU = "\u{ABB7}";

    #[Info(id: 43960, name: 'CHEROKEE SMALL LETTER TSV', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_TSV = "\u{ABB8}";

    #[Info(id: 43961, name: 'CHEROKEE SMALL LETTER WA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_WA = "\u{ABB9}";

    #[Info(id: 43962, name: 'CHEROKEE SMALL LETTER WE', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_WE = "\u{ABBA}";

    #[Info(id: 43963, name: 'CHEROKEE SMALL LETTER WI', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_WI = "\u{ABBB}";

    #[Info(id: 43964, name: 'CHEROKEE SMALL LETTER WO', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_WO = "\u{ABBC}";

    #[Info(id: 43965, name: 'CHEROKEE SMALL LETTER WU', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_WU = "\u{ABBD}";

    #[Info(id: 43966, name: 'CHEROKEE SMALL LETTER WV', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_WV = "\u{ABBE}";

    #[Info(id: 43967, name: 'CHEROKEE SMALL LETTER YA', category: Cat::Lowercase_Letter)]
    case CHEROKEE_SMALL_LETTER_YA = "\u{ABBF}";
}
