<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum CJK_Compatibility: string
{
    #[Info(id: 0x3300, name: 'SQUARE APAATO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED APAATO')]
    case SQUARE_APAATO = "\u{3300}";

    #[Info(id: 0x3301, name: 'SQUARE ARUHUA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED ARUHUA')]
    case SQUARE_ARUHUA = "\u{3301}";

    #[Info(id: 0x3302, name: 'SQUARE ANPEA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED ANPEA')]
    case SQUARE_ANPEA = "\u{3302}";

    #[Info(id: 0x3303, name: 'SQUARE AARU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED AARU')]
    case SQUARE_AARU = "\u{3303}";

    #[Info(id: 0x3304, name: 'SQUARE ININGU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED ININGU')]
    case SQUARE_ININGU = "\u{3304}";

    #[Info(id: 0x3305, name: 'SQUARE INTI', category: Cat::Other_Symbol, unicode1Name: 'SQUARED INTI')]
    case SQUARE_INTI = "\u{3305}";

    #[Info(id: 0x3306, name: 'SQUARE UON', category: Cat::Other_Symbol, unicode1Name: 'SQUARED UON')]
    case SQUARE_UON = "\u{3306}";

    #[Info(id: 0x3307, name: 'SQUARE ESUKUUDO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED ESUKUUDO')]
    case SQUARE_ESUKUUDO = "\u{3307}";

    #[Info(id: 0x3308, name: 'SQUARE EEKAA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED EEKAA')]
    case SQUARE_EEKAA = "\u{3308}";

    #[Info(id: 0x3309, name: 'SQUARE ONSU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED ONSU')]
    case SQUARE_ONSU = "\u{3309}";

    #[Info(id: 0x330A, name: 'SQUARE OOMU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED OOMU')]
    case SQUARE_OOMU = "\u{330A}";

    #[Info(id: 0x330B, name: 'SQUARE KAIRI', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KAIRI')]
    case SQUARE_KAIRI = "\u{330B}";

    #[Info(id: 0x330C, name: 'SQUARE KARATTO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KARATTO')]
    case SQUARE_KARATTO = "\u{330C}";

    #[Info(id: 0x330D, name: 'SQUARE KARORII', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KARORII')]
    case SQUARE_KARORII = "\u{330D}";

    #[Info(id: 0x330E, name: 'SQUARE GARON', category: Cat::Other_Symbol, unicode1Name: 'SQUARED GARON')]
    case SQUARE_GARON = "\u{330E}";

    #[Info(id: 0x330F, name: 'SQUARE GANMA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED GANMA')]
    case SQUARE_GANMA = "\u{330F}";

    #[Info(id: 0x3310, name: 'SQUARE GIGA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED GIGA')]
    case SQUARE_GIGA = "\u{3310}";

    #[Info(id: 0x3311, name: 'SQUARE GINII', category: Cat::Other_Symbol, unicode1Name: 'SQUARED GINII')]
    case SQUARE_GINII = "\u{3311}";

    #[Info(id: 0x3312, name: 'SQUARE KYURII', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KYURII')]
    case SQUARE_KYURII = "\u{3312}";

    #[Info(id: 0x3313, name: 'SQUARE GIRUDAA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED GIRUDAA')]
    case SQUARE_GIRUDAA = "\u{3313}";

    #[Info(id: 0x3314, name: 'SQUARE KIRO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KIRO')]
    case SQUARE_KIRO = "\u{3314}";

    #[Info(id: 0x3315, name: 'SQUARE KIROGURAMU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KIROGURAMU')]
    case SQUARE_KIROGURAMU = "\u{3315}";

    #[Info(id: 0x3316, name: 'SQUARE KIROMEETORU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KIROMEETORU')]
    case SQUARE_KIROMEETORU = "\u{3316}";

    #[Info(id: 0x3317, name: 'SQUARE KIROWATTO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KIROWATTO')]
    case SQUARE_KIROWATTO = "\u{3317}";

    #[Info(id: 0x3318, name: 'SQUARE GURAMU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED GURAMU')]
    case SQUARE_GURAMU = "\u{3318}";

    #[Info(id: 0x3319, name: 'SQUARE GURAMUTON', category: Cat::Other_Symbol, unicode1Name: 'SQUARED GURAMUTON')]
    case SQUARE_GURAMUTON = "\u{3319}";

    #[Info(id: 0x331A, name: 'SQUARE KURUZEIRO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KURUZEIRO')]
    case SQUARE_KURUZEIRO = "\u{331A}";

    #[Info(id: 0x331B, name: 'SQUARE KUROONE', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KUROONE')]
    case SQUARE_KUROONE = "\u{331B}";

    #[Info(id: 0x331C, name: 'SQUARE KEESU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KEESU')]
    case SQUARE_KEESU = "\u{331C}";

    #[Info(id: 0x331D, name: 'SQUARE KORUNA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KORUNA')]
    case SQUARE_KORUNA = "\u{331D}";

    #[Info(id: 0x331E, name: 'SQUARE KOOPO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KOOPO')]
    case SQUARE_KOOPO = "\u{331E}";

    #[Info(id: 0x331F, name: 'SQUARE SAIKURU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED SAIKURU')]
    case SQUARE_SAIKURU = "\u{331F}";

    #[Info(id: 0x3320, name: 'SQUARE SANTIIMU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED SANTIIMU')]
    case SQUARE_SANTIIMU = "\u{3320}";

    #[Info(id: 0x3321, name: 'SQUARE SIRINGU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED SIRINGU')]
    case SQUARE_SIRINGU = "\u{3321}";

    #[Info(id: 0x3322, name: 'SQUARE SENTI', category: Cat::Other_Symbol, unicode1Name: 'SQUARED SENTI')]
    case SQUARE_SENTI = "\u{3322}";

    #[Info(id: 0x3323, name: 'SQUARE SENTO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED SENTO')]
    case SQUARE_SENTO = "\u{3323}";

    #[Info(id: 0x3324, name: 'SQUARE DAASU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED DAASU')]
    case SQUARE_DAASU = "\u{3324}";

    #[Info(id: 0x3325, name: 'SQUARE DESI', category: Cat::Other_Symbol, unicode1Name: 'SQUARED DESI')]
    case SQUARE_DESI = "\u{3325}";

    #[Info(id: 0x3326, name: 'SQUARE DORU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED DORU')]
    case SQUARE_DORU = "\u{3326}";

    #[Info(id: 0x3327, name: 'SQUARE TON', category: Cat::Other_Symbol, unicode1Name: 'SQUARED TON')]
    case SQUARE_TON = "\u{3327}";

    #[Info(id: 0x3328, name: 'SQUARE NANO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED NANO')]
    case SQUARE_NANO = "\u{3328}";

    #[Info(id: 0x3329, name: 'SQUARE NOTTO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED NOTTO')]
    case SQUARE_NOTTO = "\u{3329}";

    #[Info(id: 0x332A, name: 'SQUARE HAITU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED HAITU')]
    case SQUARE_HAITU = "\u{332A}";

    #[Info(id: 0x332B, name: 'SQUARE PAASENTO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PAASENTO')]
    case SQUARE_PAASENTO = "\u{332B}";

    #[Info(id: 0x332C, name: 'SQUARE PAATU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PAATU')]
    case SQUARE_PAATU = "\u{332C}";

    #[Info(id: 0x332D, name: 'SQUARE BAARERU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED BAARERU')]
    case SQUARE_BAARERU = "\u{332D}";

    #[Info(id: 0x332E, name: 'SQUARE PIASUTORU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PIASUTORU')]
    case SQUARE_PIASUTORU = "\u{332E}";

    #[Info(id: 0x332F, name: 'SQUARE PIKURU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PIKURU')]
    case SQUARE_PIKURU = "\u{332F}";

    #[Info(id: 0x3330, name: 'SQUARE PIKO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PIKO')]
    case SQUARE_PIKO = "\u{3330}";

    #[Info(id: 0x3331, name: 'SQUARE BIRU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED BIRU')]
    case SQUARE_BIRU = "\u{3331}";

    #[Info(id: 0x3332, name: 'SQUARE HUARADDO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED HUARADDO')]
    case SQUARE_HUARADDO = "\u{3332}";

    #[Info(id: 0x3333, name: 'SQUARE HUIITO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED HUIITO')]
    case SQUARE_HUIITO = "\u{3333}";

    #[Info(id: 0x3334, name: 'SQUARE BUSSYERU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED BUSSYERU')]
    case SQUARE_BUSSYERU = "\u{3334}";

    #[Info(id: 0x3335, name: 'SQUARE HURAN', category: Cat::Other_Symbol, unicode1Name: 'SQUARED HURAN')]
    case SQUARE_HURAN = "\u{3335}";

    #[Info(id: 0x3336, name: 'SQUARE HEKUTAARU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED HEKUTAARU')]
    case SQUARE_HEKUTAARU = "\u{3336}";

    #[Info(id: 0x3337, name: 'SQUARE PESO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PESO')]
    case SQUARE_PESO = "\u{3337}";

    #[Info(id: 0x3338, name: 'SQUARE PENIHI', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PENIHI')]
    case SQUARE_PENIHI = "\u{3338}";

    #[Info(id: 0x3339, name: 'SQUARE HERUTU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED HERUTU')]
    case SQUARE_HERUTU = "\u{3339}";

    #[Info(id: 0x333A, name: 'SQUARE PENSU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PENSU')]
    case SQUARE_PENSU = "\u{333A}";

    #[Info(id: 0x333B, name: 'SQUARE PEEZI', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PEEZI')]
    case SQUARE_PEEZI = "\u{333B}";

    #[Info(id: 0x333C, name: 'SQUARE BEETA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED BEETA')]
    case SQUARE_BEETA = "\u{333C}";

    #[Info(id: 0x333D, name: 'SQUARE POINTO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED POINTO')]
    case SQUARE_POINTO = "\u{333D}";

    #[Info(id: 0x333E, name: 'SQUARE BORUTO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED BORUTO')]
    case SQUARE_BORUTO = "\u{333E}";

    #[Info(id: 0x333F, name: 'SQUARE HON', category: Cat::Other_Symbol, unicode1Name: 'SQUARED HON')]
    case SQUARE_HON = "\u{333F}";

    #[Info(id: 0x3340, name: 'SQUARE PONDO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PONDO')]
    case SQUARE_PONDO = "\u{3340}";

    #[Info(id: 0x3341, name: 'SQUARE HOORU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED HOORU')]
    case SQUARE_HOORU = "\u{3341}";

    #[Info(id: 0x3342, name: 'SQUARE HOON', category: Cat::Other_Symbol, unicode1Name: 'SQUARED HOON')]
    case SQUARE_HOON = "\u{3342}";

    #[Info(id: 0x3343, name: 'SQUARE MAIKURO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MAIKURO')]
    case SQUARE_MAIKURO = "\u{3343}";

    #[Info(id: 0x3344, name: 'SQUARE MAIRU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MAIRU')]
    case SQUARE_MAIRU = "\u{3344}";

    #[Info(id: 0x3345, name: 'SQUARE MAHHA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MAHHA')]
    case SQUARE_MAHHA = "\u{3345}";

    #[Info(id: 0x3346, name: 'SQUARE MARUKU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MARUKU')]
    case SQUARE_MARUKU = "\u{3346}";

    #[Info(id: 0x3347, name: 'SQUARE MANSYON', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MANSYON')]
    case SQUARE_MANSYON = "\u{3347}";

    #[Info(id: 0x3348, name: 'SQUARE MIKURON', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MIKURON')]
    case SQUARE_MIKURON = "\u{3348}";

    #[Info(id: 0x3349, name: 'SQUARE MIRI', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MIRI')]
    case SQUARE_MIRI = "\u{3349}";

    #[Info(id: 0x334A, name: 'SQUARE MIRIBAARU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MIRIBAARU')]
    case SQUARE_MIRIBAARU = "\u{334A}";

    #[Info(id: 0x334B, name: 'SQUARE MEGA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MEGA')]
    case SQUARE_MEGA = "\u{334B}";

    #[Info(id: 0x334C, name: 'SQUARE MEGATON', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MEGATON')]
    case SQUARE_MEGATON = "\u{334C}";

    #[Info(id: 0x334D, name: 'SQUARE MEETORU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MEETORU')]
    case SQUARE_MEETORU = "\u{334D}";

    #[Info(id: 0x334E, name: 'SQUARE YAADO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED YAADO')]
    case SQUARE_YAADO = "\u{334E}";

    #[Info(id: 0x334F, name: 'SQUARE YAARU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED YAARU')]
    case SQUARE_YAARU = "\u{334F}";

    #[Info(id: 0x3350, name: 'SQUARE YUAN', category: Cat::Other_Symbol, unicode1Name: 'SQUARED YUAN')]
    case SQUARE_YUAN = "\u{3350}";

    #[Info(id: 0x3351, name: 'SQUARE RITTORU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED RITTORU')]
    case SQUARE_RITTORU = "\u{3351}";

    #[Info(id: 0x3352, name: 'SQUARE RIRA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED RIRA')]
    case SQUARE_RIRA = "\u{3352}";

    #[Info(id: 0x3353, name: 'SQUARE RUPII', category: Cat::Other_Symbol, unicode1Name: 'SQUARED RUPII')]
    case SQUARE_RUPII = "\u{3353}";

    #[Info(id: 0x3354, name: 'SQUARE RUUBURU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED RUUBURU')]
    case SQUARE_RUUBURU = "\u{3354}";

    #[Info(id: 0x3355, name: 'SQUARE REMU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED REMU')]
    case SQUARE_REMU = "\u{3355}";

    #[Info(id: 0x3356, name: 'SQUARE RENTOGEN', category: Cat::Other_Symbol, unicode1Name: 'SQUARED RENTOGEN')]
    case SQUARE_RENTOGEN = "\u{3356}";

    #[Info(id: 0x3357, name: 'SQUARE WATTO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED WATTO')]
    case SQUARE_WATTO = "\u{3357}";

    #[Info(id: 0x3358, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR ZERO', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_ZERO = "\u{3358}";

    #[Info(id: 0x3359, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR ONE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_ONE = "\u{3359}";

    #[Info(id: 0x335A, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWO', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_TWO = "\u{335A}";

    #[Info(id: 0x335B, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR THREE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_THREE = "\u{335B}";

    #[Info(id: 0x335C, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR FOUR', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_FOUR = "\u{335C}";

    #[Info(id: 0x335D, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR FIVE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_FIVE = "\u{335D}";

    #[Info(id: 0x335E, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR SIX', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_SIX = "\u{335E}";

    #[Info(id: 0x335F, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR SEVEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_SEVEN = "\u{335F}";

    #[Info(id: 0x3360, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR EIGHT', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_EIGHT = "\u{3360}";

    #[Info(id: 0x3361, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR NINE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_NINE = "\u{3361}";

    #[Info(id: 0x3362, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_TEN = "\u{3362}";

    #[Info(id: 0x3363, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR ELEVEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_ELEVEN = "\u{3363}";

    #[Info(id: 0x3364, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWELVE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_TWELVE = "\u{3364}";

    #[Info(id: 0x3365, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR THIRTEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_THIRTEEN = "\u{3365}";

    #[Info(id: 0x3366, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR FOURTEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_FOURTEEN = "\u{3366}";

    #[Info(id: 0x3367, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR FIFTEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_FIFTEEN = "\u{3367}";

    #[Info(id: 0x3368, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR SIXTEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_SIXTEEN = "\u{3368}";

    #[Info(id: 0x3369, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR SEVENTEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_SEVENTEEN = "\u{3369}";

    #[Info(id: 0x336A, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR EIGHTEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_EIGHTEEN = "\u{336A}";

    #[Info(id: 0x336B, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR NINETEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_NINETEEN = "\u{336B}";

    #[Info(id: 0x336C, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWENTY', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_TWENTY = "\u{336C}";

    #[Info(id: 0x336D, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWENTY-ONE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_TWENTY_ONE = "\u{336D}";

    #[Info(id: 0x336E, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWENTY-TWO', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_TWENTY_TWO = "\u{336E}";

    #[Info(id: 0x336F, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWENTY-THREE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_TWENTY_THREE = "\u{336F}";

    #[Info(id: 0x3370, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWENTY-FOUR', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_HOUR_TWENTY_FOUR = "\u{3370}";

    #[Info(id: 0x3371, name: 'SQUARE HPA', category: Cat::Other_Symbol)]
    case SQUARE_HPA = "\u{3371}";

    #[Info(id: 0x3372, name: 'SQUARE DA', category: Cat::Other_Symbol)]
    case SQUARE_DA = "\u{3372}";

    #[Info(id: 0x3373, name: 'SQUARE AU', category: Cat::Other_Symbol)]
    case SQUARE_AU = "\u{3373}";

    #[Info(id: 0x3374, name: 'SQUARE BAR', category: Cat::Other_Symbol)]
    case SQUARE_BAR = "\u{3374}";

    #[Info(id: 0x3375, name: 'SQUARE OV', category: Cat::Other_Symbol)]
    case SQUARE_OV = "\u{3375}";

    #[Info(id: 0x3376, name: 'SQUARE PC', category: Cat::Other_Symbol)]
    case SQUARE_PC = "\u{3376}";

    #[Info(id: 0x3377, name: 'SQUARE DM', category: Cat::Other_Symbol)]
    case SQUARE_DM = "\u{3377}";

    #[Info(id: 0x3378, name: 'SQUARE DM SQUARED', category: Cat::Other_Symbol)]
    case SQUARE_DM_SQUARED = "\u{3378}";

    #[Info(id: 0x3379, name: 'SQUARE DM CUBED', category: Cat::Other_Symbol)]
    case SQUARE_DM_CUBED = "\u{3379}";

    #[Info(id: 0x337A, name: 'SQUARE IU', category: Cat::Other_Symbol)]
    case SQUARE_IU = "\u{337A}";

    #[Info(id: 0x337B, name: 'SQUARE ERA NAME HEISEI', category: Cat::Other_Symbol, unicode1Name: 'SQUARED TWO IDEOGRAPHS ERA NAME HEISEI')]
    case SQUARE_ERA_NAME_HEISEI = "\u{337B}";

    #[Info(id: 0x337C, name: 'SQUARE ERA NAME SYOUWA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED TWO IDEOGRAPHS ERA NAME SYOUWA')]
    case SQUARE_ERA_NAME_SYOUWA = "\u{337C}";

    #[Info(id: 0x337D, name: 'SQUARE ERA NAME TAISYOU', category: Cat::Other_Symbol, unicode1Name: 'SQUARED TWO IDEOGRAPHS ERA NAME TAISYOU')]
    case SQUARE_ERA_NAME_TAISYOU = "\u{337D}";

    #[Info(id: 0x337E, name: 'SQUARE ERA NAME MEIZI', category: Cat::Other_Symbol, unicode1Name: 'SQUARED TWO IDEOGRAPHS ERA NAME MEIZI')]
    case SQUARE_ERA_NAME_MEIZI = "\u{337E}";

    #[Info(id: 0x337F, name: 'SQUARE CORPORATION', category: Cat::Other_Symbol, unicode1Name: 'SQUARED FOUR IDEOGRAPHS CORPORATION', informativeAliases: ['kabusiki-gaisya'])]
    case SQUARE_CORPORATION = "\u{337F}";

    #[Info(id: 0x3380, name: 'SQUARE PA AMPS', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PA AMPS')]
    case SQUARE_PA_AMPS = "\u{3380}";

    #[Info(id: 0x3381, name: 'SQUARE NA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED NA')]
    case SQUARE_NA = "\u{3381}";

    #[Info(id: 0x3382, name: 'SQUARE MU A', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MU A')]
    case SQUARE_MU_A = "\u{3382}";

    #[Info(id: 0x3383, name: 'SQUARE MA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MA')]
    case SQUARE_MA = "\u{3383}";

    #[Info(id: 0x3384, name: 'SQUARE KA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KA')]
    case SQUARE_KA = "\u{3384}";

    #[Info(id: 0x3385, name: 'SQUARE KB', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KB')]
    case SQUARE_KB = "\u{3385}";

    #[Info(id: 0x3386, name: 'SQUARE MB', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MB')]
    case SQUARE_MB = "\u{3386}";

    #[Info(id: 0x3387, name: 'SQUARE GB', category: Cat::Other_Symbol, unicode1Name: 'SQUARED GB')]
    case SQUARE_GB = "\u{3387}";

    #[Info(id: 0x3388, name: 'SQUARE CAL', category: Cat::Other_Symbol, unicode1Name: 'SQUARED CAL')]
    case SQUARE_CAL = "\u{3388}";

    #[Info(id: 0x3389, name: 'SQUARE KCAL', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KCAL')]
    case SQUARE_KCAL = "\u{3389}";

    #[Info(id: 0x338A, name: 'SQUARE PF', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PF')]
    case SQUARE_PF = "\u{338A}";

    #[Info(id: 0x338B, name: 'SQUARE NF', category: Cat::Other_Symbol, unicode1Name: 'SQUARED NF')]
    case SQUARE_NF = "\u{338B}";

    #[Info(id: 0x338C, name: 'SQUARE MU F', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MU F')]
    case SQUARE_MU_F = "\u{338C}";

    #[Info(id: 0x338D, name: 'SQUARE MU G', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MU G')]
    case SQUARE_MU_G = "\u{338D}";

    #[Info(id: 0x338E, name: 'SQUARE MG', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MG')]
    case SQUARE_MG = "\u{338E}";

    #[Info(id: 0x338F, name: 'SQUARE KG', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KG')]
    case SQUARE_KG = "\u{338F}";

    #[Info(id: 0x3390, name: 'SQUARE HZ', category: Cat::Other_Symbol, unicode1Name: 'SQUARED HZ')]
    case SQUARE_HZ = "\u{3390}";

    #[Info(id: 0x3391, name: 'SQUARE KHZ', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KHZ')]
    case SQUARE_KHZ = "\u{3391}";

    #[Info(id: 0x3392, name: 'SQUARE MHZ', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MHZ')]
    case SQUARE_MHZ = "\u{3392}";

    #[Info(id: 0x3393, name: 'SQUARE GHZ', category: Cat::Other_Symbol, unicode1Name: 'SQUARED GHZ')]
    case SQUARE_GHZ = "\u{3393}";

    #[Info(id: 0x3394, name: 'SQUARE THZ', category: Cat::Other_Symbol, unicode1Name: 'SQUARED THZ')]
    case SQUARE_THZ = "\u{3394}";

    #[Info(id: 0x3395, name: 'SQUARE MU L', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MU L')]
    case SQUARE_MU_L = "\u{3395}";

    #[Info(id: 0x3396, name: 'SQUARE ML', category: Cat::Other_Symbol, unicode1Name: 'SQUARED ML')]
    case SQUARE_ML = "\u{3396}";

    #[Info(id: 0x3397, name: 'SQUARE DL', category: Cat::Other_Symbol, unicode1Name: 'SQUARED DL')]
    case SQUARE_DL = "\u{3397}";

    #[Info(id: 0x3398, name: 'SQUARE KL', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KL')]
    case SQUARE_KL = "\u{3398}";

    #[Info(id: 0x3399, name: 'SQUARE FM', category: Cat::Other_Symbol, unicode1Name: 'SQUARED FM')]
    case SQUARE_FM = "\u{3399}";

    #[Info(id: 0x339A, name: 'SQUARE NM', category: Cat::Other_Symbol, unicode1Name: 'SQUARED NM')]
    case SQUARE_NM = "\u{339A}";

    #[Info(id: 0x339B, name: 'SQUARE MU M', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MU M')]
    case SQUARE_MU_M = "\u{339B}";

    #[Info(id: 0x339C, name: 'SQUARE MM', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MM')]
    case SQUARE_MM = "\u{339C}";

    #[Info(id: 0x339D, name: 'SQUARE CM', category: Cat::Other_Symbol, unicode1Name: 'SQUARED CM')]
    case SQUARE_CM = "\u{339D}";

    #[Info(id: 0x339E, name: 'SQUARE KM', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KM')]
    case SQUARE_KM = "\u{339E}";

    #[Info(id: 0x339F, name: 'SQUARE MM SQUARED', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MM SQUARED')]
    case SQUARE_MM_SQUARED = "\u{339F}";

    #[Info(id: 0x33A0, name: 'SQUARE CM SQUARED', category: Cat::Other_Symbol, unicode1Name: 'SQUARED CM SQUARED')]
    case SQUARE_CM_SQUARED = "\u{33A0}";

    #[Info(id: 0x33A1, name: 'SQUARE M SQUARED', category: Cat::Other_Symbol, unicode1Name: 'SQUARED M SQUARED')]
    case SQUARE_M_SQUARED = "\u{33A1}";

    #[Info(id: 0x33A2, name: 'SQUARE KM SQUARED', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KM SQUARED')]
    case SQUARE_KM_SQUARED = "\u{33A2}";

    #[Info(id: 0x33A3, name: 'SQUARE MM CUBED', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MM CUBED')]
    case SQUARE_MM_CUBED = "\u{33A3}";

    #[Info(id: 0x33A4, name: 'SQUARE CM CUBED', category: Cat::Other_Symbol, unicode1Name: 'SQUARED CM CUBED')]
    case SQUARE_CM_CUBED = "\u{33A4}";

    #[Info(id: 0x33A5, name: 'SQUARE M CUBED', category: Cat::Other_Symbol, unicode1Name: 'SQUARED M CUBED')]
    case SQUARE_M_CUBED = "\u{33A5}";

    #[Info(id: 0x33A6, name: 'SQUARE KM CUBED', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KM CUBED')]
    case SQUARE_KM_CUBED = "\u{33A6}";

    #[Info(id: 0x33A7, name: 'SQUARE M OVER S', category: Cat::Other_Symbol, unicode1Name: 'SQUARED M OVER S')]
    case SQUARE_M_OVER_S = "\u{33A7}";

    #[Info(id: 0x33A8, name: 'SQUARE M OVER S SQUARED', category: Cat::Other_Symbol, unicode1Name: 'SQUARED M OVER S SQUARED')]
    case SQUARE_M_OVER_S_SQUARED = "\u{33A8}";

    #[Info(id: 0x33A9, name: 'SQUARE PA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PA')]
    case SQUARE_PA = "\u{33A9}";

    #[Info(id: 0x33AA, name: 'SQUARE KPA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KPA')]
    case SQUARE_KPA = "\u{33AA}";

    #[Info(id: 0x33AB, name: 'SQUARE MPA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MPA')]
    case SQUARE_MPA = "\u{33AB}";

    #[Info(id: 0x33AC, name: 'SQUARE GPA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED GPA')]
    case SQUARE_GPA = "\u{33AC}";

    #[Info(id: 0x33AD, name: 'SQUARE RAD', category: Cat::Other_Symbol, unicode1Name: 'SQUARED RAD')]
    case SQUARE_RAD = "\u{33AD}";

    #[Info(id: 0x33AE, name: 'SQUARE RAD OVER S', category: Cat::Other_Symbol, unicode1Name: 'SQUARED RAD OVER S')]
    case SQUARE_RAD_OVER_S = "\u{33AE}";

    #[Info(id: 0x33AF, name: 'SQUARE RAD OVER S SQUARED', category: Cat::Other_Symbol, unicode1Name: 'SQUARED RAD OVER S SQUARED')]
    case SQUARE_RAD_OVER_S_SQUARED = "\u{33AF}";

    #[Info(id: 0x33B0, name: 'SQUARE PS', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PS')]
    case SQUARE_PS = "\u{33B0}";

    #[Info(id: 0x33B1, name: 'SQUARE NS', category: Cat::Other_Symbol, unicode1Name: 'SQUARED NS')]
    case SQUARE_NS = "\u{33B1}";

    #[Info(id: 0x33B2, name: 'SQUARE MU S', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MU S')]
    case SQUARE_MU_S = "\u{33B2}";

    #[Info(id: 0x33B3, name: 'SQUARE MS', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MS')]
    case SQUARE_MS = "\u{33B3}";

    #[Info(id: 0x33B4, name: 'SQUARE PV', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PV')]
    case SQUARE_PV = "\u{33B4}";

    #[Info(id: 0x33B5, name: 'SQUARE NV', category: Cat::Other_Symbol, unicode1Name: 'SQUARED NV')]
    case SQUARE_NV = "\u{33B5}";

    #[Info(id: 0x33B6, name: 'SQUARE MU V', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MU V')]
    case SQUARE_MU_V = "\u{33B6}";

    #[Info(id: 0x33B7, name: 'SQUARE MV', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MV')]
    case SQUARE_MV = "\u{33B7}";

    #[Info(id: 0x33B8, name: 'SQUARE KV', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KV')]
    case SQUARE_KV = "\u{33B8}";

    #[Info(id: 0x33B9, name: 'SQUARE MV MEGA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MV MEGA')]
    case SQUARE_MV_MEGA = "\u{33B9}";

    #[Info(id: 0x33BA, name: 'SQUARE PW', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PW')]
    case SQUARE_PW = "\u{33BA}";

    #[Info(id: 0x33BB, name: 'SQUARE NW', category: Cat::Other_Symbol, unicode1Name: 'SQUARED NW')]
    case SQUARE_NW = "\u{33BB}";

    #[Info(id: 0x33BC, name: 'SQUARE MU W', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MU W')]
    case SQUARE_MU_W = "\u{33BC}";

    #[Info(id: 0x33BD, name: 'SQUARE MW', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MW')]
    case SQUARE_MW = "\u{33BD}";

    #[Info(id: 0x33BE, name: 'SQUARE KW', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KW')]
    case SQUARE_KW = "\u{33BE}";

    #[Info(id: 0x33BF, name: 'SQUARE MW MEGA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MW MEGA')]
    case SQUARE_MW_MEGA = "\u{33BF}";

    #[Info(id: 0x33C0, name: 'SQUARE K OHM', category: Cat::Other_Symbol, unicode1Name: 'SQUARED K OHM')]
    case SQUARE_K_OHM = "\u{33C0}";

    #[Info(id: 0x33C1, name: 'SQUARE M OHM', category: Cat::Other_Symbol, unicode1Name: 'SQUARED M OHM')]
    case SQUARE_M_OHM = "\u{33C1}";

    #[Info(id: 0x33C2, name: 'SQUARE AM', category: Cat::Other_Symbol, unicode1Name: 'SQUARED AM')]
    case SQUARE_AM = "\u{33C2}";

    #[Info(id: 0x33C3, name: 'SQUARE BQ', category: Cat::Other_Symbol, unicode1Name: 'SQUARED BQ')]
    case SQUARE_BQ = "\u{33C3}";

    #[Info(id: 0x33C4, name: 'SQUARE CC', category: Cat::Other_Symbol, unicode1Name: 'SQUARED CC')]
    case SQUARE_CC = "\u{33C4}";

    #[Info(id: 0x33C5, name: 'SQUARE CD', category: Cat::Other_Symbol, unicode1Name: 'SQUARED CD')]
    case SQUARE_CD = "\u{33C5}";

    #[Info(id: 0x33C6, name: 'SQUARE C OVER KG', category: Cat::Other_Symbol, unicode1Name: 'SQUARED C OVER KG')]
    case SQUARE_C_OVER_KG = "\u{33C6}";

    #[Info(id: 0x33C7, name: 'SQUARE CO', category: Cat::Other_Symbol, unicode1Name: 'SQUARED CO')]
    case SQUARE_CO = "\u{33C7}";

    #[Info(id: 0x33C8, name: 'SQUARE DB', category: Cat::Other_Symbol, unicode1Name: 'SQUARED DB')]
    case SQUARE_DB = "\u{33C8}";

    #[Info(id: 0x33C9, name: 'SQUARE GY', category: Cat::Other_Symbol, unicode1Name: 'SQUARED GY')]
    case SQUARE_GY = "\u{33C9}";

    #[Info(id: 0x33CA, name: 'SQUARE HA', category: Cat::Other_Symbol, unicode1Name: 'SQUARED HA')]
    case SQUARE_HA = "\u{33CA}";

    #[Info(id: 0x33CB, name: 'SQUARE HP', category: Cat::Other_Symbol, unicode1Name: 'SQUARED HP')]
    case SQUARE_HP = "\u{33CB}";

    #[Info(id: 0x33CC, name: 'SQUARE IN', category: Cat::Other_Symbol, unicode1Name: 'SQUARED IN')]
    case SQUARE_IN = "\u{33CC}";

    #[Info(id: 0x33CD, name: 'SQUARE KK', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KK')]
    case SQUARE_KK = "\u{33CD}";

    #[Info(id: 0x33CE, name: 'SQUARE KM CAPITAL', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KM CAPITAL')]
    case SQUARE_KM_CAPITAL = "\u{33CE}";

    #[Info(id: 0x33CF, name: 'SQUARE KT', category: Cat::Other_Symbol, unicode1Name: 'SQUARED KT')]
    case SQUARE_KT = "\u{33CF}";

    #[Info(id: 0x33D0, name: 'SQUARE LM', category: Cat::Other_Symbol, unicode1Name: 'SQUARED LM')]
    case SQUARE_LM = "\u{33D0}";

    #[Info(id: 0x33D1, name: 'SQUARE LN', category: Cat::Other_Symbol, unicode1Name: 'SQUARED LN')]
    case SQUARE_LN = "\u{33D1}";

    #[Info(id: 0x33D2, name: 'SQUARE LOG', category: Cat::Other_Symbol, unicode1Name: 'SQUARED LOG')]
    case SQUARE_LOG = "\u{33D2}";

    #[Info(id: 0x33D3, name: 'SQUARE LX', category: Cat::Other_Symbol, unicode1Name: 'SQUARED LX')]
    case SQUARE_LX = "\u{33D3}";

    #[Info(id: 0x33D4, name: 'SQUARE MB SMALL', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MB SMALL')]
    case SQUARE_MB_SMALL = "\u{33D4}";

    #[Info(id: 0x33D5, name: 'SQUARE MIL', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MIL')]
    case SQUARE_MIL = "\u{33D5}";

    #[Info(id: 0x33D6, name: 'SQUARE MOL', category: Cat::Other_Symbol, unicode1Name: 'SQUARED MOL')]
    case SQUARE_MOL = "\u{33D6}";

    #[Info(id: 0x33D7, name: 'SQUARE PH', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PH')]
    case SQUARE_PH = "\u{33D7}";

    #[Info(id: 0x33D8, name: 'SQUARE PM', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PM')]
    case SQUARE_PM = "\u{33D8}";

    #[Info(id: 0x33D9, name: 'SQUARE PPM', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PPM')]
    case SQUARE_PPM = "\u{33D9}";

    #[Info(id: 0x33DA, name: 'SQUARE PR', category: Cat::Other_Symbol, unicode1Name: 'SQUARED PR')]
    case SQUARE_PR = "\u{33DA}";

    #[Info(id: 0x33DB, name: 'SQUARE SR', category: Cat::Other_Symbol, unicode1Name: 'SQUARED SR')]
    case SQUARE_SR = "\u{33DB}";

    #[Info(id: 0x33DC, name: 'SQUARE SV', category: Cat::Other_Symbol, unicode1Name: 'SQUARED SV')]
    case SQUARE_SV = "\u{33DC}";

    #[Info(id: 0x33DD, name: 'SQUARE WB', category: Cat::Other_Symbol, unicode1Name: 'SQUARED WB')]
    case SQUARE_WB = "\u{33DD}";

    #[Info(id: 0x33DE, name: 'SQUARE V OVER M', category: Cat::Other_Symbol)]
    case SQUARE_V_OVER_M = "\u{33DE}";

    #[Info(id: 0x33DF, name: 'SQUARE A OVER M', category: Cat::Other_Symbol)]
    case SQUARE_A_OVER_M = "\u{33DF}";

    #[Info(id: 0x33E0, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY ONE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_ONE = "\u{33E0}";

    #[Info(id: 0x33E1, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWO', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TWO = "\u{33E1}";

    #[Info(id: 0x33E2, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY THREE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_THREE = "\u{33E2}";

    #[Info(id: 0x33E3, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY FOUR', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_FOUR = "\u{33E3}";

    #[Info(id: 0x33E4, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY FIVE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_FIVE = "\u{33E4}";

    #[Info(id: 0x33E5, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY SIX', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_SIX = "\u{33E5}";

    #[Info(id: 0x33E6, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY SEVEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_SEVEN = "\u{33E6}";

    #[Info(id: 0x33E7, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY EIGHT', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_EIGHT = "\u{33E7}";

    #[Info(id: 0x33E8, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY NINE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_NINE = "\u{33E8}";

    #[Info(id: 0x33E9, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TEN = "\u{33E9}";

    #[Info(id: 0x33EA, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY ELEVEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_ELEVEN = "\u{33EA}";

    #[Info(id: 0x33EB, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWELVE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TWELVE = "\u{33EB}";

    #[Info(id: 0x33EC, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY THIRTEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_THIRTEEN = "\u{33EC}";

    #[Info(id: 0x33ED, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY FOURTEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_FOURTEEN = "\u{33ED}";

    #[Info(id: 0x33EE, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY FIFTEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_FIFTEEN = "\u{33EE}";

    #[Info(id: 0x33EF, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY SIXTEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_SIXTEEN = "\u{33EF}";

    #[Info(id: 0x33F0, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY SEVENTEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_SEVENTEEN = "\u{33F0}";

    #[Info(id: 0x33F1, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY EIGHTEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_EIGHTEEN = "\u{33F1}";

    #[Info(id: 0x33F2, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY NINETEEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_NINETEEN = "\u{33F2}";

    #[Info(id: 0x33F3, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TWENTY = "\u{33F3}";

    #[Info(id: 0x33F4, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-ONE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TWENTY_ONE = "\u{33F4}";

    #[Info(id: 0x33F5, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-TWO', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TWENTY_TWO = "\u{33F5}";

    #[Info(id: 0x33F6, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-THREE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TWENTY_THREE = "\u{33F6}";

    #[Info(id: 0x33F7, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-FOUR', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TWENTY_FOUR = "\u{33F7}";

    #[Info(id: 0x33F8, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-FIVE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TWENTY_FIVE = "\u{33F8}";

    #[Info(id: 0x33F9, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-SIX', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TWENTY_SIX = "\u{33F9}";

    #[Info(id: 0x33FA, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-SEVEN', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TWENTY_SEVEN = "\u{33FA}";

    #[Info(id: 0x33FB, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-EIGHT', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TWENTY_EIGHT = "\u{33FB}";

    #[Info(id: 0x33FC, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-NINE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_TWENTY_NINE = "\u{33FC}";

    #[Info(id: 0x33FD, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY THIRTY', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_THIRTY = "\u{33FD}";

    #[Info(id: 0x33FE, name: 'IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY THIRTY-ONE', category: Cat::Other_Symbol)]
    case IDEOGRAPHIC_TELEGRAPH_SYMBOL_FOR_DAY_THIRTY_ONE = "\u{33FE}";

    #[Info(id: 0x33FF, name: 'SQUARE GAL', category: Cat::Other_Symbol)]
    case SQUARE_GAL = "\u{33FF}";
}
