<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Coptic_Epact_Numbers: string
{
    #[Info(id: 0x102E0, name: 'COPTIC EPACT THOUSANDS MARK', category: Cat::Nonspacing_Mark)]
    case COPTIC_EPACT_THOUSANDS_MARK = "\u{102E0}";

    #[Info(id: 0x102E1, name: 'COPTIC EPACT DIGIT ONE', category: Cat::Other_Number)]
    case COPTIC_EPACT_DIGIT_ONE = "\u{102E1}";

    #[Info(id: 0x102E2, name: 'COPTIC EPACT DIGIT TWO', category: Cat::Other_Number)]
    case COPTIC_EPACT_DIGIT_TWO = "\u{102E2}";

    #[Info(id: 0x102E3, name: 'COPTIC EPACT DIGIT THREE', category: Cat::Other_Number)]
    case COPTIC_EPACT_DIGIT_THREE = "\u{102E3}";

    #[Info(id: 0x102E4, name: 'COPTIC EPACT DIGIT FOUR', category: Cat::Other_Number)]
    case COPTIC_EPACT_DIGIT_FOUR = "\u{102E4}";

    #[Info(id: 0x102E5, name: 'COPTIC EPACT DIGIT FIVE', category: Cat::Other_Number)]
    case COPTIC_EPACT_DIGIT_FIVE = "\u{102E5}";

    #[Info(id: 0x102E6, name: 'COPTIC EPACT DIGIT SIX', category: Cat::Other_Number)]
    case COPTIC_EPACT_DIGIT_SIX = "\u{102E6}";

    #[Info(id: 0x102E7, name: 'COPTIC EPACT DIGIT SEVEN', category: Cat::Other_Number)]
    case COPTIC_EPACT_DIGIT_SEVEN = "\u{102E7}";

    #[Info(id: 0x102E8, name: 'COPTIC EPACT DIGIT EIGHT', category: Cat::Other_Number)]
    case COPTIC_EPACT_DIGIT_EIGHT = "\u{102E8}";

    #[Info(id: 0x102E9, name: 'COPTIC EPACT DIGIT NINE', category: Cat::Other_Number)]
    case COPTIC_EPACT_DIGIT_NINE = "\u{102E9}";

    #[Info(id: 0x102EA, name: 'COPTIC EPACT NUMBER TEN', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_TEN = "\u{102EA}";

    #[Info(id: 0x102EB, name: 'COPTIC EPACT NUMBER TWENTY', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_TWENTY = "\u{102EB}";

    #[Info(id: 0x102EC, name: 'COPTIC EPACT NUMBER THIRTY', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_THIRTY = "\u{102EC}";

    #[Info(id: 0x102ED, name: 'COPTIC EPACT NUMBER FORTY', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_FORTY = "\u{102ED}";

    #[Info(id: 0x102EE, name: 'COPTIC EPACT NUMBER FIFTY', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_FIFTY = "\u{102EE}";

    #[Info(id: 0x102EF, name: 'COPTIC EPACT NUMBER SIXTY', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_SIXTY = "\u{102EF}";

    #[Info(id: 0x102F0, name: 'COPTIC EPACT NUMBER SEVENTY', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_SEVENTY = "\u{102F0}";

    #[Info(id: 0x102F1, name: 'COPTIC EPACT NUMBER EIGHTY', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_EIGHTY = "\u{102F1}";

    #[Info(id: 0x102F2, name: 'COPTIC EPACT NUMBER NINETY', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_NINETY = "\u{102F2}";

    #[Info(id: 0x102F3, name: 'COPTIC EPACT NUMBER ONE HUNDRED', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_ONE_HUNDRED = "\u{102F3}";

    #[Info(id: 0x102F4, name: 'COPTIC EPACT NUMBER TWO HUNDRED', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_TWO_HUNDRED = "\u{102F4}";

    #[Info(id: 0x102F5, name: 'COPTIC EPACT NUMBER THREE HUNDRED', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_THREE_HUNDRED = "\u{102F5}";

    #[Info(id: 0x102F6, name: 'COPTIC EPACT NUMBER FOUR HUNDRED', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_FOUR_HUNDRED = "\u{102F6}";

    #[Info(id: 0x102F7, name: 'COPTIC EPACT NUMBER FIVE HUNDRED', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_FIVE_HUNDRED = "\u{102F7}";

    #[Info(id: 0x102F8, name: 'COPTIC EPACT NUMBER SIX HUNDRED', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_SIX_HUNDRED = "\u{102F8}";

    #[Info(id: 0x102F9, name: 'COPTIC EPACT NUMBER SEVEN HUNDRED', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_SEVEN_HUNDRED = "\u{102F9}";

    #[Info(id: 0x102FA, name: 'COPTIC EPACT NUMBER EIGHT HUNDRED', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_EIGHT_HUNDRED = "\u{102FA}";

    #[Info(id: 0x102FB, name: 'COPTIC EPACT NUMBER NINE HUNDRED', category: Cat::Other_Number)]
    case COPTIC_EPACT_NUMBER_NINE_HUNDRED = "\u{102FB}";
}
