<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Cuneiform_Numbers_and_Punctuation: string
{
    #[Info(id: 0x12400, name: 'CUNEIFORM NUMERIC SIGN TWO ASH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_TWO_ASH = "\u{12400}";

    #[Info(id: 0x12401, name: 'CUNEIFORM NUMERIC SIGN THREE ASH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_ASH = "\u{12401}";

    #[Info(id: 0x12402, name: 'CUNEIFORM NUMERIC SIGN FOUR ASH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_ASH = "\u{12402}";

    #[Info(id: 0x12403, name: 'CUNEIFORM NUMERIC SIGN FIVE ASH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_ASH = "\u{12403}";

    #[Info(id: 0x12404, name: 'CUNEIFORM NUMERIC SIGN SIX ASH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SIX_ASH = "\u{12404}";

    #[Info(id: 0x12405, name: 'CUNEIFORM NUMERIC SIGN SEVEN ASH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SEVEN_ASH = "\u{12405}";

    #[Info(id: 0x12406, name: 'CUNEIFORM NUMERIC SIGN EIGHT ASH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_EIGHT_ASH = "\u{12406}";

    #[Info(id: 0x12407, name: 'CUNEIFORM NUMERIC SIGN NINE ASH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_NINE_ASH = "\u{12407}";

    #[Info(id: 0x12408, name: 'CUNEIFORM NUMERIC SIGN THREE DISH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_DISH = "\u{12408}";

    #[Info(id: 0x12409, name: 'CUNEIFORM NUMERIC SIGN FOUR DISH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_DISH = "\u{12409}";

    #[Info(id: 0x1240A, name: 'CUNEIFORM NUMERIC SIGN FIVE DISH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_DISH = "\u{1240A}";

    #[Info(id: 0x1240B, name: 'CUNEIFORM NUMERIC SIGN SIX DISH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SIX_DISH = "\u{1240B}";

    #[Info(id: 0x1240C, name: 'CUNEIFORM NUMERIC SIGN SEVEN DISH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SEVEN_DISH = "\u{1240C}";

    #[Info(id: 0x1240D, name: 'CUNEIFORM NUMERIC SIGN EIGHT DISH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_EIGHT_DISH = "\u{1240D}";

    #[Info(id: 0x1240E, name: 'CUNEIFORM NUMERIC SIGN NINE DISH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_NINE_DISH = "\u{1240E}";

    #[Info(id: 0x1240F, name: 'CUNEIFORM NUMERIC SIGN FOUR U', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_U = "\u{1240F}";

    #[Info(id: 0x12410, name: 'CUNEIFORM NUMERIC SIGN FIVE U', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_U = "\u{12410}";

    #[Info(id: 0x12411, name: 'CUNEIFORM NUMERIC SIGN SIX U', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SIX_U = "\u{12411}";

    #[Info(id: 0x12412, name: 'CUNEIFORM NUMERIC SIGN SEVEN U', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SEVEN_U = "\u{12412}";

    #[Info(id: 0x12413, name: 'CUNEIFORM NUMERIC SIGN EIGHT U', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_EIGHT_U = "\u{12413}";

    #[Info(id: 0x12414, name: 'CUNEIFORM NUMERIC SIGN NINE U', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_NINE_U = "\u{12414}";

    #[Info(id: 0x12415, name: 'CUNEIFORM NUMERIC SIGN ONE GESH2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ONE_GESH2 = "\u{12415}";

    #[Info(id: 0x12416, name: 'CUNEIFORM NUMERIC SIGN TWO GESH2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_TWO_GESH2 = "\u{12416}";

    #[Info(id: 0x12417, name: 'CUNEIFORM NUMERIC SIGN THREE GESH2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_GESH2 = "\u{12417}";

    #[Info(id: 0x12418, name: 'CUNEIFORM NUMERIC SIGN FOUR GESH2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_GESH2 = "\u{12418}";

    #[Info(id: 0x12419, name: 'CUNEIFORM NUMERIC SIGN FIVE GESH2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_GESH2 = "\u{12419}";

    #[Info(id: 0x1241A, name: 'CUNEIFORM NUMERIC SIGN SIX GESH2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SIX_GESH2 = "\u{1241A}";

    #[Info(id: 0x1241B, name: 'CUNEIFORM NUMERIC SIGN SEVEN GESH2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SEVEN_GESH2 = "\u{1241B}";

    #[Info(id: 0x1241C, name: 'CUNEIFORM NUMERIC SIGN EIGHT GESH2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_EIGHT_GESH2 = "\u{1241C}";

    #[Info(id: 0x1241D, name: 'CUNEIFORM NUMERIC SIGN NINE GESH2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_NINE_GESH2 = "\u{1241D}";

    #[Info(id: 0x1241E, name: 'CUNEIFORM NUMERIC SIGN ONE GESHU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ONE_GESHU = "\u{1241E}";

    #[Info(id: 0x1241F, name: 'CUNEIFORM NUMERIC SIGN TWO GESHU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_TWO_GESHU = "\u{1241F}";

    #[Info(id: 0x12420, name: 'CUNEIFORM NUMERIC SIGN THREE GESHU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_GESHU = "\u{12420}";

    #[Info(id: 0x12421, name: 'CUNEIFORM NUMERIC SIGN FOUR GESHU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_GESHU = "\u{12421}";

    #[Info(id: 0x12422, name: 'CUNEIFORM NUMERIC SIGN FIVE GESHU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_GESHU = "\u{12422}";

    #[Info(id: 0x12423, name: 'CUNEIFORM NUMERIC SIGN TWO SHAR2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_TWO_SHAR2 = "\u{12423}";

    #[Info(id: 0x12424, name: 'CUNEIFORM NUMERIC SIGN THREE SHAR2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_SHAR2 = "\u{12424}";

    #[Info(id: 0x12425, name: 'CUNEIFORM NUMERIC SIGN THREE SHAR2 VARIANT FORM', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_SHAR2_VARIANT_FORM = "\u{12425}";

    #[Info(id: 0x12426, name: 'CUNEIFORM NUMERIC SIGN FOUR SHAR2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_SHAR2 = "\u{12426}";

    #[Info(id: 0x12427, name: 'CUNEIFORM NUMERIC SIGN FIVE SHAR2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_SHAR2 = "\u{12427}";

    #[Info(id: 0x12428, name: 'CUNEIFORM NUMERIC SIGN SIX SHAR2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SIX_SHAR2 = "\u{12428}";

    #[Info(id: 0x12429, name: 'CUNEIFORM NUMERIC SIGN SEVEN SHAR2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SEVEN_SHAR2 = "\u{12429}";

    #[Info(id: 0x1242A, name: 'CUNEIFORM NUMERIC SIGN EIGHT SHAR2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_EIGHT_SHAR2 = "\u{1242A}";

    #[Info(id: 0x1242B, name: 'CUNEIFORM NUMERIC SIGN NINE SHAR2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_NINE_SHAR2 = "\u{1242B}";

    #[Info(id: 0x1242C, name: 'CUNEIFORM NUMERIC SIGN ONE SHARU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ONE_SHARU = "\u{1242C}";

    #[Info(id: 0x1242D, name: 'CUNEIFORM NUMERIC SIGN TWO SHARU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_TWO_SHARU = "\u{1242D}";

    #[Info(id: 0x1242E, name: 'CUNEIFORM NUMERIC SIGN THREE SHARU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_SHARU = "\u{1242E}";

    #[Info(id: 0x1242F, name: 'CUNEIFORM NUMERIC SIGN THREE SHARU VARIANT FORM', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_SHARU_VARIANT_FORM = "\u{1242F}";

    #[Info(id: 0x12430, name: 'CUNEIFORM NUMERIC SIGN FOUR SHARU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_SHARU = "\u{12430}";

    #[Info(id: 0x12431, name: 'CUNEIFORM NUMERIC SIGN FIVE SHARU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_SHARU = "\u{12431}";

    #[Info(id: 0x12432, name: 'CUNEIFORM NUMERIC SIGN SHAR2 TIMES GAL PLUS DISH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SHAR2_TIMES_GAL_PLUS_DISH = "\u{12432}";

    #[Info(id: 0x12433, name: 'CUNEIFORM NUMERIC SIGN SHAR2 TIMES GAL PLUS MIN', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SHAR2_TIMES_GAL_PLUS_MIN = "\u{12433}";

    #[Info(id: 0x12434, name: 'CUNEIFORM NUMERIC SIGN ONE BURU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ONE_BURU = "\u{12434}";

    #[Info(id: 0x12435, name: 'CUNEIFORM NUMERIC SIGN TWO BURU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_TWO_BURU = "\u{12435}";

    #[Info(id: 0x12436, name: 'CUNEIFORM NUMERIC SIGN THREE BURU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_BURU = "\u{12436}";

    #[Info(id: 0x12437, name: 'CUNEIFORM NUMERIC SIGN THREE BURU VARIANT FORM', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_BURU_VARIANT_FORM = "\u{12437}";

    #[Info(id: 0x12438, name: 'CUNEIFORM NUMERIC SIGN FOUR BURU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_BURU = "\u{12438}";

    #[Info(id: 0x12439, name: 'CUNEIFORM NUMERIC SIGN FIVE BURU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_BURU = "\u{12439}";

    #[Info(id: 0x1243A, name: 'CUNEIFORM NUMERIC SIGN THREE VARIANT FORM ESH16', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_VARIANT_FORM_ESH16 = "\u{1243A}";

    #[Info(id: 0x1243B, name: 'CUNEIFORM NUMERIC SIGN THREE VARIANT FORM ESH21', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_VARIANT_FORM_ESH21 = "\u{1243B}";

    #[Info(id: 0x1243C, name: 'CUNEIFORM NUMERIC SIGN FOUR VARIANT FORM LIMMU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_VARIANT_FORM_LIMMU = "\u{1243C}";

    #[Info(id: 0x1243D, name: 'CUNEIFORM NUMERIC SIGN FOUR VARIANT FORM LIMMU4', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_VARIANT_FORM_LIMMU4 = "\u{1243D}";

    #[Info(id: 0x1243E, name: 'CUNEIFORM NUMERIC SIGN FOUR VARIANT FORM LIMMU A', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_VARIANT_FORM_LIMMU_A = "\u{1243E}";

    #[Info(id: 0x1243F, name: 'CUNEIFORM NUMERIC SIGN FOUR VARIANT FORM LIMMU B', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_VARIANT_FORM_LIMMU_B = "\u{1243F}";

    #[Info(id: 0x12440, name: 'CUNEIFORM NUMERIC SIGN SIX VARIANT FORM ASH9', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SIX_VARIANT_FORM_ASH9 = "\u{12440}";

    #[Info(id: 0x12441, name: 'CUNEIFORM NUMERIC SIGN SEVEN VARIANT FORM IMIN3', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SEVEN_VARIANT_FORM_IMIN3 = "\u{12441}";

    #[Info(id: 0x12442, name: 'CUNEIFORM NUMERIC SIGN SEVEN VARIANT FORM IMIN A', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SEVEN_VARIANT_FORM_IMIN_A = "\u{12442}";

    #[Info(id: 0x12443, name: 'CUNEIFORM NUMERIC SIGN SEVEN VARIANT FORM IMIN B', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SEVEN_VARIANT_FORM_IMIN_B = "\u{12443}";

    #[Info(id: 0x12444, name: 'CUNEIFORM NUMERIC SIGN EIGHT VARIANT FORM USSU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_EIGHT_VARIANT_FORM_USSU = "\u{12444}";

    #[Info(id: 0x12445, name: 'CUNEIFORM NUMERIC SIGN EIGHT VARIANT FORM USSU3', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_EIGHT_VARIANT_FORM_USSU3 = "\u{12445}";

    #[Info(id: 0x12446, name: 'CUNEIFORM NUMERIC SIGN NINE VARIANT FORM ILIMMU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_NINE_VARIANT_FORM_ILIMMU = "\u{12446}";

    #[Info(id: 0x12447, name: 'CUNEIFORM NUMERIC SIGN NINE VARIANT FORM ILIMMU3', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_NINE_VARIANT_FORM_ILIMMU3 = "\u{12447}";

    #[Info(id: 0x12448, name: 'CUNEIFORM NUMERIC SIGN NINE VARIANT FORM ILIMMU4', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_NINE_VARIANT_FORM_ILIMMU4 = "\u{12448}";

    #[Info(id: 0x12449, name: 'CUNEIFORM NUMERIC SIGN NINE VARIANT FORM ILIMMU A', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_NINE_VARIANT_FORM_ILIMMU_A = "\u{12449}";

    #[Info(id: 0x1244A, name: 'CUNEIFORM NUMERIC SIGN TWO ASH TENU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_TWO_ASH_TENU = "\u{1244A}";

    #[Info(id: 0x1244B, name: 'CUNEIFORM NUMERIC SIGN THREE ASH TENU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_ASH_TENU = "\u{1244B}";

    #[Info(id: 0x1244C, name: 'CUNEIFORM NUMERIC SIGN FOUR ASH TENU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_ASH_TENU = "\u{1244C}";

    #[Info(id: 0x1244D, name: 'CUNEIFORM NUMERIC SIGN FIVE ASH TENU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_ASH_TENU = "\u{1244D}";

    #[Info(id: 0x1244E, name: 'CUNEIFORM NUMERIC SIGN SIX ASH TENU', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SIX_ASH_TENU = "\u{1244E}";

    #[Info(id: 0x1244F, name: 'CUNEIFORM NUMERIC SIGN ONE BAN2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ONE_BAN2 = "\u{1244F}";

    #[Info(id: 0x12450, name: 'CUNEIFORM NUMERIC SIGN TWO BAN2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_TWO_BAN2 = "\u{12450}";

    #[Info(id: 0x12451, name: 'CUNEIFORM NUMERIC SIGN THREE BAN2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_THREE_BAN2 = "\u{12451}";

    #[Info(id: 0x12452, name: 'CUNEIFORM NUMERIC SIGN FOUR BAN2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_BAN2 = "\u{12452}";

    #[Info(id: 0x12453, name: 'CUNEIFORM NUMERIC SIGN FOUR BAN2 VARIANT FORM', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_BAN2_VARIANT_FORM = "\u{12453}";

    #[Info(id: 0x12454, name: 'CUNEIFORM NUMERIC SIGN FIVE BAN2', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_BAN2 = "\u{12454}";

    #[Info(id: 0x12455, name: 'CUNEIFORM NUMERIC SIGN FIVE BAN2 VARIANT FORM', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_BAN2_VARIANT_FORM = "\u{12455}";

    #[Info(id: 0x12456, name: 'CUNEIFORM NUMERIC SIGN NIGIDAMIN', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_NIGIDAMIN = "\u{12456}";

    #[Info(id: 0x12457, name: 'CUNEIFORM NUMERIC SIGN NIGIDAESH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_NIGIDAESH = "\u{12457}";

    #[Info(id: 0x12458, name: 'CUNEIFORM NUMERIC SIGN ONE ESHE3', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ONE_ESHE3 = "\u{12458}";

    #[Info(id: 0x12459, name: 'CUNEIFORM NUMERIC SIGN TWO ESHE3', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_TWO_ESHE3 = "\u{12459}";

    #[Info(id: 0x1245A, name: 'CUNEIFORM NUMERIC SIGN ONE THIRD DISH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ONE_THIRD_DISH = "\u{1245A}";

    #[Info(id: 0x1245B, name: 'CUNEIFORM NUMERIC SIGN TWO THIRDS DISH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_TWO_THIRDS_DISH = "\u{1245B}";

    #[Info(id: 0x1245C, name: 'CUNEIFORM NUMERIC SIGN FIVE SIXTHS DISH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_SIXTHS_DISH = "\u{1245C}";

    #[Info(id: 0x1245D, name: 'CUNEIFORM NUMERIC SIGN ONE THIRD VARIANT FORM A', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ONE_THIRD_VARIANT_FORM_A = "\u{1245D}";

    #[Info(id: 0x1245E, name: 'CUNEIFORM NUMERIC SIGN TWO THIRDS VARIANT FORM A', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_TWO_THIRDS_VARIANT_FORM_A = "\u{1245E}";

    #[Info(id: 0x1245F, name: 'CUNEIFORM NUMERIC SIGN ONE EIGHTH ASH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ONE_EIGHTH_ASH = "\u{1245F}";

    #[Info(id: 0x12460, name: 'CUNEIFORM NUMERIC SIGN ONE QUARTER ASH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ONE_QUARTER_ASH = "\u{12460}";

    #[Info(id: 0x12461, name: 'CUNEIFORM NUMERIC SIGN OLD ASSYRIAN ONE SIXTH', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_OLD_ASSYRIAN_ONE_SIXTH = "\u{12461}";

    #[Info(id: 0x12462, name: 'CUNEIFORM NUMERIC SIGN OLD ASSYRIAN ONE QUARTER', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_OLD_ASSYRIAN_ONE_QUARTER = "\u{12462}";

    #[Info(id: 0x12463, name: 'CUNEIFORM NUMERIC SIGN ONE QUARTER GUR', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ONE_QUARTER_GUR = "\u{12463}";

    #[Info(id: 0x12464, name: 'CUNEIFORM NUMERIC SIGN ONE HALF GUR', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ONE_HALF_GUR = "\u{12464}";

    #[Info(id: 0x12465, name: 'CUNEIFORM NUMERIC SIGN ELAMITE ONE THIRD', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ELAMITE_ONE_THIRD = "\u{12465}";

    #[Info(id: 0x12466, name: 'CUNEIFORM NUMERIC SIGN ELAMITE TWO THIRDS', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ELAMITE_TWO_THIRDS = "\u{12466}";

    #[Info(id: 0x12467, name: 'CUNEIFORM NUMERIC SIGN ELAMITE FORTY', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ELAMITE_FORTY = "\u{12467}";

    #[Info(id: 0x12468, name: 'CUNEIFORM NUMERIC SIGN ELAMITE FIFTY', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_ELAMITE_FIFTY = "\u{12468}";

    #[Info(id: 0x12469, name: 'CUNEIFORM NUMERIC SIGN FOUR U VARIANT FORM', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FOUR_U_VARIANT_FORM = "\u{12469}";

    #[Info(id: 0x1246A, name: 'CUNEIFORM NUMERIC SIGN FIVE U VARIANT FORM', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_FIVE_U_VARIANT_FORM = "\u{1246A}";

    #[Info(id: 0x1246B, name: 'CUNEIFORM NUMERIC SIGN SIX U VARIANT FORM', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SIX_U_VARIANT_FORM = "\u{1246B}";

    #[Info(id: 0x1246C, name: 'CUNEIFORM NUMERIC SIGN SEVEN U VARIANT FORM', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_SEVEN_U_VARIANT_FORM = "\u{1246C}";

    #[Info(id: 0x1246D, name: 'CUNEIFORM NUMERIC SIGN EIGHT U VARIANT FORM', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_EIGHT_U_VARIANT_FORM = "\u{1246D}";

    #[Info(id: 0x1246E, name: 'CUNEIFORM NUMERIC SIGN NINE U VARIANT FORM', category: Cat::Letter_Number)]
    case CUNEIFORM_NUMERIC_SIGN_NINE_U_VARIANT_FORM = "\u{1246E}";

    #[Info(id: 0x12470, name: 'CUNEIFORM PUNCTUATION SIGN OLD ASSYRIAN WORD DIVIDER', category: Cat::Other_Punctuation)]
    case CUNEIFORM_PUNCTUATION_SIGN_OLD_ASSYRIAN_WORD_DIVIDER = "\u{12470}";

    #[Info(id: 0x12471, name: 'CUNEIFORM PUNCTUATION SIGN VERTICAL COLON', category: Cat::Other_Punctuation)]
    case CUNEIFORM_PUNCTUATION_SIGN_VERTICAL_COLON = "\u{12471}";

    #[Info(id: 0x12472, name: 'CUNEIFORM PUNCTUATION SIGN DIAGONAL COLON', category: Cat::Other_Punctuation)]
    case CUNEIFORM_PUNCTUATION_SIGN_DIAGONAL_COLON = "\u{12472}";

    #[Info(id: 0x12473, name: 'CUNEIFORM PUNCTUATION SIGN DIAGONAL TRICOLON', category: Cat::Other_Punctuation)]
    case CUNEIFORM_PUNCTUATION_SIGN_DIAGONAL_TRICOLON = "\u{12473}";

    #[Info(id: 0x12474, name: 'CUNEIFORM PUNCTUATION SIGN DIAGONAL QUADCOLON', category: Cat::Other_Punctuation)]
    case CUNEIFORM_PUNCTUATION_SIGN_DIAGONAL_QUADCOLON = "\u{12474}";
}
