<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Currency_Symbols: string
{
    #[Info(id: 8352, name: 'EURO-CURRENCY SIGN', category: Cat::Currency_Symbol)]
    case EURO_CURRENCY_SIGN = "\u{20A0}";

    #[Info(id: 8353, name: 'COLON SIGN', category: Cat::Currency_Symbol)]
    case COLON_SIGN = "\u{20A1}";

    #[Info(id: 8354, name: 'CRUZEIRO SIGN', category: Cat::Currency_Symbol)]
    case CRUZEIRO_SIGN = "\u{20A2}";

    #[Info(id: 8355, name: 'FRENCH FRANC SIGN', category: Cat::Currency_Symbol)]
    case FRENCH_FRANC_SIGN = "\u{20A3}";

    #[Info(id: 8356, name: 'LIRA SIGN', category: Cat::Currency_Symbol)]
    case LIRA_SIGN = "\u{20A4}";

    #[Info(id: 8357, name: 'MILL SIGN', category: Cat::Currency_Symbol)]
    case MILL_SIGN = "\u{20A5}";

    #[Info(id: 8358, name: 'NAIRA SIGN', category: Cat::Currency_Symbol)]
    case NAIRA_SIGN = "\u{20A6}";

    #[Info(id: 8359, name: 'PESETA SIGN', category: Cat::Currency_Symbol)]
    case PESETA_SIGN = "\u{20A7}";

    #[Info(id: 8360, name: 'RUPEE SIGN', category: Cat::Currency_Symbol)]
    case RUPEE_SIGN = "\u{20A8}";

    #[Info(id: 8361, name: 'WON SIGN', category: Cat::Currency_Symbol)]
    case WON_SIGN = "\u{20A9}";

    #[Info(id: 8362, name: 'NEW SHEQEL SIGN', category: Cat::Currency_Symbol)]
    case NEW_SHEQEL_SIGN = "\u{20AA}";

    #[Info(id: 8363, name: 'DONG SIGN', category: Cat::Currency_Symbol)]
    case DONG_SIGN = "\u{20AB}";

    #[Info(id: 8364, name: 'EURO SIGN', category: Cat::Currency_Symbol)]
    case EURO_SIGN = "\u{20AC}";

    #[Info(id: 8365, name: 'KIP SIGN', category: Cat::Currency_Symbol)]
    case KIP_SIGN = "\u{20AD}";

    #[Info(id: 8366, name: 'TUGRIK SIGN', category: Cat::Currency_Symbol)]
    case TUGRIK_SIGN = "\u{20AE}";

    #[Info(id: 8367, name: 'DRACHMA SIGN', category: Cat::Currency_Symbol)]
    case DRACHMA_SIGN = "\u{20AF}";

    #[Info(id: 8368, name: 'GERMAN PENNY SIGN', category: Cat::Currency_Symbol)]
    case GERMAN_PENNY_SIGN = "\u{20B0}";

    #[Info(id: 8369, name: 'PESO SIGN', category: Cat::Currency_Symbol)]
    case PESO_SIGN = "\u{20B1}";

    #[Info(id: 8370, name: 'GUARANI SIGN', category: Cat::Currency_Symbol)]
    case GUARANI_SIGN = "\u{20B2}";

    #[Info(id: 8371, name: 'AUSTRAL SIGN', category: Cat::Currency_Symbol)]
    case AUSTRAL_SIGN = "\u{20B3}";

    #[Info(id: 8372, name: 'HRYVNIA SIGN', category: Cat::Currency_Symbol)]
    case HRYVNIA_SIGN = "\u{20B4}";

    #[Info(id: 8373, name: 'CEDI SIGN', category: Cat::Currency_Symbol)]
    case CEDI_SIGN = "\u{20B5}";

    #[Info(id: 8374, name: 'LIVRE TOURNOIS SIGN', category: Cat::Currency_Symbol)]
    case LIVRE_TOURNOIS_SIGN = "\u{20B6}";

    #[Info(id: 8375, name: 'SPESMILO SIGN', category: Cat::Currency_Symbol)]
    case SPESMILO_SIGN = "\u{20B7}";

    #[Info(id: 8376, name: 'TENGE SIGN', category: Cat::Currency_Symbol)]
    case TENGE_SIGN = "\u{20B8}";

    #[Info(id: 8377, name: 'INDIAN RUPEE SIGN', category: Cat::Currency_Symbol)]
    case INDIAN_RUPEE_SIGN = "\u{20B9}";

    #[Info(id: 8378, name: 'TURKISH LIRA SIGN', category: Cat::Currency_Symbol)]
    case TURKISH_LIRA_SIGN = "\u{20BA}";

    #[Info(id: 8379, name: 'NORDIC MARK SIGN', category: Cat::Currency_Symbol)]
    case NORDIC_MARK_SIGN = "\u{20BB}";

    #[Info(id: 8380, name: 'MANAT SIGN', category: Cat::Currency_Symbol)]
    case MANAT_SIGN = "\u{20BC}";

    #[Info(id: 8381, name: 'RUBLE SIGN', category: Cat::Currency_Symbol)]
    case RUBLE_SIGN = "\u{20BD}";

    #[Info(id: 8382, name: 'LARI SIGN', category: Cat::Currency_Symbol)]
    case LARI_SIGN = "\u{20BE}";

    #[Info(id: 8383, name: 'BITCOIN SIGN', category: Cat::Currency_Symbol)]
    case BITCOIN_SIGN = "\u{20BF}";

    #[Info(id: 8384, name: 'SOM SIGN', category: Cat::Currency_Symbol)]
    case SOM_SIGN = "\u{20C0}";
}
