<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Cyrillic_ExtendedD: string
{
    #[Info(id: 0x1E030, name: 'MODIFIER LETTER CYRILLIC SMALL A', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_A = "\u{1E030}";

    #[Info(id: 0x1E031, name: 'MODIFIER LETTER CYRILLIC SMALL BE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_BE = "\u{1E031}";

    #[Info(id: 0x1E032, name: 'MODIFIER LETTER CYRILLIC SMALL VE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_VE = "\u{1E032}";

    #[Info(id: 0x1E033, name: 'MODIFIER LETTER CYRILLIC SMALL GHE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_GHE = "\u{1E033}";

    #[Info(id: 0x1E034, name: 'MODIFIER LETTER CYRILLIC SMALL DE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_DE = "\u{1E034}";

    #[Info(id: 0x1E035, name: 'MODIFIER LETTER CYRILLIC SMALL IE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_IE = "\u{1E035}";

    #[Info(id: 0x1E036, name: 'MODIFIER LETTER CYRILLIC SMALL ZHE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_ZHE = "\u{1E036}";

    #[Info(id: 0x1E037, name: 'MODIFIER LETTER CYRILLIC SMALL ZE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_ZE = "\u{1E037}";

    #[Info(id: 0x1E038, name: 'MODIFIER LETTER CYRILLIC SMALL I', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_I = "\u{1E038}";

    #[Info(id: 0x1E039, name: 'MODIFIER LETTER CYRILLIC SMALL KA', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_KA = "\u{1E039}";

    #[Info(id: 0x1E03A, name: 'MODIFIER LETTER CYRILLIC SMALL EL', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_EL = "\u{1E03A}";

    #[Info(id: 0x1E03B, name: 'MODIFIER LETTER CYRILLIC SMALL EM', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_EM = "\u{1E03B}";

    #[Info(id: 0x1E03C, name: 'MODIFIER LETTER CYRILLIC SMALL O', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_O = "\u{1E03C}";

    #[Info(id: 0x1E03D, name: 'MODIFIER LETTER CYRILLIC SMALL PE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_PE = "\u{1E03D}";

    #[Info(id: 0x1E03E, name: 'MODIFIER LETTER CYRILLIC SMALL ER', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_ER = "\u{1E03E}";

    #[Info(id: 0x1E03F, name: 'MODIFIER LETTER CYRILLIC SMALL ES', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_ES = "\u{1E03F}";

    #[Info(id: 0x1E040, name: 'MODIFIER LETTER CYRILLIC SMALL TE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_TE = "\u{1E040}";

    #[Info(id: 0x1E041, name: 'MODIFIER LETTER CYRILLIC SMALL U', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_U = "\u{1E041}";

    #[Info(id: 0x1E042, name: 'MODIFIER LETTER CYRILLIC SMALL EF', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_EF = "\u{1E042}";

    #[Info(id: 0x1E043, name: 'MODIFIER LETTER CYRILLIC SMALL HA', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_HA = "\u{1E043}";

    #[Info(id: 0x1E044, name: 'MODIFIER LETTER CYRILLIC SMALL TSE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_TSE = "\u{1E044}";

    #[Info(id: 0x1E045, name: 'MODIFIER LETTER CYRILLIC SMALL CHE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_CHE = "\u{1E045}";

    #[Info(id: 0x1E046, name: 'MODIFIER LETTER CYRILLIC SMALL SHA', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_SHA = "\u{1E046}";

    #[Info(id: 0x1E047, name: 'MODIFIER LETTER CYRILLIC SMALL YERU', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_YERU = "\u{1E047}";

    #[Info(id: 0x1E048, name: 'MODIFIER LETTER CYRILLIC SMALL E', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_E = "\u{1E048}";

    #[Info(id: 0x1E049, name: 'MODIFIER LETTER CYRILLIC SMALL YU', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_YU = "\u{1E049}";

    #[Info(id: 0x1E04A, name: 'MODIFIER LETTER CYRILLIC SMALL DZZE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_DZZE = "\u{1E04A}";

    #[Info(id: 0x1E04B, name: 'MODIFIER LETTER CYRILLIC SMALL SCHWA', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_SCHWA = "\u{1E04B}";

    #[Info(id: 0x1E04C, name: 'MODIFIER LETTER CYRILLIC SMALL BYELORUSSIAN-UKRAINIAN I', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_BYELORUSSIAN_UKRAINIAN_I = "\u{1E04C}";

    #[Info(id: 0x1E04D, name: 'MODIFIER LETTER CYRILLIC SMALL JE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_JE = "\u{1E04D}";

    #[Info(id: 0x1E04E, name: 'MODIFIER LETTER CYRILLIC SMALL BARRED O', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_BARRED_O = "\u{1E04E}";

    #[Info(id: 0x1E04F, name: 'MODIFIER LETTER CYRILLIC SMALL STRAIGHT U', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_STRAIGHT_U = "\u{1E04F}";

    #[Info(id: 0x1E050, name: 'MODIFIER LETTER CYRILLIC SMALL PALOCHKA', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_PALOCHKA = "\u{1E050}";

    #[Info(id: 0x1E051, name: 'CYRILLIC SUBSCRIPT SMALL LETTER A', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_A = "\u{1E051}";

    #[Info(id: 0x1E052, name: 'CYRILLIC SUBSCRIPT SMALL LETTER BE', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_BE = "\u{1E052}";

    #[Info(id: 0x1E053, name: 'CYRILLIC SUBSCRIPT SMALL LETTER VE', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_VE = "\u{1E053}";

    #[Info(id: 0x1E054, name: 'CYRILLIC SUBSCRIPT SMALL LETTER GHE', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_GHE = "\u{1E054}";

    #[Info(id: 0x1E055, name: 'CYRILLIC SUBSCRIPT SMALL LETTER DE', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_DE = "\u{1E055}";

    #[Info(id: 0x1E056, name: 'CYRILLIC SUBSCRIPT SMALL LETTER IE', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_IE = "\u{1E056}";

    #[Info(id: 0x1E057, name: 'CYRILLIC SUBSCRIPT SMALL LETTER ZHE', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_ZHE = "\u{1E057}";

    #[Info(id: 0x1E058, name: 'CYRILLIC SUBSCRIPT SMALL LETTER ZE', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_ZE = "\u{1E058}";

    #[Info(id: 0x1E059, name: 'CYRILLIC SUBSCRIPT SMALL LETTER I', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_I = "\u{1E059}";

    #[Info(id: 0x1E05A, name: 'CYRILLIC SUBSCRIPT SMALL LETTER KA', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_KA = "\u{1E05A}";

    #[Info(id: 0x1E05B, name: 'CYRILLIC SUBSCRIPT SMALL LETTER EL', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_EL = "\u{1E05B}";

    #[Info(id: 0x1E05C, name: 'CYRILLIC SUBSCRIPT SMALL LETTER O', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_O = "\u{1E05C}";

    #[Info(id: 0x1E05D, name: 'CYRILLIC SUBSCRIPT SMALL LETTER PE', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_PE = "\u{1E05D}";

    #[Info(id: 0x1E05E, name: 'CYRILLIC SUBSCRIPT SMALL LETTER ES', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_ES = "\u{1E05E}";

    #[Info(id: 0x1E05F, name: 'CYRILLIC SUBSCRIPT SMALL LETTER U', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_U = "\u{1E05F}";

    #[Info(id: 0x1E060, name: 'CYRILLIC SUBSCRIPT SMALL LETTER EF', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_EF = "\u{1E060}";

    #[Info(id: 0x1E061, name: 'CYRILLIC SUBSCRIPT SMALL LETTER HA', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_HA = "\u{1E061}";

    #[Info(id: 0x1E062, name: 'CYRILLIC SUBSCRIPT SMALL LETTER TSE', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_TSE = "\u{1E062}";

    #[Info(id: 0x1E063, name: 'CYRILLIC SUBSCRIPT SMALL LETTER CHE', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_CHE = "\u{1E063}";

    #[Info(id: 0x1E064, name: 'CYRILLIC SUBSCRIPT SMALL LETTER SHA', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_SHA = "\u{1E064}";

    #[Info(id: 0x1E065, name: 'CYRILLIC SUBSCRIPT SMALL LETTER HARD SIGN', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_HARD_SIGN = "\u{1E065}";

    #[Info(id: 0x1E066, name: 'CYRILLIC SUBSCRIPT SMALL LETTER YERU', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_YERU = "\u{1E066}";

    #[Info(id: 0x1E067, name: 'CYRILLIC SUBSCRIPT SMALL LETTER GHE WITH UPTURN', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_GHE_WITH_UPTURN = "\u{1E067}";

    #[Info(id: 0x1E068, name: 'CYRILLIC SUBSCRIPT SMALL LETTER BYELORUSSIAN-UKRAINIAN I', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_BYELORUSSIAN_UKRAINIAN_I = "\u{1E068}";

    #[Info(id: 0x1E069, name: 'CYRILLIC SUBSCRIPT SMALL LETTER DZE', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_DZE = "\u{1E069}";

    #[Info(id: 0x1E06A, name: 'CYRILLIC SUBSCRIPT SMALL LETTER DZHE', category: Cat::Modifier_Letter)]
    case CYRILLIC_SUBSCRIPT_SMALL_LETTER_DZHE = "\u{1E06A}";

    #[Info(id: 0x1E06B, name: 'MODIFIER LETTER CYRILLIC SMALL ES WITH DESCENDER', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_ES_WITH_DESCENDER = "\u{1E06B}";

    #[Info(id: 0x1E06C, name: 'MODIFIER LETTER CYRILLIC SMALL YERU WITH BACK YER', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_YERU_WITH_BACK_YER = "\u{1E06C}";

    #[Info(id: 0x1E06D, name: 'MODIFIER LETTER CYRILLIC SMALL STRAIGHT U WITH STROKE', category: Cat::Modifier_Letter)]
    case MODIFIER_LETTER_CYRILLIC_SMALL_STRAIGHT_U_WITH_STROKE = "\u{1E06D}";

    #[Info(id: 0x1E08F, name: 'COMBINING CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I', category: Cat::Nonspacing_Mark)]
    case COMBINING_CYRILLIC_SMALL_LETTER_BYELORUSSIAN_UKRAINIAN_I = "\u{1E08F}";
}
