<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Emoticons: string
{
    #[Info(id: 128512, name: 'GRINNING FACE', category: Cat::Other_Symbol)]
    case GRINNING_FACE = "\u{1F600}";

    #[Info(id: 128513, name: 'GRINNING FACE WITH SMILING EYES', category: Cat::Other_Symbol)]
    case GRINNING_FACE_WITH_SMILING_EYES = "\u{1F601}";

    #[Info(id: 128514, name: 'FACE WITH TEARS OF JOY', category: Cat::Other_Symbol)]
    case FACE_WITH_TEARS_OF_JOY = "\u{1F602}";

    #[Info(id: 128515, name: 'SMILING FACE WITH OPEN MOUTH', category: Cat::Other_Symbol)]
    case SMILING_FACE_WITH_OPEN_MOUTH = "\u{1F603}";

    #[Info(id: 128516, name: 'SMILING FACE WITH OPEN MOUTH AND SMILING EYES', category: Cat::Other_Symbol)]
    case SMILING_FACE_WITH_OPEN_MOUTH_AND_SMILING_EYES = "\u{1F604}";

    #[Info(id: 128517, name: 'SMILING FACE WITH OPEN MOUTH AND COLD SWEAT', category: Cat::Other_Symbol)]
    case SMILING_FACE_WITH_OPEN_MOUTH_AND_COLD_SWEAT = "\u{1F605}";

    #[Info(id: 128518, name: 'SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES', category: Cat::Other_Symbol)]
    case SMILING_FACE_WITH_OPEN_MOUTH_AND_TIGHTLY_CLOSED_EYES = "\u{1F606}";

    #[Info(id: 128519, name: 'SMILING FACE WITH HALO', category: Cat::Other_Symbol)]
    case SMILING_FACE_WITH_HALO = "\u{1F607}";

    #[Info(id: 128520, name: 'SMILING FACE WITH HORNS', category: Cat::Other_Symbol)]
    case SMILING_FACE_WITH_HORNS = "\u{1F608}";

    #[Info(id: 128521, name: 'WINKING FACE', category: Cat::Other_Symbol)]
    case WINKING_FACE = "\u{1F609}";

    #[Info(id: 128522, name: 'SMILING FACE WITH SMILING EYES', category: Cat::Other_Symbol)]
    case SMILING_FACE_WITH_SMILING_EYES = "\u{1F60A}";

    #[Info(id: 128523, name: 'FACE SAVOURING DELICIOUS FOOD', category: Cat::Other_Symbol)]
    case FACE_SAVOURING_DELICIOUS_FOOD = "\u{1F60B}";

    #[Info(id: 128524, name: 'RELIEVED FACE', category: Cat::Other_Symbol)]
    case RELIEVED_FACE = "\u{1F60C}";

    #[Info(id: 128525, name: 'SMILING FACE WITH HEART-SHAPED EYES', category: Cat::Other_Symbol)]
    case SMILING_FACE_WITH_HEART_SHAPED_EYES = "\u{1F60D}";

    #[Info(id: 128526, name: 'SMILING FACE WITH SUNGLASSES', category: Cat::Other_Symbol)]
    case SMILING_FACE_WITH_SUNGLASSES = "\u{1F60E}";

    #[Info(id: 128527, name: 'SMIRKING FACE', category: Cat::Other_Symbol)]
    case SMIRKING_FACE = "\u{1F60F}";

    #[Info(id: 128528, name: 'NEUTRAL FACE', category: Cat::Other_Symbol)]
    case NEUTRAL_FACE = "\u{1F610}";

    #[Info(id: 128529, name: 'EXPRESSIONLESS FACE', category: Cat::Other_Symbol)]
    case EXPRESSIONLESS_FACE = "\u{1F611}";

    #[Info(id: 128530, name: 'UNAMUSED FACE', category: Cat::Other_Symbol)]
    case UNAMUSED_FACE = "\u{1F612}";

    #[Info(id: 128531, name: 'FACE WITH COLD SWEAT', category: Cat::Other_Symbol)]
    case FACE_WITH_COLD_SWEAT = "\u{1F613}";

    #[Info(id: 128532, name: 'PENSIVE FACE', category: Cat::Other_Symbol)]
    case PENSIVE_FACE = "\u{1F614}";

    #[Info(id: 128533, name: 'CONFUSED FACE', category: Cat::Other_Symbol)]
    case CONFUSED_FACE = "\u{1F615}";

    #[Info(id: 128534, name: 'CONFOUNDED FACE', category: Cat::Other_Symbol)]
    case CONFOUNDED_FACE = "\u{1F616}";

    #[Info(id: 128535, name: 'KISSING FACE', category: Cat::Other_Symbol)]
    case KISSING_FACE = "\u{1F617}";

    #[Info(id: 128536, name: 'FACE THROWING A KISS', category: Cat::Other_Symbol)]
    case FACE_THROWING_A_KISS = "\u{1F618}";

    #[Info(id: 128537, name: 'KISSING FACE WITH SMILING EYES', category: Cat::Other_Symbol)]
    case KISSING_FACE_WITH_SMILING_EYES = "\u{1F619}";

    #[Info(id: 128538, name: 'KISSING FACE WITH CLOSED EYES', category: Cat::Other_Symbol)]
    case KISSING_FACE_WITH_CLOSED_EYES = "\u{1F61A}";

    #[Info(id: 128539, name: 'FACE WITH STUCK-OUT TONGUE', category: Cat::Other_Symbol)]
    case FACE_WITH_STUCK_OUT_TONGUE = "\u{1F61B}";

    #[Info(id: 128540, name: 'FACE WITH STUCK-OUT TONGUE AND WINKING EYE', category: Cat::Other_Symbol)]
    case FACE_WITH_STUCK_OUT_TONGUE_AND_WINKING_EYE = "\u{1F61C}";

    #[Info(id: 128541, name: 'FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES', category: Cat::Other_Symbol)]
    case FACE_WITH_STUCK_OUT_TONGUE_AND_TIGHTLY_CLOSED_EYES = "\u{1F61D}";

    #[Info(id: 128542, name: 'DISAPPOINTED FACE', category: Cat::Other_Symbol)]
    case DISAPPOINTED_FACE = "\u{1F61E}";

    #[Info(id: 128543, name: 'WORRIED FACE', category: Cat::Other_Symbol)]
    case WORRIED_FACE = "\u{1F61F}";

    #[Info(id: 128544, name: 'ANGRY FACE', category: Cat::Other_Symbol)]
    case ANGRY_FACE = "\u{1F620}";

    #[Info(id: 128545, name: 'POUTING FACE', category: Cat::Other_Symbol)]
    case POUTING_FACE = "\u{1F621}";

    #[Info(id: 128546, name: 'CRYING FACE', category: Cat::Other_Symbol)]
    case CRYING_FACE = "\u{1F622}";

    #[Info(id: 128547, name: 'PERSEVERING FACE', category: Cat::Other_Symbol)]
    case PERSEVERING_FACE = "\u{1F623}";

    #[Info(id: 128548, name: 'FACE WITH LOOK OF TRIUMPH', category: Cat::Other_Symbol)]
    case FACE_WITH_LOOK_OF_TRIUMPH = "\u{1F624}";

    #[Info(id: 128549, name: 'DISAPPOINTED BUT RELIEVED FACE', category: Cat::Other_Symbol)]
    case DISAPPOINTED_BUT_RELIEVED_FACE = "\u{1F625}";

    #[Info(id: 128550, name: 'FROWNING FACE WITH OPEN MOUTH', category: Cat::Other_Symbol)]
    case FROWNING_FACE_WITH_OPEN_MOUTH = "\u{1F626}";

    #[Info(id: 128551, name: 'ANGUISHED FACE', category: Cat::Other_Symbol)]
    case ANGUISHED_FACE = "\u{1F627}";

    #[Info(id: 128552, name: 'FEARFUL FACE', category: Cat::Other_Symbol)]
    case FEARFUL_FACE = "\u{1F628}";

    #[Info(id: 128553, name: 'WEARY FACE', category: Cat::Other_Symbol)]
    case WEARY_FACE = "\u{1F629}";

    #[Info(id: 128554, name: 'SLEEPY FACE', category: Cat::Other_Symbol)]
    case SLEEPY_FACE = "\u{1F62A}";

    #[Info(id: 128555, name: 'TIRED FACE', category: Cat::Other_Symbol)]
    case TIRED_FACE = "\u{1F62B}";

    #[Info(id: 128556, name: 'GRIMACING FACE', category: Cat::Other_Symbol)]
    case GRIMACING_FACE = "\u{1F62C}";

    #[Info(id: 128557, name: 'LOUDLY CRYING FACE', category: Cat::Other_Symbol)]
    case LOUDLY_CRYING_FACE = "\u{1F62D}";

    #[Info(id: 128558, name: 'FACE WITH OPEN MOUTH', category: Cat::Other_Symbol)]
    case FACE_WITH_OPEN_MOUTH = "\u{1F62E}";

    #[Info(id: 128559, name: 'HUSHED FACE', category: Cat::Other_Symbol)]
    case HUSHED_FACE = "\u{1F62F}";

    #[Info(id: 128560, name: 'FACE WITH OPEN MOUTH AND COLD SWEAT', category: Cat::Other_Symbol)]
    case FACE_WITH_OPEN_MOUTH_AND_COLD_SWEAT = "\u{1F630}";

    #[Info(id: 128561, name: 'FACE SCREAMING IN FEAR', category: Cat::Other_Symbol)]
    case FACE_SCREAMING_IN_FEAR = "\u{1F631}";

    #[Info(id: 128562, name: 'ASTONISHED FACE', category: Cat::Other_Symbol)]
    case ASTONISHED_FACE = "\u{1F632}";

    #[Info(id: 128563, name: 'FLUSHED FACE', category: Cat::Other_Symbol)]
    case FLUSHED_FACE = "\u{1F633}";

    #[Info(id: 128564, name: 'SLEEPING FACE', category: Cat::Other_Symbol)]
    case SLEEPING_FACE = "\u{1F634}";

    #[Info(id: 128565, name: 'DIZZY FACE', category: Cat::Other_Symbol)]
    case DIZZY_FACE = "\u{1F635}";

    #[Info(id: 128566, name: 'FACE WITHOUT MOUTH', category: Cat::Other_Symbol)]
    case FACE_WITHOUT_MOUTH = "\u{1F636}";

    #[Info(id: 128567, name: 'FACE WITH MEDICAL MASK', category: Cat::Other_Symbol)]
    case FACE_WITH_MEDICAL_MASK = "\u{1F637}";

    #[Info(id: 128568, name: 'GRINNING CAT FACE WITH SMILING EYES', category: Cat::Other_Symbol)]
    case GRINNING_CAT_FACE_WITH_SMILING_EYES = "\u{1F638}";

    #[Info(id: 128569, name: 'CAT FACE WITH TEARS OF JOY', category: Cat::Other_Symbol)]
    case CAT_FACE_WITH_TEARS_OF_JOY = "\u{1F639}";

    #[Info(id: 128570, name: 'SMILING CAT FACE WITH OPEN MOUTH', category: Cat::Other_Symbol)]
    case SMILING_CAT_FACE_WITH_OPEN_MOUTH = "\u{1F63A}";

    #[Info(id: 128571, name: 'SMILING CAT FACE WITH HEART-SHAPED EYES', category: Cat::Other_Symbol)]
    case SMILING_CAT_FACE_WITH_HEART_SHAPED_EYES = "\u{1F63B}";

    #[Info(id: 128572, name: 'CAT FACE WITH WRY SMILE', category: Cat::Other_Symbol)]
    case CAT_FACE_WITH_WRY_SMILE = "\u{1F63C}";

    #[Info(id: 128573, name: 'KISSING CAT FACE WITH CLOSED EYES', category: Cat::Other_Symbol)]
    case KISSING_CAT_FACE_WITH_CLOSED_EYES = "\u{1F63D}";

    #[Info(id: 128574, name: 'POUTING CAT FACE', category: Cat::Other_Symbol)]
    case POUTING_CAT_FACE = "\u{1F63E}";

    #[Info(id: 128575, name: 'CRYING CAT FACE', category: Cat::Other_Symbol)]
    case CRYING_CAT_FACE = "\u{1F63F}";

    #[Info(id: 128576, name: 'WEARY CAT FACE', category: Cat::Other_Symbol)]
    case WEARY_CAT_FACE = "\u{1F640}";

    #[Info(id: 128577, name: 'SLIGHTLY FROWNING FACE', category: Cat::Other_Symbol)]
    case SLIGHTLY_FROWNING_FACE = "\u{1F641}";

    #[Info(id: 128578, name: 'SLIGHTLY SMILING FACE', category: Cat::Other_Symbol)]
    case SLIGHTLY_SMILING_FACE = "\u{1F642}";

    #[Info(id: 128579, name: 'UPSIDE-DOWN FACE', category: Cat::Other_Symbol)]
    case UPSIDE_DOWN_FACE = "\u{1F643}";

    #[Info(id: 128580, name: 'FACE WITH ROLLING EYES', category: Cat::Other_Symbol)]
    case FACE_WITH_ROLLING_EYES = "\u{1F644}";

    #[Info(id: 128581, name: 'FACE WITH NO GOOD GESTURE', category: Cat::Other_Symbol)]
    case FACE_WITH_NO_GOOD_GESTURE = "\u{1F645}";

    #[Info(id: 128582, name: 'FACE WITH OK GESTURE', category: Cat::Other_Symbol)]
    case FACE_WITH_OK_GESTURE = "\u{1F646}";

    #[Info(id: 128583, name: 'PERSON BOWING DEEPLY', category: Cat::Other_Symbol)]
    case PERSON_BOWING_DEEPLY = "\u{1F647}";

    #[Info(id: 128584, name: 'SEE-NO-EVIL MONKEY', category: Cat::Other_Symbol)]
    case SEE_NO_EVIL_MONKEY = "\u{1F648}";

    #[Info(id: 128585, name: 'HEAR-NO-EVIL MONKEY', category: Cat::Other_Symbol)]
    case HEAR_NO_EVIL_MONKEY = "\u{1F649}";

    #[Info(id: 128586, name: 'SPEAK-NO-EVIL MONKEY', category: Cat::Other_Symbol)]
    case SPEAK_NO_EVIL_MONKEY = "\u{1F64A}";

    #[Info(id: 128587, name: 'HAPPY PERSON RAISING ONE HAND', category: Cat::Other_Symbol)]
    case HAPPY_PERSON_RAISING_ONE_HAND = "\u{1F64B}";

    #[Info(id: 128588, name: 'PERSON RAISING BOTH HANDS IN CELEBRATION', category: Cat::Other_Symbol)]
    case PERSON_RAISING_BOTH_HANDS_IN_CELEBRATION = "\u{1F64C}";

    #[Info(id: 128589, name: 'PERSON FROWNING', category: Cat::Other_Symbol)]
    case PERSON_FROWNING = "\u{1F64D}";

    #[Info(id: 128590, name: 'PERSON WITH POUTING FACE', category: Cat::Other_Symbol)]
    case PERSON_WITH_POUTING_FACE = "\u{1F64E}";

    #[Info(id: 128591, name: 'PERSON WITH FOLDED HANDS', category: Cat::Other_Symbol)]
    case PERSON_WITH_FOLDED_HANDS = "\u{1F64F}";
}
