<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Indic_Siyaq_Numbers: string
{
    #[Info(id: 126065, name: 'INDIC SIYAQ NUMBER ONE', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_ONE = "\u{1EC71}";

    #[Info(id: 126066, name: 'INDIC SIYAQ NUMBER TWO', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_TWO = "\u{1EC72}";

    #[Info(id: 126067, name: 'INDIC SIYAQ NUMBER THREE', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_THREE = "\u{1EC73}";

    #[Info(id: 126068, name: 'INDIC SIYAQ NUMBER FOUR', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_FOUR = "\u{1EC74}";

    #[Info(id: 126069, name: 'INDIC SIYAQ NUMBER FIVE', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_FIVE = "\u{1EC75}";

    #[Info(id: 126070, name: 'INDIC SIYAQ NUMBER SIX', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_SIX = "\u{1EC76}";

    #[Info(id: 126071, name: 'INDIC SIYAQ NUMBER SEVEN', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_SEVEN = "\u{1EC77}";

    #[Info(id: 126072, name: 'INDIC SIYAQ NUMBER EIGHT', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_EIGHT = "\u{1EC78}";

    #[Info(id: 126073, name: 'INDIC SIYAQ NUMBER NINE', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_NINE = "\u{1EC79}";

    #[Info(id: 126074, name: 'INDIC SIYAQ NUMBER TEN', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_TEN = "\u{1EC7A}";

    #[Info(id: 126075, name: 'INDIC SIYAQ NUMBER TWENTY', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_TWENTY = "\u{1EC7B}";

    #[Info(id: 126076, name: 'INDIC SIYAQ NUMBER THIRTY', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_THIRTY = "\u{1EC7C}";

    #[Info(id: 126077, name: 'INDIC SIYAQ NUMBER FORTY', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_FORTY = "\u{1EC7D}";

    #[Info(id: 126078, name: 'INDIC SIYAQ NUMBER FIFTY', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_FIFTY = "\u{1EC7E}";

    #[Info(id: 126079, name: 'INDIC SIYAQ NUMBER SIXTY', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_SIXTY = "\u{1EC7F}";

    #[Info(id: 126080, name: 'INDIC SIYAQ NUMBER SEVENTY', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_SEVENTY = "\u{1EC80}";

    #[Info(id: 126081, name: 'INDIC SIYAQ NUMBER EIGHTY', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_EIGHTY = "\u{1EC81}";

    #[Info(id: 126082, name: 'INDIC SIYAQ NUMBER NINETY', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_NINETY = "\u{1EC82}";

    #[Info(id: 126083, name: 'INDIC SIYAQ NUMBER ONE HUNDRED', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_ONE_HUNDRED = "\u{1EC83}";

    #[Info(id: 126084, name: 'INDIC SIYAQ NUMBER TWO HUNDRED', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_TWO_HUNDRED = "\u{1EC84}";

    #[Info(id: 126085, name: 'INDIC SIYAQ NUMBER THREE HUNDRED', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_THREE_HUNDRED = "\u{1EC85}";

    #[Info(id: 126086, name: 'INDIC SIYAQ NUMBER FOUR HUNDRED', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_FOUR_HUNDRED = "\u{1EC86}";

    #[Info(id: 126087, name: 'INDIC SIYAQ NUMBER FIVE HUNDRED', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_FIVE_HUNDRED = "\u{1EC87}";

    #[Info(id: 126088, name: 'INDIC SIYAQ NUMBER SIX HUNDRED', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_SIX_HUNDRED = "\u{1EC88}";

    #[Info(id: 126089, name: 'INDIC SIYAQ NUMBER SEVEN HUNDRED', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_SEVEN_HUNDRED = "\u{1EC89}";

    #[Info(id: 126090, name: 'INDIC SIYAQ NUMBER EIGHT HUNDRED', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_EIGHT_HUNDRED = "\u{1EC8A}";

    #[Info(id: 126091, name: 'INDIC SIYAQ NUMBER NINE HUNDRED', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_NINE_HUNDRED = "\u{1EC8B}";

    #[Info(id: 126092, name: 'INDIC SIYAQ NUMBER ONE THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_ONE_THOUSAND = "\u{1EC8C}";

    #[Info(id: 126093, name: 'INDIC SIYAQ NUMBER TWO THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_TWO_THOUSAND = "\u{1EC8D}";

    #[Info(id: 126094, name: 'INDIC SIYAQ NUMBER THREE THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_THREE_THOUSAND = "\u{1EC8E}";

    #[Info(id: 126095, name: 'INDIC SIYAQ NUMBER FOUR THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_FOUR_THOUSAND = "\u{1EC8F}";

    #[Info(id: 126096, name: 'INDIC SIYAQ NUMBER FIVE THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_FIVE_THOUSAND = "\u{1EC90}";

    #[Info(id: 126097, name: 'INDIC SIYAQ NUMBER SIX THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_SIX_THOUSAND = "\u{1EC91}";

    #[Info(id: 126098, name: 'INDIC SIYAQ NUMBER SEVEN THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_SEVEN_THOUSAND = "\u{1EC92}";

    #[Info(id: 126099, name: 'INDIC SIYAQ NUMBER EIGHT THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_EIGHT_THOUSAND = "\u{1EC93}";

    #[Info(id: 126100, name: 'INDIC SIYAQ NUMBER NINE THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_NINE_THOUSAND = "\u{1EC94}";

    #[Info(id: 126101, name: 'INDIC SIYAQ NUMBER TEN THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_TEN_THOUSAND = "\u{1EC95}";

    #[Info(id: 126102, name: 'INDIC SIYAQ NUMBER TWENTY THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_TWENTY_THOUSAND = "\u{1EC96}";

    #[Info(id: 126103, name: 'INDIC SIYAQ NUMBER THIRTY THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_THIRTY_THOUSAND = "\u{1EC97}";

    #[Info(id: 126104, name: 'INDIC SIYAQ NUMBER FORTY THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_FORTY_THOUSAND = "\u{1EC98}";

    #[Info(id: 126105, name: 'INDIC SIYAQ NUMBER FIFTY THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_FIFTY_THOUSAND = "\u{1EC99}";

    #[Info(id: 126106, name: 'INDIC SIYAQ NUMBER SIXTY THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_SIXTY_THOUSAND = "\u{1EC9A}";

    #[Info(id: 126107, name: 'INDIC SIYAQ NUMBER SEVENTY THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_SEVENTY_THOUSAND = "\u{1EC9B}";

    #[Info(id: 126108, name: 'INDIC SIYAQ NUMBER EIGHTY THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_EIGHTY_THOUSAND = "\u{1EC9C}";

    #[Info(id: 126109, name: 'INDIC SIYAQ NUMBER NINETY THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_NINETY_THOUSAND = "\u{1EC9D}";

    #[Info(id: 126110, name: 'INDIC SIYAQ NUMBER LAKH', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_LAKH = "\u{1EC9E}";

    #[Info(id: 126111, name: 'INDIC SIYAQ NUMBER LAKHAN', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_LAKHAN = "\u{1EC9F}";

    #[Info(id: 126112, name: 'INDIC SIYAQ LAKH MARK', category: Cat::Other_Number)]
    case INDIC_SIYAQ_LAKH_MARK = "\u{1ECA0}";

    #[Info(id: 126113, name: 'INDIC SIYAQ NUMBER KAROR', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_KAROR = "\u{1ECA1}";

    #[Info(id: 126114, name: 'INDIC SIYAQ NUMBER KARORAN', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_KARORAN = "\u{1ECA2}";

    #[Info(id: 126115, name: 'INDIC SIYAQ NUMBER PREFIXED ONE', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_PREFIXED_ONE = "\u{1ECA3}";

    #[Info(id: 126116, name: 'INDIC SIYAQ NUMBER PREFIXED TWO', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_PREFIXED_TWO = "\u{1ECA4}";

    #[Info(id: 126117, name: 'INDIC SIYAQ NUMBER PREFIXED THREE', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_PREFIXED_THREE = "\u{1ECA5}";

    #[Info(id: 126118, name: 'INDIC SIYAQ NUMBER PREFIXED FOUR', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_PREFIXED_FOUR = "\u{1ECA6}";

    #[Info(id: 126119, name: 'INDIC SIYAQ NUMBER PREFIXED FIVE', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_PREFIXED_FIVE = "\u{1ECA7}";

    #[Info(id: 126120, name: 'INDIC SIYAQ NUMBER PREFIXED SIX', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_PREFIXED_SIX = "\u{1ECA8}";

    #[Info(id: 126121, name: 'INDIC SIYAQ NUMBER PREFIXED SEVEN', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_PREFIXED_SEVEN = "\u{1ECA9}";

    #[Info(id: 126122, name: 'INDIC SIYAQ NUMBER PREFIXED EIGHT', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_PREFIXED_EIGHT = "\u{1ECAA}";

    #[Info(id: 126123, name: 'INDIC SIYAQ NUMBER PREFIXED NINE', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_PREFIXED_NINE = "\u{1ECAB}";

    #[Info(id: 126124, name: 'INDIC SIYAQ PLACEHOLDER', category: Cat::Other_Symbol)]
    case INDIC_SIYAQ_PLACEHOLDER = "\u{1ECAC}";

    #[Info(id: 126125, name: 'INDIC SIYAQ FRACTION ONE QUARTER', category: Cat::Other_Number)]
    case INDIC_SIYAQ_FRACTION_ONE_QUARTER = "\u{1ECAD}";

    #[Info(id: 126126, name: 'INDIC SIYAQ FRACTION ONE HALF', category: Cat::Other_Number)]
    case INDIC_SIYAQ_FRACTION_ONE_HALF = "\u{1ECAE}";

    #[Info(id: 126127, name: 'INDIC SIYAQ FRACTION THREE QUARTERS', category: Cat::Other_Number)]
    case INDIC_SIYAQ_FRACTION_THREE_QUARTERS = "\u{1ECAF}";

    #[Info(id: 126128, name: 'INDIC SIYAQ RUPEE MARK', category: Cat::Currency_Symbol)]
    case INDIC_SIYAQ_RUPEE_MARK = "\u{1ECB0}";

    #[Info(id: 126129, name: 'INDIC SIYAQ NUMBER ALTERNATE ONE', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_ALTERNATE_ONE = "\u{1ECB1}";

    #[Info(id: 126130, name: 'INDIC SIYAQ NUMBER ALTERNATE TWO', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_ALTERNATE_TWO = "\u{1ECB2}";

    #[Info(id: 126131, name: 'INDIC SIYAQ NUMBER ALTERNATE TEN THOUSAND', category: Cat::Other_Number)]
    case INDIC_SIYAQ_NUMBER_ALTERNATE_TEN_THOUSAND = "\u{1ECB3}";

    #[Info(id: 126132, name: 'INDIC SIYAQ ALTERNATE LAKH MARK', category: Cat::Other_Number)]
    case INDIC_SIYAQ_ALTERNATE_LAKH_MARK = "\u{1ECB4}";
}
