<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Kangxi_Radicals: string
{
    #[Info(id: 12032, name: 'KANGXI RADICAL ONE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_ONE = "\u{2F00}";

    #[Info(id: 12033, name: 'KANGXI RADICAL LINE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_LINE = "\u{2F01}";

    #[Info(id: 12034, name: 'KANGXI RADICAL DOT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DOT = "\u{2F02}";

    #[Info(id: 12035, name: 'KANGXI RADICAL SLASH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SLASH = "\u{2F03}";

    #[Info(id: 12036, name: 'KANGXI RADICAL SECOND', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SECOND = "\u{2F04}";

    #[Info(id: 12037, name: 'KANGXI RADICAL HOOK', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_HOOK = "\u{2F05}";

    #[Info(id: 12038, name: 'KANGXI RADICAL TWO', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TWO = "\u{2F06}";

    #[Info(id: 12039, name: 'KANGXI RADICAL LID', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_LID = "\u{2F07}";

    #[Info(id: 12040, name: 'KANGXI RADICAL MAN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_MAN = "\u{2F08}";

    #[Info(id: 12041, name: 'KANGXI RADICAL LEGS', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_LEGS = "\u{2F09}";

    #[Info(id: 12042, name: 'KANGXI RADICAL ENTER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_ENTER = "\u{2F0A}";

    #[Info(id: 12043, name: 'KANGXI RADICAL EIGHT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_EIGHT = "\u{2F0B}";

    #[Info(id: 12044, name: 'KANGXI RADICAL DOWN BOX', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DOWN_BOX = "\u{2F0C}";

    #[Info(id: 12045, name: 'KANGXI RADICAL COVER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_COVER = "\u{2F0D}";

    #[Info(id: 12046, name: 'KANGXI RADICAL ICE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_ICE = "\u{2F0E}";

    #[Info(id: 12047, name: 'KANGXI RADICAL TABLE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TABLE = "\u{2F0F}";

    #[Info(id: 12048, name: 'KANGXI RADICAL OPEN BOX', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_OPEN_BOX = "\u{2F10}";

    #[Info(id: 12049, name: 'KANGXI RADICAL KNIFE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_KNIFE = "\u{2F11}";

    #[Info(id: 12050, name: 'KANGXI RADICAL POWER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_POWER = "\u{2F12}";

    #[Info(id: 12051, name: 'KANGXI RADICAL WRAP', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WRAP = "\u{2F13}";

    #[Info(id: 12052, name: 'KANGXI RADICAL SPOON', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SPOON = "\u{2F14}";

    #[Info(id: 12053, name: 'KANGXI RADICAL RIGHT OPEN BOX', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_RIGHT_OPEN_BOX = "\u{2F15}";

    #[Info(id: 12054, name: 'KANGXI RADICAL HIDING ENCLOSURE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_HIDING_ENCLOSURE = "\u{2F16}";

    #[Info(id: 12055, name: 'KANGXI RADICAL TEN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TEN = "\u{2F17}";

    #[Info(id: 12056, name: 'KANGXI RADICAL DIVINATION', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DIVINATION = "\u{2F18}";

    #[Info(id: 12057, name: 'KANGXI RADICAL SEAL', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SEAL = "\u{2F19}";

    #[Info(id: 12058, name: 'KANGXI RADICAL CLIFF', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_CLIFF = "\u{2F1A}";

    #[Info(id: 12059, name: 'KANGXI RADICAL PRIVATE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_PRIVATE = "\u{2F1B}";

    #[Info(id: 12060, name: 'KANGXI RADICAL AGAIN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_AGAIN = "\u{2F1C}";

    #[Info(id: 12061, name: 'KANGXI RADICAL MOUTH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_MOUTH = "\u{2F1D}";

    #[Info(id: 12062, name: 'KANGXI RADICAL ENCLOSURE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_ENCLOSURE = "\u{2F1E}";

    #[Info(id: 12063, name: 'KANGXI RADICAL EARTH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_EARTH = "\u{2F1F}";

    #[Info(id: 12064, name: 'KANGXI RADICAL SCHOLAR', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SCHOLAR = "\u{2F20}";

    #[Info(id: 12065, name: 'KANGXI RADICAL GO', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_GO = "\u{2F21}";

    #[Info(id: 12066, name: 'KANGXI RADICAL GO SLOWLY', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_GO_SLOWLY = "\u{2F22}";

    #[Info(id: 12067, name: 'KANGXI RADICAL EVENING', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_EVENING = "\u{2F23}";

    #[Info(id: 12068, name: 'KANGXI RADICAL BIG', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BIG = "\u{2F24}";

    #[Info(id: 12069, name: 'KANGXI RADICAL WOMAN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WOMAN = "\u{2F25}";

    #[Info(id: 12070, name: 'KANGXI RADICAL CHILD', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_CHILD = "\u{2F26}";

    #[Info(id: 12071, name: 'KANGXI RADICAL ROOF', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_ROOF = "\u{2F27}";

    #[Info(id: 12072, name: 'KANGXI RADICAL INCH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_INCH = "\u{2F28}";

    #[Info(id: 12073, name: 'KANGXI RADICAL SMALL', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SMALL = "\u{2F29}";

    #[Info(id: 12074, name: 'KANGXI RADICAL LAME', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_LAME = "\u{2F2A}";

    #[Info(id: 12075, name: 'KANGXI RADICAL CORPSE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_CORPSE = "\u{2F2B}";

    #[Info(id: 12076, name: 'KANGXI RADICAL SPROUT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SPROUT = "\u{2F2C}";

    #[Info(id: 12077, name: 'KANGXI RADICAL MOUNTAIN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_MOUNTAIN = "\u{2F2D}";

    #[Info(id: 12078, name: 'KANGXI RADICAL RIVER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_RIVER = "\u{2F2E}";

    #[Info(id: 12079, name: 'KANGXI RADICAL WORK', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WORK = "\u{2F2F}";

    #[Info(id: 12080, name: 'KANGXI RADICAL ONESELF', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_ONESELF = "\u{2F30}";

    #[Info(id: 12081, name: 'KANGXI RADICAL TURBAN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TURBAN = "\u{2F31}";

    #[Info(id: 12082, name: 'KANGXI RADICAL DRY', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DRY = "\u{2F32}";

    #[Info(id: 12083, name: 'KANGXI RADICAL SHORT THREAD', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SHORT_THREAD = "\u{2F33}";

    #[Info(id: 12084, name: 'KANGXI RADICAL DOTTED CLIFF', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DOTTED_CLIFF = "\u{2F34}";

    #[Info(id: 12085, name: 'KANGXI RADICAL LONG STRIDE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_LONG_STRIDE = "\u{2F35}";

    #[Info(id: 12086, name: 'KANGXI RADICAL TWO HANDS', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TWO_HANDS = "\u{2F36}";

    #[Info(id: 12087, name: 'KANGXI RADICAL SHOOT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SHOOT = "\u{2F37}";

    #[Info(id: 12088, name: 'KANGXI RADICAL BOW', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BOW = "\u{2F38}";

    #[Info(id: 12089, name: 'KANGXI RADICAL SNOUT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SNOUT = "\u{2F39}";

    #[Info(id: 12090, name: 'KANGXI RADICAL BRISTLE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BRISTLE = "\u{2F3A}";

    #[Info(id: 12091, name: 'KANGXI RADICAL STEP', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_STEP = "\u{2F3B}";

    #[Info(id: 12092, name: 'KANGXI RADICAL HEART', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_HEART = "\u{2F3C}";

    #[Info(id: 12093, name: 'KANGXI RADICAL HALBERD', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_HALBERD = "\u{2F3D}";

    #[Info(id: 12094, name: 'KANGXI RADICAL DOOR', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DOOR = "\u{2F3E}";

    #[Info(id: 12095, name: 'KANGXI RADICAL HAND', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_HAND = "\u{2F3F}";

    #[Info(id: 12096, name: 'KANGXI RADICAL BRANCH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BRANCH = "\u{2F40}";

    #[Info(id: 12097, name: 'KANGXI RADICAL RAP', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_RAP = "\u{2F41}";

    #[Info(id: 12098, name: 'KANGXI RADICAL SCRIPT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SCRIPT = "\u{2F42}";

    #[Info(id: 12099, name: 'KANGXI RADICAL DIPPER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DIPPER = "\u{2F43}";

    #[Info(id: 12100, name: 'KANGXI RADICAL AXE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_AXE = "\u{2F44}";

    #[Info(id: 12101, name: 'KANGXI RADICAL SQUARE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SQUARE = "\u{2F45}";

    #[Info(id: 12102, name: 'KANGXI RADICAL NOT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_NOT = "\u{2F46}";

    #[Info(id: 12103, name: 'KANGXI RADICAL SUN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SUN = "\u{2F47}";

    #[Info(id: 12104, name: 'KANGXI RADICAL SAY', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SAY = "\u{2F48}";

    #[Info(id: 12105, name: 'KANGXI RADICAL MOON', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_MOON = "\u{2F49}";

    #[Info(id: 12106, name: 'KANGXI RADICAL TREE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TREE = "\u{2F4A}";

    #[Info(id: 12107, name: 'KANGXI RADICAL LACK', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_LACK = "\u{2F4B}";

    #[Info(id: 12108, name: 'KANGXI RADICAL STOP', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_STOP = "\u{2F4C}";

    #[Info(id: 12109, name: 'KANGXI RADICAL DEATH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DEATH = "\u{2F4D}";

    #[Info(id: 12110, name: 'KANGXI RADICAL WEAPON', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WEAPON = "\u{2F4E}";

    #[Info(id: 12111, name: 'KANGXI RADICAL DO NOT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DO_NOT = "\u{2F4F}";

    #[Info(id: 12112, name: 'KANGXI RADICAL COMPARE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_COMPARE = "\u{2F50}";

    #[Info(id: 12113, name: 'KANGXI RADICAL FUR', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FUR = "\u{2F51}";

    #[Info(id: 12114, name: 'KANGXI RADICAL CLAN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_CLAN = "\u{2F52}";

    #[Info(id: 12115, name: 'KANGXI RADICAL STEAM', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_STEAM = "\u{2F53}";

    #[Info(id: 12116, name: 'KANGXI RADICAL WATER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WATER = "\u{2F54}";

    #[Info(id: 12117, name: 'KANGXI RADICAL FIRE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FIRE = "\u{2F55}";

    #[Info(id: 12118, name: 'KANGXI RADICAL CLAW', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_CLAW = "\u{2F56}";

    #[Info(id: 12119, name: 'KANGXI RADICAL FATHER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FATHER = "\u{2F57}";

    #[Info(id: 12120, name: 'KANGXI RADICAL DOUBLE X', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DOUBLE_X = "\u{2F58}";

    #[Info(id: 12121, name: 'KANGXI RADICAL HALF TREE TRUNK', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_HALF_TREE_TRUNK = "\u{2F59}";

    #[Info(id: 12122, name: 'KANGXI RADICAL SLICE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SLICE = "\u{2F5A}";

    #[Info(id: 12123, name: 'KANGXI RADICAL FANG', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FANG = "\u{2F5B}";

    #[Info(id: 12124, name: 'KANGXI RADICAL COW', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_COW = "\u{2F5C}";

    #[Info(id: 12125, name: 'KANGXI RADICAL DOG', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DOG = "\u{2F5D}";

    #[Info(id: 12126, name: 'KANGXI RADICAL PROFOUND', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_PROFOUND = "\u{2F5E}";

    #[Info(id: 12127, name: 'KANGXI RADICAL JADE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_JADE = "\u{2F5F}";

    #[Info(id: 12128, name: 'KANGXI RADICAL MELON', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_MELON = "\u{2F60}";

    #[Info(id: 12129, name: 'KANGXI RADICAL TILE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TILE = "\u{2F61}";

    #[Info(id: 12130, name: 'KANGXI RADICAL SWEET', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SWEET = "\u{2F62}";

    #[Info(id: 12131, name: 'KANGXI RADICAL LIFE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_LIFE = "\u{2F63}";

    #[Info(id: 12132, name: 'KANGXI RADICAL USE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_USE = "\u{2F64}";

    #[Info(id: 12133, name: 'KANGXI RADICAL FIELD', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FIELD = "\u{2F65}";

    #[Info(id: 12134, name: 'KANGXI RADICAL BOLT OF CLOTH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BOLT_OF_CLOTH = "\u{2F66}";

    #[Info(id: 12135, name: 'KANGXI RADICAL SICKNESS', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SICKNESS = "\u{2F67}";

    #[Info(id: 12136, name: 'KANGXI RADICAL DOTTED TENT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DOTTED_TENT = "\u{2F68}";

    #[Info(id: 12137, name: 'KANGXI RADICAL WHITE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WHITE = "\u{2F69}";

    #[Info(id: 12138, name: 'KANGXI RADICAL SKIN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SKIN = "\u{2F6A}";

    #[Info(id: 12139, name: 'KANGXI RADICAL DISH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DISH = "\u{2F6B}";

    #[Info(id: 12140, name: 'KANGXI RADICAL EYE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_EYE = "\u{2F6C}";

    #[Info(id: 12141, name: 'KANGXI RADICAL SPEAR', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SPEAR = "\u{2F6D}";

    #[Info(id: 12142, name: 'KANGXI RADICAL ARROW', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_ARROW = "\u{2F6E}";

    #[Info(id: 12143, name: 'KANGXI RADICAL STONE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_STONE = "\u{2F6F}";

    #[Info(id: 12144, name: 'KANGXI RADICAL SPIRIT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SPIRIT = "\u{2F70}";

    #[Info(id: 12145, name: 'KANGXI RADICAL TRACK', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TRACK = "\u{2F71}";

    #[Info(id: 12146, name: 'KANGXI RADICAL GRAIN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_GRAIN = "\u{2F72}";

    #[Info(id: 12147, name: 'KANGXI RADICAL CAVE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_CAVE = "\u{2F73}";

    #[Info(id: 12148, name: 'KANGXI RADICAL STAND', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_STAND = "\u{2F74}";

    #[Info(id: 12149, name: 'KANGXI RADICAL BAMBOO', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BAMBOO = "\u{2F75}";

    #[Info(id: 12150, name: 'KANGXI RADICAL RICE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_RICE = "\u{2F76}";

    #[Info(id: 12151, name: 'KANGXI RADICAL SILK', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SILK = "\u{2F77}";

    #[Info(id: 12152, name: 'KANGXI RADICAL JAR', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_JAR = "\u{2F78}";

    #[Info(id: 12153, name: 'KANGXI RADICAL NET', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_NET = "\u{2F79}";

    #[Info(id: 12154, name: 'KANGXI RADICAL SHEEP', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SHEEP = "\u{2F7A}";

    #[Info(id: 12155, name: 'KANGXI RADICAL FEATHER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FEATHER = "\u{2F7B}";

    #[Info(id: 12156, name: 'KANGXI RADICAL OLD', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_OLD = "\u{2F7C}";

    #[Info(id: 12157, name: 'KANGXI RADICAL AND', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_AND = "\u{2F7D}";

    #[Info(id: 12158, name: 'KANGXI RADICAL PLOW', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_PLOW = "\u{2F7E}";

    #[Info(id: 12159, name: 'KANGXI RADICAL EAR', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_EAR = "\u{2F7F}";

    #[Info(id: 12160, name: 'KANGXI RADICAL BRUSH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BRUSH = "\u{2F80}";

    #[Info(id: 12161, name: 'KANGXI RADICAL MEAT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_MEAT = "\u{2F81}";

    #[Info(id: 12162, name: 'KANGXI RADICAL MINISTER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_MINISTER = "\u{2F82}";

    #[Info(id: 12163, name: 'KANGXI RADICAL SELF', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SELF = "\u{2F83}";

    #[Info(id: 12164, name: 'KANGXI RADICAL ARRIVE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_ARRIVE = "\u{2F84}";

    #[Info(id: 12165, name: 'KANGXI RADICAL MORTAR', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_MORTAR = "\u{2F85}";

    #[Info(id: 12166, name: 'KANGXI RADICAL TONGUE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TONGUE = "\u{2F86}";

    #[Info(id: 12167, name: 'KANGXI RADICAL OPPOSE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_OPPOSE = "\u{2F87}";

    #[Info(id: 12168, name: 'KANGXI RADICAL BOAT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BOAT = "\u{2F88}";

    #[Info(id: 12169, name: 'KANGXI RADICAL STOPPING', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_STOPPING = "\u{2F89}";

    #[Info(id: 12170, name: 'KANGXI RADICAL COLOR', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_COLOR = "\u{2F8A}";

    #[Info(id: 12171, name: 'KANGXI RADICAL GRASS', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_GRASS = "\u{2F8B}";

    #[Info(id: 12172, name: 'KANGXI RADICAL TIGER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TIGER = "\u{2F8C}";

    #[Info(id: 12173, name: 'KANGXI RADICAL INSECT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_INSECT = "\u{2F8D}";

    #[Info(id: 12174, name: 'KANGXI RADICAL BLOOD', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BLOOD = "\u{2F8E}";

    #[Info(id: 12175, name: 'KANGXI RADICAL WALK ENCLOSURE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WALK_ENCLOSURE = "\u{2F8F}";

    #[Info(id: 12176, name: 'KANGXI RADICAL CLOTHES', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_CLOTHES = "\u{2F90}";

    #[Info(id: 12177, name: 'KANGXI RADICAL WEST', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WEST = "\u{2F91}";

    #[Info(id: 12178, name: 'KANGXI RADICAL SEE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SEE = "\u{2F92}";

    #[Info(id: 12179, name: 'KANGXI RADICAL HORN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_HORN = "\u{2F93}";

    #[Info(id: 12180, name: 'KANGXI RADICAL SPEECH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SPEECH = "\u{2F94}";

    #[Info(id: 12181, name: 'KANGXI RADICAL VALLEY', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_VALLEY = "\u{2F95}";

    #[Info(id: 12182, name: 'KANGXI RADICAL BEAN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BEAN = "\u{2F96}";

    #[Info(id: 12183, name: 'KANGXI RADICAL PIG', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_PIG = "\u{2F97}";

    #[Info(id: 12184, name: 'KANGXI RADICAL BADGER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BADGER = "\u{2F98}";

    #[Info(id: 12185, name: 'KANGXI RADICAL SHELL', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SHELL = "\u{2F99}";

    #[Info(id: 12186, name: 'KANGXI RADICAL RED', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_RED = "\u{2F9A}";

    #[Info(id: 12187, name: 'KANGXI RADICAL RUN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_RUN = "\u{2F9B}";

    #[Info(id: 12188, name: 'KANGXI RADICAL FOOT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FOOT = "\u{2F9C}";

    #[Info(id: 12189, name: 'KANGXI RADICAL BODY', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BODY = "\u{2F9D}";

    #[Info(id: 12190, name: 'KANGXI RADICAL CART', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_CART = "\u{2F9E}";

    #[Info(id: 12191, name: 'KANGXI RADICAL BITTER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BITTER = "\u{2F9F}";

    #[Info(id: 12192, name: 'KANGXI RADICAL MORNING', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_MORNING = "\u{2FA0}";

    #[Info(id: 12193, name: 'KANGXI RADICAL WALK', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WALK = "\u{2FA1}";

    #[Info(id: 12194, name: 'KANGXI RADICAL CITY', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_CITY = "\u{2FA2}";

    #[Info(id: 12195, name: 'KANGXI RADICAL WINE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WINE = "\u{2FA3}";

    #[Info(id: 12196, name: 'KANGXI RADICAL DISTINGUISH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DISTINGUISH = "\u{2FA4}";

    #[Info(id: 12197, name: 'KANGXI RADICAL VILLAGE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_VILLAGE = "\u{2FA5}";

    #[Info(id: 12198, name: 'KANGXI RADICAL GOLD', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_GOLD = "\u{2FA6}";

    #[Info(id: 12199, name: 'KANGXI RADICAL LONG', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_LONG = "\u{2FA7}";

    #[Info(id: 12200, name: 'KANGXI RADICAL GATE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_GATE = "\u{2FA8}";

    #[Info(id: 12201, name: 'KANGXI RADICAL MOUND', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_MOUND = "\u{2FA9}";

    #[Info(id: 12202, name: 'KANGXI RADICAL SLAVE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SLAVE = "\u{2FAA}";

    #[Info(id: 12203, name: 'KANGXI RADICAL SHORT TAILED BIRD', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SHORT_TAILED_BIRD = "\u{2FAB}";

    #[Info(id: 12204, name: 'KANGXI RADICAL RAIN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_RAIN = "\u{2FAC}";

    #[Info(id: 12205, name: 'KANGXI RADICAL BLUE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BLUE = "\u{2FAD}";

    #[Info(id: 12206, name: 'KANGXI RADICAL WRONG', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WRONG = "\u{2FAE}";

    #[Info(id: 12207, name: 'KANGXI RADICAL FACE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FACE = "\u{2FAF}";

    #[Info(id: 12208, name: 'KANGXI RADICAL LEATHER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_LEATHER = "\u{2FB0}";

    #[Info(id: 12209, name: 'KANGXI RADICAL TANNED LEATHER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TANNED_LEATHER = "\u{2FB1}";

    #[Info(id: 12210, name: 'KANGXI RADICAL LEEK', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_LEEK = "\u{2FB2}";

    #[Info(id: 12211, name: 'KANGXI RADICAL SOUND', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SOUND = "\u{2FB3}";

    #[Info(id: 12212, name: 'KANGXI RADICAL LEAF', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_LEAF = "\u{2FB4}";

    #[Info(id: 12213, name: 'KANGXI RADICAL WIND', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WIND = "\u{2FB5}";

    #[Info(id: 12214, name: 'KANGXI RADICAL FLY', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FLY = "\u{2FB6}";

    #[Info(id: 12215, name: 'KANGXI RADICAL EAT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_EAT = "\u{2FB7}";

    #[Info(id: 12216, name: 'KANGXI RADICAL HEAD', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_HEAD = "\u{2FB8}";

    #[Info(id: 12217, name: 'KANGXI RADICAL FRAGRANT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FRAGRANT = "\u{2FB9}";

    #[Info(id: 12218, name: 'KANGXI RADICAL HORSE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_HORSE = "\u{2FBA}";

    #[Info(id: 12219, name: 'KANGXI RADICAL BONE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BONE = "\u{2FBB}";

    #[Info(id: 12220, name: 'KANGXI RADICAL TALL', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TALL = "\u{2FBC}";

    #[Info(id: 12221, name: 'KANGXI RADICAL HAIR', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_HAIR = "\u{2FBD}";

    #[Info(id: 12222, name: 'KANGXI RADICAL FIGHT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FIGHT = "\u{2FBE}";

    #[Info(id: 12223, name: 'KANGXI RADICAL SACRIFICIAL WINE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SACRIFICIAL_WINE = "\u{2FBF}";

    #[Info(id: 12224, name: 'KANGXI RADICAL CAULDRON', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_CAULDRON = "\u{2FC0}";

    #[Info(id: 12225, name: 'KANGXI RADICAL GHOST', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_GHOST = "\u{2FC1}";

    #[Info(id: 12226, name: 'KANGXI RADICAL FISH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FISH = "\u{2FC2}";

    #[Info(id: 12227, name: 'KANGXI RADICAL BIRD', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BIRD = "\u{2FC3}";

    #[Info(id: 12228, name: 'KANGXI RADICAL SALT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_SALT = "\u{2FC4}";

    #[Info(id: 12229, name: 'KANGXI RADICAL DEER', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DEER = "\u{2FC5}";

    #[Info(id: 12230, name: 'KANGXI RADICAL WHEAT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_WHEAT = "\u{2FC6}";

    #[Info(id: 12231, name: 'KANGXI RADICAL HEMP', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_HEMP = "\u{2FC7}";

    #[Info(id: 12232, name: 'KANGXI RADICAL YELLOW', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_YELLOW = "\u{2FC8}";

    #[Info(id: 12233, name: 'KANGXI RADICAL MILLET', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_MILLET = "\u{2FC9}";

    #[Info(id: 12234, name: 'KANGXI RADICAL BLACK', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_BLACK = "\u{2FCA}";

    #[Info(id: 12235, name: 'KANGXI RADICAL EMBROIDERY', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_EMBROIDERY = "\u{2FCB}";

    #[Info(id: 12236, name: 'KANGXI RADICAL FROG', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FROG = "\u{2FCC}";

    #[Info(id: 12237, name: 'KANGXI RADICAL TRIPOD', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TRIPOD = "\u{2FCD}";

    #[Info(id: 12238, name: 'KANGXI RADICAL DRUM', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DRUM = "\u{2FCE}";

    #[Info(id: 12239, name: 'KANGXI RADICAL RAT', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_RAT = "\u{2FCF}";

    #[Info(id: 12240, name: 'KANGXI RADICAL NOSE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_NOSE = "\u{2FD0}";

    #[Info(id: 12241, name: 'KANGXI RADICAL EVEN', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_EVEN = "\u{2FD1}";

    #[Info(id: 12242, name: 'KANGXI RADICAL TOOTH', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TOOTH = "\u{2FD2}";

    #[Info(id: 12243, name: 'KANGXI RADICAL DRAGON', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_DRAGON = "\u{2FD3}";

    #[Info(id: 12244, name: 'KANGXI RADICAL TURTLE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_TURTLE = "\u{2FD4}";

    #[Info(id: 12245, name: 'KANGXI RADICAL FLUTE', category: Cat::Other_Symbol)]
    case KANGXI_RADICAL_FLUTE = "\u{2FD5}";
}
