<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Lao: string
{
    #[Info(id: 3713, name: 'LAO LETTER KO', category: Cat::Other_Letter)]
    case LAO_LETTER_KO = "\u{E81}";

    #[Info(id: 3714, name: 'LAO LETTER KHO SUNG', category: Cat::Other_Letter)]
    case LAO_LETTER_KHO_SUNG = "\u{E82}";

    #[Info(id: 3716, name: 'LAO LETTER KHO TAM', category: Cat::Other_Letter)]
    case LAO_LETTER_KHO_TAM = "\u{E84}";

    #[Info(id: 3718, name: 'LAO LETTER PALI GHA', category: Cat::Other_Letter)]
    case LAO_LETTER_PALI_GHA = "\u{E86}";

    #[Info(id: 3719, name: 'LAO LETTER NGO', category: Cat::Other_Letter)]
    case LAO_LETTER_NGO = "\u{E87}";

    #[Info(id: 3720, name: 'LAO LETTER CO', category: Cat::Other_Letter)]
    case LAO_LETTER_CO = "\u{E88}";

    #[Info(id: 3721, name: 'LAO LETTER PALI CHA', category: Cat::Other_Letter)]
    case LAO_LETTER_PALI_CHA = "\u{E89}";

    #[Info(id: 3722, name: 'LAO LETTER SO TAM', category: Cat::Other_Letter)]
    case LAO_LETTER_SO_TAM = "\u{E8A}";

    #[Info(id: 3724, name: 'LAO LETTER PALI JHA', category: Cat::Other_Letter)]
    case LAO_LETTER_PALI_JHA = "\u{E8C}";

    #[Info(id: 3725, name: 'LAO LETTER NYO', category: Cat::Other_Letter)]
    case LAO_LETTER_NYO = "\u{E8D}";

    #[Info(id: 3726, name: 'LAO LETTER PALI NYA', category: Cat::Other_Letter)]
    case LAO_LETTER_PALI_NYA = "\u{E8E}";

    #[Info(id: 3727, name: 'LAO LETTER PALI TTA', category: Cat::Other_Letter)]
    case LAO_LETTER_PALI_TTA = "\u{E8F}";

    #[Info(id: 3728, name: 'LAO LETTER PALI TTHA', category: Cat::Other_Letter)]
    case LAO_LETTER_PALI_TTHA = "\u{E90}";

    #[Info(id: 3729, name: 'LAO LETTER PALI DDA', category: Cat::Other_Letter)]
    case LAO_LETTER_PALI_DDA = "\u{E91}";

    #[Info(id: 3730, name: 'LAO LETTER PALI DDHA', category: Cat::Other_Letter)]
    case LAO_LETTER_PALI_DDHA = "\u{E92}";

    #[Info(id: 3731, name: 'LAO LETTER PALI NNA', category: Cat::Other_Letter)]
    case LAO_LETTER_PALI_NNA = "\u{E93}";

    #[Info(id: 3732, name: 'LAO LETTER DO', category: Cat::Other_Letter)]
    case LAO_LETTER_DO = "\u{E94}";

    #[Info(id: 3733, name: 'LAO LETTER TO', category: Cat::Other_Letter)]
    case LAO_LETTER_TO = "\u{E95}";

    #[Info(id: 3734, name: 'LAO LETTER THO SUNG', category: Cat::Other_Letter)]
    case LAO_LETTER_THO_SUNG = "\u{E96}";

    #[Info(id: 3735, name: 'LAO LETTER THO TAM', category: Cat::Other_Letter)]
    case LAO_LETTER_THO_TAM = "\u{E97}";

    #[Info(id: 3736, name: 'LAO LETTER PALI DHA', category: Cat::Other_Letter)]
    case LAO_LETTER_PALI_DHA = "\u{E98}";

    #[Info(id: 3737, name: 'LAO LETTER NO', category: Cat::Other_Letter)]
    case LAO_LETTER_NO = "\u{E99}";

    #[Info(id: 3738, name: 'LAO LETTER BO', category: Cat::Other_Letter)]
    case LAO_LETTER_BO = "\u{E9A}";

    #[Info(id: 3739, name: 'LAO LETTER PO', category: Cat::Other_Letter)]
    case LAO_LETTER_PO = "\u{E9B}";

    #[Info(id: 3740, name: 'LAO LETTER PHO SUNG', category: Cat::Other_Letter)]
    case LAO_LETTER_PHO_SUNG = "\u{E9C}";

    #[Info(id: 3741, name: 'LAO LETTER FO TAM', category: Cat::Other_Letter)]
    case LAO_LETTER_FO_TAM = "\u{E9D}";

    #[Info(id: 3742, name: 'LAO LETTER PHO TAM', category: Cat::Other_Letter)]
    case LAO_LETTER_PHO_TAM = "\u{E9E}";

    #[Info(id: 3743, name: 'LAO LETTER FO SUNG', category: Cat::Other_Letter)]
    case LAO_LETTER_FO_SUNG = "\u{E9F}";

    #[Info(id: 3744, name: 'LAO LETTER PALI BHA', category: Cat::Other_Letter)]
    case LAO_LETTER_PALI_BHA = "\u{EA0}";

    #[Info(id: 3745, name: 'LAO LETTER MO', category: Cat::Other_Letter)]
    case LAO_LETTER_MO = "\u{EA1}";

    #[Info(id: 3746, name: 'LAO LETTER YO', category: Cat::Other_Letter)]
    case LAO_LETTER_YO = "\u{EA2}";

    #[Info(id: 3747, name: 'LAO LETTER LO LING', category: Cat::Other_Letter)]
    case LAO_LETTER_LO_LING = "\u{EA3}";

    #[Info(id: 3749, name: 'LAO LETTER LO LOOT', category: Cat::Other_Letter)]
    case LAO_LETTER_LO_LOOT = "\u{EA5}";

    #[Info(id: 3751, name: 'LAO LETTER WO', category: Cat::Other_Letter)]
    case LAO_LETTER_WO = "\u{EA7}";

    #[Info(id: 3752, name: 'LAO LETTER SANSKRIT SHA', category: Cat::Other_Letter)]
    case LAO_LETTER_SANSKRIT_SHA = "\u{EA8}";

    #[Info(id: 3753, name: 'LAO LETTER SANSKRIT SSA', category: Cat::Other_Letter)]
    case LAO_LETTER_SANSKRIT_SSA = "\u{EA9}";

    #[Info(id: 3754, name: 'LAO LETTER SO SUNG', category: Cat::Other_Letter)]
    case LAO_LETTER_SO_SUNG = "\u{EAA}";

    #[Info(id: 3755, name: 'LAO LETTER HO SUNG', category: Cat::Other_Letter)]
    case LAO_LETTER_HO_SUNG = "\u{EAB}";

    #[Info(id: 3756, name: 'LAO LETTER PALI LLA', category: Cat::Other_Letter)]
    case LAO_LETTER_PALI_LLA = "\u{EAC}";

    #[Info(id: 3757, name: 'LAO LETTER O', category: Cat::Other_Letter)]
    case LAO_LETTER_O = "\u{EAD}";

    #[Info(id: 3758, name: 'LAO LETTER HO TAM', category: Cat::Other_Letter)]
    case LAO_LETTER_HO_TAM = "\u{EAE}";

    #[Info(id: 3759, name: 'LAO ELLIPSIS', category: Cat::Other_Letter)]
    case LAO_ELLIPSIS = "\u{EAF}";

    #[Info(id: 3760, name: 'LAO VOWEL SIGN A', category: Cat::Other_Letter)]
    case LAO_VOWEL_SIGN_A = "\u{EB0}";

    #[Info(id: 3761, name: 'LAO VOWEL SIGN MAI KAN', category: Cat::Nonspacing_Mark)]
    case LAO_VOWEL_SIGN_MAI_KAN = "\u{EB1}";

    #[Info(id: 3762, name: 'LAO VOWEL SIGN AA', category: Cat::Other_Letter)]
    case LAO_VOWEL_SIGN_AA = "\u{EB2}";

    #[Info(id: 3763, name: 'LAO VOWEL SIGN AM', category: Cat::Other_Letter)]
    case LAO_VOWEL_SIGN_AM = "\u{EB3}";

    #[Info(id: 3764, name: 'LAO VOWEL SIGN I', category: Cat::Nonspacing_Mark)]
    case LAO_VOWEL_SIGN_I = "\u{EB4}";

    #[Info(id: 3765, name: 'LAO VOWEL SIGN II', category: Cat::Nonspacing_Mark)]
    case LAO_VOWEL_SIGN_II = "\u{EB5}";

    #[Info(id: 3766, name: 'LAO VOWEL SIGN Y', category: Cat::Nonspacing_Mark)]
    case LAO_VOWEL_SIGN_Y = "\u{EB6}";

    #[Info(id: 3767, name: 'LAO VOWEL SIGN YY', category: Cat::Nonspacing_Mark)]
    case LAO_VOWEL_SIGN_YY = "\u{EB7}";

    #[Info(id: 3768, name: 'LAO VOWEL SIGN U', category: Cat::Nonspacing_Mark)]
    case LAO_VOWEL_SIGN_U = "\u{EB8}";

    #[Info(id: 3769, name: 'LAO VOWEL SIGN UU', category: Cat::Nonspacing_Mark)]
    case LAO_VOWEL_SIGN_UU = "\u{EB9}";

    #[Info(id: 3770, name: 'LAO SIGN PALI VIRAMA', category: Cat::Nonspacing_Mark)]
    case LAO_SIGN_PALI_VIRAMA = "\u{EBA}";

    #[Info(id: 3771, name: 'LAO VOWEL SIGN MAI KON', category: Cat::Nonspacing_Mark)]
    case LAO_VOWEL_SIGN_MAI_KON = "\u{EBB}";

    #[Info(id: 3772, name: 'LAO SEMIVOWEL SIGN LO', category: Cat::Nonspacing_Mark)]
    case LAO_SEMIVOWEL_SIGN_LO = "\u{EBC}";

    #[Info(id: 3773, name: 'LAO SEMIVOWEL SIGN NYO', category: Cat::Other_Letter)]
    case LAO_SEMIVOWEL_SIGN_NYO = "\u{EBD}";

    #[Info(id: 3776, name: 'LAO VOWEL SIGN E', category: Cat::Other_Letter)]
    case LAO_VOWEL_SIGN_E = "\u{EC0}";

    #[Info(id: 3777, name: 'LAO VOWEL SIGN EI', category: Cat::Other_Letter)]
    case LAO_VOWEL_SIGN_EI = "\u{EC1}";

    #[Info(id: 3778, name: 'LAO VOWEL SIGN O', category: Cat::Other_Letter)]
    case LAO_VOWEL_SIGN_O = "\u{EC2}";

    #[Info(id: 3779, name: 'LAO VOWEL SIGN AY', category: Cat::Other_Letter)]
    case LAO_VOWEL_SIGN_AY = "\u{EC3}";

    #[Info(id: 3780, name: 'LAO VOWEL SIGN AI', category: Cat::Other_Letter)]
    case LAO_VOWEL_SIGN_AI = "\u{EC4}";

    #[Info(id: 3782, name: 'LAO KO LA', category: Cat::Modifier_Letter)]
    case LAO_KO_LA = "\u{EC6}";

    #[Info(id: 3784, name: 'LAO TONE MAI EK', category: Cat::Nonspacing_Mark)]
    case LAO_TONE_MAI_EK = "\u{EC8}";

    #[Info(id: 3785, name: 'LAO TONE MAI THO', category: Cat::Nonspacing_Mark)]
    case LAO_TONE_MAI_THO = "\u{EC9}";

    #[Info(id: 3786, name: 'LAO TONE MAI TI', category: Cat::Nonspacing_Mark)]
    case LAO_TONE_MAI_TI = "\u{ECA}";

    #[Info(id: 3787, name: 'LAO TONE MAI CATAWA', category: Cat::Nonspacing_Mark)]
    case LAO_TONE_MAI_CATAWA = "\u{ECB}";

    #[Info(id: 3788, name: 'LAO CANCELLATION MARK', category: Cat::Nonspacing_Mark)]
    case LAO_CANCELLATION_MARK = "\u{ECC}";

    #[Info(id: 3789, name: 'LAO NIGGAHITA', category: Cat::Nonspacing_Mark)]
    case LAO_NIGGAHITA = "\u{ECD}";

    #[Info(id: 3790, name: 'LAO YAMAKKAN', category: Cat::Nonspacing_Mark)]
    case LAO_YAMAKKAN = "\u{ECE}";

    #[Info(id: 3792, name: 'LAO DIGIT ZERO', category: Cat::Decimal_Number)]
    case LAO_DIGIT_ZERO = "\u{ED0}";

    #[Info(id: 3793, name: 'LAO DIGIT ONE', category: Cat::Decimal_Number)]
    case LAO_DIGIT_ONE = "\u{ED1}";

    #[Info(id: 3794, name: 'LAO DIGIT TWO', category: Cat::Decimal_Number)]
    case LAO_DIGIT_TWO = "\u{ED2}";

    #[Info(id: 3795, name: 'LAO DIGIT THREE', category: Cat::Decimal_Number)]
    case LAO_DIGIT_THREE = "\u{ED3}";

    #[Info(id: 3796, name: 'LAO DIGIT FOUR', category: Cat::Decimal_Number)]
    case LAO_DIGIT_FOUR = "\u{ED4}";

    #[Info(id: 3797, name: 'LAO DIGIT FIVE', category: Cat::Decimal_Number)]
    case LAO_DIGIT_FIVE = "\u{ED5}";

    #[Info(id: 3798, name: 'LAO DIGIT SIX', category: Cat::Decimal_Number)]
    case LAO_DIGIT_SIX = "\u{ED6}";

    #[Info(id: 3799, name: 'LAO DIGIT SEVEN', category: Cat::Decimal_Number)]
    case LAO_DIGIT_SEVEN = "\u{ED7}";

    #[Info(id: 3800, name: 'LAO DIGIT EIGHT', category: Cat::Decimal_Number)]
    case LAO_DIGIT_EIGHT = "\u{ED8}";

    #[Info(id: 3801, name: 'LAO DIGIT NINE', category: Cat::Decimal_Number)]
    case LAO_DIGIT_NINE = "\u{ED9}";

    #[Info(id: 3804, name: 'LAO HO NO', category: Cat::Other_Letter)]
    case LAO_HO_NO = "\u{EDC}";

    #[Info(id: 3805, name: 'LAO HO MO', category: Cat::Other_Letter)]
    case LAO_HO_MO = "\u{EDD}";

    #[Info(id: 3806, name: 'LAO LETTER KHMU GO', category: Cat::Other_Letter)]
    case LAO_LETTER_KHMU_GO = "\u{EDE}";

    #[Info(id: 3807, name: 'LAO LETTER KHMU NYO', category: Cat::Other_Letter)]
    case LAO_LETTER_KHMU_NYO = "\u{EDF}";
}
