<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Nandinagari: string
{
    #[Info(id: 0x119A0, name: 'NANDINAGARI LETTER A', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_A = "\u{119A0}";

    #[Info(id: 0x119A1, name: 'NANDINAGARI LETTER AA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_AA = "\u{119A1}";

    #[Info(id: 0x119A2, name: 'NANDINAGARI LETTER I', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_I = "\u{119A2}";

    #[Info(id: 0x119A3, name: 'NANDINAGARI LETTER II', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_II = "\u{119A3}";

    #[Info(id: 0x119A4, name: 'NANDINAGARI LETTER U', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_U = "\u{119A4}";

    #[Info(id: 0x119A5, name: 'NANDINAGARI LETTER UU', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_UU = "\u{119A5}";

    #[Info(id: 0x119A6, name: 'NANDINAGARI LETTER VOCALIC R', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_VOCALIC_R = "\u{119A6}";

    #[Info(id: 0x119A7, name: 'NANDINAGARI LETTER VOCALIC RR', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_VOCALIC_RR = "\u{119A7}";

    #[Info(id: 0x119AA, name: 'NANDINAGARI LETTER E', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_E = "\u{119AA}";

    #[Info(id: 0x119AB, name: 'NANDINAGARI LETTER AI', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_AI = "\u{119AB}";

    #[Info(id: 0x119AC, name: 'NANDINAGARI LETTER O', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_O = "\u{119AC}";

    #[Info(id: 0x119AD, name: 'NANDINAGARI LETTER AU', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_AU = "\u{119AD}";

    #[Info(id: 0x119AE, name: 'NANDINAGARI LETTER KA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_KA = "\u{119AE}";

    #[Info(id: 0x119AF, name: 'NANDINAGARI LETTER KHA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_KHA = "\u{119AF}";

    #[Info(id: 0x119B0, name: 'NANDINAGARI LETTER GA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_GA = "\u{119B0}";

    #[Info(id: 0x119B1, name: 'NANDINAGARI LETTER GHA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_GHA = "\u{119B1}";

    #[Info(id: 0x119B2, name: 'NANDINAGARI LETTER NGA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_NGA = "\u{119B2}";

    #[Info(id: 0x119B3, name: 'NANDINAGARI LETTER CA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_CA = "\u{119B3}";

    #[Info(id: 0x119B4, name: 'NANDINAGARI LETTER CHA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_CHA = "\u{119B4}";

    #[Info(id: 0x119B5, name: 'NANDINAGARI LETTER JA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_JA = "\u{119B5}";

    #[Info(id: 0x119B6, name: 'NANDINAGARI LETTER JHA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_JHA = "\u{119B6}";

    #[Info(id: 0x119B7, name: 'NANDINAGARI LETTER NYA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_NYA = "\u{119B7}";

    #[Info(id: 0x119B8, name: 'NANDINAGARI LETTER TTA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_TTA = "\u{119B8}";

    #[Info(id: 0x119B9, name: 'NANDINAGARI LETTER TTHA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_TTHA = "\u{119B9}";

    #[Info(id: 0x119BA, name: 'NANDINAGARI LETTER DDA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_DDA = "\u{119BA}";

    #[Info(id: 0x119BB, name: 'NANDINAGARI LETTER DDHA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_DDHA = "\u{119BB}";

    #[Info(id: 0x119BC, name: 'NANDINAGARI LETTER NNA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_NNA = "\u{119BC}";

    #[Info(id: 0x119BD, name: 'NANDINAGARI LETTER TA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_TA = "\u{119BD}";

    #[Info(id: 0x119BE, name: 'NANDINAGARI LETTER THA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_THA = "\u{119BE}";

    #[Info(id: 0x119BF, name: 'NANDINAGARI LETTER DA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_DA = "\u{119BF}";

    #[Info(id: 0x119C0, name: 'NANDINAGARI LETTER DHA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_DHA = "\u{119C0}";

    #[Info(id: 0x119C1, name: 'NANDINAGARI LETTER NA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_NA = "\u{119C1}";

    #[Info(id: 0x119C2, name: 'NANDINAGARI LETTER PA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_PA = "\u{119C2}";

    #[Info(id: 0x119C3, name: 'NANDINAGARI LETTER PHA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_PHA = "\u{119C3}";

    #[Info(id: 0x119C4, name: 'NANDINAGARI LETTER BA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_BA = "\u{119C4}";

    #[Info(id: 0x119C5, name: 'NANDINAGARI LETTER BHA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_BHA = "\u{119C5}";

    #[Info(id: 0x119C6, name: 'NANDINAGARI LETTER MA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_MA = "\u{119C6}";

    #[Info(id: 0x119C7, name: 'NANDINAGARI LETTER YA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_YA = "\u{119C7}";

    #[Info(id: 0x119C8, name: 'NANDINAGARI LETTER RA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_RA = "\u{119C8}";

    #[Info(id: 0x119C9, name: 'NANDINAGARI LETTER LA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_LA = "\u{119C9}";

    #[Info(id: 0x119CA, name: 'NANDINAGARI LETTER VA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_VA = "\u{119CA}";

    #[Info(id: 0x119CB, name: 'NANDINAGARI LETTER SHA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_SHA = "\u{119CB}";

    #[Info(id: 0x119CC, name: 'NANDINAGARI LETTER SSA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_SSA = "\u{119CC}";

    #[Info(id: 0x119CD, name: 'NANDINAGARI LETTER SA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_SA = "\u{119CD}";

    #[Info(id: 0x119CE, name: 'NANDINAGARI LETTER HA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_HA = "\u{119CE}";

    #[Info(id: 0x119CF, name: 'NANDINAGARI LETTER LLA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_LLA = "\u{119CF}";

    #[Info(id: 0x119D0, name: 'NANDINAGARI LETTER RRA', category: Cat::Other_Letter)]
    case NANDINAGARI_LETTER_RRA = "\u{119D0}";

    #[Info(id: 0x119D1, name: 'NANDINAGARI VOWEL SIGN AA', category: Cat::Spacing_Mark)]
    case NANDINAGARI_VOWEL_SIGN_AA = "\u{119D1}";

    #[Info(id: 0x119D2, name: 'NANDINAGARI VOWEL SIGN I', category: Cat::Spacing_Mark)]
    case NANDINAGARI_VOWEL_SIGN_I = "\u{119D2}";

    #[Info(id: 0x119D3, name: 'NANDINAGARI VOWEL SIGN II', category: Cat::Spacing_Mark)]
    case NANDINAGARI_VOWEL_SIGN_II = "\u{119D3}";

    #[Info(id: 0x119D4, name: 'NANDINAGARI VOWEL SIGN U', category: Cat::Nonspacing_Mark)]
    case NANDINAGARI_VOWEL_SIGN_U = "\u{119D4}";

    #[Info(id: 0x119D5, name: 'NANDINAGARI VOWEL SIGN UU', category: Cat::Nonspacing_Mark)]
    case NANDINAGARI_VOWEL_SIGN_UU = "\u{119D5}";

    #[Info(id: 0x119D6, name: 'NANDINAGARI VOWEL SIGN VOCALIC R', category: Cat::Nonspacing_Mark)]
    case NANDINAGARI_VOWEL_SIGN_VOCALIC_R = "\u{119D6}";

    #[Info(id: 0x119D7, name: 'NANDINAGARI VOWEL SIGN VOCALIC RR', category: Cat::Nonspacing_Mark)]
    case NANDINAGARI_VOWEL_SIGN_VOCALIC_RR = "\u{119D7}";

    #[Info(id: 0x119DA, name: 'NANDINAGARI VOWEL SIGN E', category: Cat::Nonspacing_Mark)]
    case NANDINAGARI_VOWEL_SIGN_E = "\u{119DA}";

    #[Info(id: 0x119DB, name: 'NANDINAGARI VOWEL SIGN AI', category: Cat::Nonspacing_Mark)]
    case NANDINAGARI_VOWEL_SIGN_AI = "\u{119DB}";

    #[Info(id: 0x119DC, name: 'NANDINAGARI VOWEL SIGN O', category: Cat::Spacing_Mark)]
    case NANDINAGARI_VOWEL_SIGN_O = "\u{119DC}";

    #[Info(id: 0x119DD, name: 'NANDINAGARI VOWEL SIGN AU', category: Cat::Spacing_Mark)]
    case NANDINAGARI_VOWEL_SIGN_AU = "\u{119DD}";

    #[Info(id: 0x119DE, name: 'NANDINAGARI SIGN ANUSVARA', category: Cat::Spacing_Mark)]
    case NANDINAGARI_SIGN_ANUSVARA = "\u{119DE}";

    #[Info(id: 0x119DF, name: 'NANDINAGARI SIGN VISARGA', category: Cat::Spacing_Mark)]
    case NANDINAGARI_SIGN_VISARGA = "\u{119DF}";

    #[Info(id: 0x119E0, name: 'NANDINAGARI SIGN VIRAMA', category: Cat::Nonspacing_Mark)]
    case NANDINAGARI_SIGN_VIRAMA = "\u{119E0}";

    #[Info(id: 0x119E1, name: 'NANDINAGARI SIGN AVAGRAHA', category: Cat::Other_Letter)]
    case NANDINAGARI_SIGN_AVAGRAHA = "\u{119E1}";

    #[Info(id: 0x119E2, name: 'NANDINAGARI SIGN SIDDHAM', category: Cat::Other_Punctuation)]
    case NANDINAGARI_SIGN_SIDDHAM = "\u{119E2}";

    #[Info(id: 0x119E3, name: 'NANDINAGARI HEADSTROKE', category: Cat::Other_Letter)]
    case NANDINAGARI_HEADSTROKE = "\u{119E3}";

    #[Info(id: 0x119E4, name: 'NANDINAGARI VOWEL SIGN PRISHTHAMATRA E', category: Cat::Spacing_Mark)]
    case NANDINAGARI_VOWEL_SIGN_PRISHTHAMATRA_E = "\u{119E4}";
}
