<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Nushu: string
{
    #[Info(id: 110960, name: 'NUSHU CHARACTER-1B170', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B170 = "\u{1B170}";

    #[Info(id: 110961, name: 'NUSHU CHARACTER-1B171', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B171 = "\u{1B171}";

    #[Info(id: 110962, name: 'NUSHU CHARACTER-1B172', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B172 = "\u{1B172}";

    #[Info(id: 110963, name: 'NUSHU CHARACTER-1B173', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B173 = "\u{1B173}";

    #[Info(id: 110964, name: 'NUSHU CHARACTER-1B174', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B174 = "\u{1B174}";

    #[Info(id: 110965, name: 'NUSHU CHARACTER-1B175', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B175 = "\u{1B175}";

    #[Info(id: 110966, name: 'NUSHU CHARACTER-1B176', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B176 = "\u{1B176}";

    #[Info(id: 110967, name: 'NUSHU CHARACTER-1B177', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B177 = "\u{1B177}";

    #[Info(id: 110968, name: 'NUSHU CHARACTER-1B178', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B178 = "\u{1B178}";

    #[Info(id: 110969, name: 'NUSHU CHARACTER-1B179', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B179 = "\u{1B179}";

    #[Info(id: 110970, name: 'NUSHU CHARACTER-1B17A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B17A = "\u{1B17A}";

    #[Info(id: 110971, name: 'NUSHU CHARACTER-1B17B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B17B = "\u{1B17B}";

    #[Info(id: 110972, name: 'NUSHU CHARACTER-1B17C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B17C = "\u{1B17C}";

    #[Info(id: 110973, name: 'NUSHU CHARACTER-1B17D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B17D = "\u{1B17D}";

    #[Info(id: 110974, name: 'NUSHU CHARACTER-1B17E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B17E = "\u{1B17E}";

    #[Info(id: 110975, name: 'NUSHU CHARACTER-1B17F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B17F = "\u{1B17F}";

    #[Info(id: 110976, name: 'NUSHU CHARACTER-1B180', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B180 = "\u{1B180}";

    #[Info(id: 110977, name: 'NUSHU CHARACTER-1B181', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B181 = "\u{1B181}";

    #[Info(id: 110978, name: 'NUSHU CHARACTER-1B182', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B182 = "\u{1B182}";

    #[Info(id: 110979, name: 'NUSHU CHARACTER-1B183', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B183 = "\u{1B183}";

    #[Info(id: 110980, name: 'NUSHU CHARACTER-1B184', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B184 = "\u{1B184}";

    #[Info(id: 110981, name: 'NUSHU CHARACTER-1B185', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B185 = "\u{1B185}";

    #[Info(id: 110982, name: 'NUSHU CHARACTER-1B186', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B186 = "\u{1B186}";

    #[Info(id: 110983, name: 'NUSHU CHARACTER-1B187', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B187 = "\u{1B187}";

    #[Info(id: 110984, name: 'NUSHU CHARACTER-1B188', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B188 = "\u{1B188}";

    #[Info(id: 110985, name: 'NUSHU CHARACTER-1B189', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B189 = "\u{1B189}";

    #[Info(id: 110986, name: 'NUSHU CHARACTER-1B18A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B18A = "\u{1B18A}";

    #[Info(id: 110987, name: 'NUSHU CHARACTER-1B18B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B18B = "\u{1B18B}";

    #[Info(id: 110988, name: 'NUSHU CHARACTER-1B18C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B18C = "\u{1B18C}";

    #[Info(id: 110989, name: 'NUSHU CHARACTER-1B18D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B18D = "\u{1B18D}";

    #[Info(id: 110990, name: 'NUSHU CHARACTER-1B18E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B18E = "\u{1B18E}";

    #[Info(id: 110991, name: 'NUSHU CHARACTER-1B18F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B18F = "\u{1B18F}";

    #[Info(id: 110992, name: 'NUSHU CHARACTER-1B190', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B190 = "\u{1B190}";

    #[Info(id: 110993, name: 'NUSHU CHARACTER-1B191', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B191 = "\u{1B191}";

    #[Info(id: 110994, name: 'NUSHU CHARACTER-1B192', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B192 = "\u{1B192}";

    #[Info(id: 110995, name: 'NUSHU CHARACTER-1B193', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B193 = "\u{1B193}";

    #[Info(id: 110996, name: 'NUSHU CHARACTER-1B194', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B194 = "\u{1B194}";

    #[Info(id: 110997, name: 'NUSHU CHARACTER-1B195', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B195 = "\u{1B195}";

    #[Info(id: 110998, name: 'NUSHU CHARACTER-1B196', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B196 = "\u{1B196}";

    #[Info(id: 110999, name: 'NUSHU CHARACTER-1B197', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B197 = "\u{1B197}";

    #[Info(id: 111000, name: 'NUSHU CHARACTER-1B198', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B198 = "\u{1B198}";

    #[Info(id: 111001, name: 'NUSHU CHARACTER-1B199', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B199 = "\u{1B199}";

    #[Info(id: 111002, name: 'NUSHU CHARACTER-1B19A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B19A = "\u{1B19A}";

    #[Info(id: 111003, name: 'NUSHU CHARACTER-1B19B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B19B = "\u{1B19B}";

    #[Info(id: 111004, name: 'NUSHU CHARACTER-1B19C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B19C = "\u{1B19C}";

    #[Info(id: 111005, name: 'NUSHU CHARACTER-1B19D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B19D = "\u{1B19D}";

    #[Info(id: 111006, name: 'NUSHU CHARACTER-1B19E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B19E = "\u{1B19E}";

    #[Info(id: 111007, name: 'NUSHU CHARACTER-1B19F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B19F = "\u{1B19F}";

    #[Info(id: 111008, name: 'NUSHU CHARACTER-1B1A0', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1A0 = "\u{1B1A0}";

    #[Info(id: 111009, name: 'NUSHU CHARACTER-1B1A1', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1A1 = "\u{1B1A1}";

    #[Info(id: 111010, name: 'NUSHU CHARACTER-1B1A2', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1A2 = "\u{1B1A2}";

    #[Info(id: 111011, name: 'NUSHU CHARACTER-1B1A3', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1A3 = "\u{1B1A3}";

    #[Info(id: 111012, name: 'NUSHU CHARACTER-1B1A4', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1A4 = "\u{1B1A4}";

    #[Info(id: 111013, name: 'NUSHU CHARACTER-1B1A5', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1A5 = "\u{1B1A5}";

    #[Info(id: 111014, name: 'NUSHU CHARACTER-1B1A6', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1A6 = "\u{1B1A6}";

    #[Info(id: 111015, name: 'NUSHU CHARACTER-1B1A7', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1A7 = "\u{1B1A7}";

    #[Info(id: 111016, name: 'NUSHU CHARACTER-1B1A8', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1A8 = "\u{1B1A8}";

    #[Info(id: 111017, name: 'NUSHU CHARACTER-1B1A9', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1A9 = "\u{1B1A9}";

    #[Info(id: 111018, name: 'NUSHU CHARACTER-1B1AA', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1AA = "\u{1B1AA}";

    #[Info(id: 111019, name: 'NUSHU CHARACTER-1B1AB', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1AB = "\u{1B1AB}";

    #[Info(id: 111020, name: 'NUSHU CHARACTER-1B1AC', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1AC = "\u{1B1AC}";

    #[Info(id: 111021, name: 'NUSHU CHARACTER-1B1AD', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1AD = "\u{1B1AD}";

    #[Info(id: 111022, name: 'NUSHU CHARACTER-1B1AE', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1AE = "\u{1B1AE}";

    #[Info(id: 111023, name: 'NUSHU CHARACTER-1B1AF', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1AF = "\u{1B1AF}";

    #[Info(id: 111024, name: 'NUSHU CHARACTER-1B1B0', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1B0 = "\u{1B1B0}";

    #[Info(id: 111025, name: 'NUSHU CHARACTER-1B1B1', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1B1 = "\u{1B1B1}";

    #[Info(id: 111026, name: 'NUSHU CHARACTER-1B1B2', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1B2 = "\u{1B1B2}";

    #[Info(id: 111027, name: 'NUSHU CHARACTER-1B1B3', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1B3 = "\u{1B1B3}";

    #[Info(id: 111028, name: 'NUSHU CHARACTER-1B1B4', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1B4 = "\u{1B1B4}";

    #[Info(id: 111029, name: 'NUSHU CHARACTER-1B1B5', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1B5 = "\u{1B1B5}";

    #[Info(id: 111030, name: 'NUSHU CHARACTER-1B1B6', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1B6 = "\u{1B1B6}";

    #[Info(id: 111031, name: 'NUSHU CHARACTER-1B1B7', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1B7 = "\u{1B1B7}";

    #[Info(id: 111032, name: 'NUSHU CHARACTER-1B1B8', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1B8 = "\u{1B1B8}";

    #[Info(id: 111033, name: 'NUSHU CHARACTER-1B1B9', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1B9 = "\u{1B1B9}";

    #[Info(id: 111034, name: 'NUSHU CHARACTER-1B1BA', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1BA = "\u{1B1BA}";

    #[Info(id: 111035, name: 'NUSHU CHARACTER-1B1BB', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1BB = "\u{1B1BB}";

    #[Info(id: 111036, name: 'NUSHU CHARACTER-1B1BC', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1BC = "\u{1B1BC}";

    #[Info(id: 111037, name: 'NUSHU CHARACTER-1B1BD', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1BD = "\u{1B1BD}";

    #[Info(id: 111038, name: 'NUSHU CHARACTER-1B1BE', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1BE = "\u{1B1BE}";

    #[Info(id: 111039, name: 'NUSHU CHARACTER-1B1BF', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1BF = "\u{1B1BF}";

    #[Info(id: 111040, name: 'NUSHU CHARACTER-1B1C0', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1C0 = "\u{1B1C0}";

    #[Info(id: 111041, name: 'NUSHU CHARACTER-1B1C1', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1C1 = "\u{1B1C1}";

    #[Info(id: 111042, name: 'NUSHU CHARACTER-1B1C2', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1C2 = "\u{1B1C2}";

    #[Info(id: 111043, name: 'NUSHU CHARACTER-1B1C3', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1C3 = "\u{1B1C3}";

    #[Info(id: 111044, name: 'NUSHU CHARACTER-1B1C4', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1C4 = "\u{1B1C4}";

    #[Info(id: 111045, name: 'NUSHU CHARACTER-1B1C5', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1C5 = "\u{1B1C5}";

    #[Info(id: 111046, name: 'NUSHU CHARACTER-1B1C6', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1C6 = "\u{1B1C6}";

    #[Info(id: 111047, name: 'NUSHU CHARACTER-1B1C7', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1C7 = "\u{1B1C7}";

    #[Info(id: 111048, name: 'NUSHU CHARACTER-1B1C8', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1C8 = "\u{1B1C8}";

    #[Info(id: 111049, name: 'NUSHU CHARACTER-1B1C9', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1C9 = "\u{1B1C9}";

    #[Info(id: 111050, name: 'NUSHU CHARACTER-1B1CA', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1CA = "\u{1B1CA}";

    #[Info(id: 111051, name: 'NUSHU CHARACTER-1B1CB', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1CB = "\u{1B1CB}";

    #[Info(id: 111052, name: 'NUSHU CHARACTER-1B1CC', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1CC = "\u{1B1CC}";

    #[Info(id: 111053, name: 'NUSHU CHARACTER-1B1CD', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1CD = "\u{1B1CD}";

    #[Info(id: 111054, name: 'NUSHU CHARACTER-1B1CE', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1CE = "\u{1B1CE}";

    #[Info(id: 111055, name: 'NUSHU CHARACTER-1B1CF', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1CF = "\u{1B1CF}";

    #[Info(id: 111056, name: 'NUSHU CHARACTER-1B1D0', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1D0 = "\u{1B1D0}";

    #[Info(id: 111057, name: 'NUSHU CHARACTER-1B1D1', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1D1 = "\u{1B1D1}";

    #[Info(id: 111058, name: 'NUSHU CHARACTER-1B1D2', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1D2 = "\u{1B1D2}";

    #[Info(id: 111059, name: 'NUSHU CHARACTER-1B1D3', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1D3 = "\u{1B1D3}";

    #[Info(id: 111060, name: 'NUSHU CHARACTER-1B1D4', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1D4 = "\u{1B1D4}";

    #[Info(id: 111061, name: 'NUSHU CHARACTER-1B1D5', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1D5 = "\u{1B1D5}";

    #[Info(id: 111062, name: 'NUSHU CHARACTER-1B1D6', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1D6 = "\u{1B1D6}";

    #[Info(id: 111063, name: 'NUSHU CHARACTER-1B1D7', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1D7 = "\u{1B1D7}";

    #[Info(id: 111064, name: 'NUSHU CHARACTER-1B1D8', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1D8 = "\u{1B1D8}";

    #[Info(id: 111065, name: 'NUSHU CHARACTER-1B1D9', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1D9 = "\u{1B1D9}";

    #[Info(id: 111066, name: 'NUSHU CHARACTER-1B1DA', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1DA = "\u{1B1DA}";

    #[Info(id: 111067, name: 'NUSHU CHARACTER-1B1DB', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1DB = "\u{1B1DB}";

    #[Info(id: 111068, name: 'NUSHU CHARACTER-1B1DC', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1DC = "\u{1B1DC}";

    #[Info(id: 111069, name: 'NUSHU CHARACTER-1B1DD', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1DD = "\u{1B1DD}";

    #[Info(id: 111070, name: 'NUSHU CHARACTER-1B1DE', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1DE = "\u{1B1DE}";

    #[Info(id: 111071, name: 'NUSHU CHARACTER-1B1DF', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1DF = "\u{1B1DF}";

    #[Info(id: 111072, name: 'NUSHU CHARACTER-1B1E0', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1E0 = "\u{1B1E0}";

    #[Info(id: 111073, name: 'NUSHU CHARACTER-1B1E1', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1E1 = "\u{1B1E1}";

    #[Info(id: 111074, name: 'NUSHU CHARACTER-1B1E2', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1E2 = "\u{1B1E2}";

    #[Info(id: 111075, name: 'NUSHU CHARACTER-1B1E3', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1E3 = "\u{1B1E3}";

    #[Info(id: 111076, name: 'NUSHU CHARACTER-1B1E4', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1E4 = "\u{1B1E4}";

    #[Info(id: 111077, name: 'NUSHU CHARACTER-1B1E5', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1E5 = "\u{1B1E5}";

    #[Info(id: 111078, name: 'NUSHU CHARACTER-1B1E6', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1E6 = "\u{1B1E6}";

    #[Info(id: 111079, name: 'NUSHU CHARACTER-1B1E7', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1E7 = "\u{1B1E7}";

    #[Info(id: 111080, name: 'NUSHU CHARACTER-1B1E8', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1E8 = "\u{1B1E8}";

    #[Info(id: 111081, name: 'NUSHU CHARACTER-1B1E9', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1E9 = "\u{1B1E9}";

    #[Info(id: 111082, name: 'NUSHU CHARACTER-1B1EA', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1EA = "\u{1B1EA}";

    #[Info(id: 111083, name: 'NUSHU CHARACTER-1B1EB', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1EB = "\u{1B1EB}";

    #[Info(id: 111084, name: 'NUSHU CHARACTER-1B1EC', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1EC = "\u{1B1EC}";

    #[Info(id: 111085, name: 'NUSHU CHARACTER-1B1ED', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1ED = "\u{1B1ED}";

    #[Info(id: 111086, name: 'NUSHU CHARACTER-1B1EE', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1EE = "\u{1B1EE}";

    #[Info(id: 111087, name: 'NUSHU CHARACTER-1B1EF', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1EF = "\u{1B1EF}";

    #[Info(id: 111088, name: 'NUSHU CHARACTER-1B1F0', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1F0 = "\u{1B1F0}";

    #[Info(id: 111089, name: 'NUSHU CHARACTER-1B1F1', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1F1 = "\u{1B1F1}";

    #[Info(id: 111090, name: 'NUSHU CHARACTER-1B1F2', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1F2 = "\u{1B1F2}";

    #[Info(id: 111091, name: 'NUSHU CHARACTER-1B1F3', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1F3 = "\u{1B1F3}";

    #[Info(id: 111092, name: 'NUSHU CHARACTER-1B1F4', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1F4 = "\u{1B1F4}";

    #[Info(id: 111093, name: 'NUSHU CHARACTER-1B1F5', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1F5 = "\u{1B1F5}";

    #[Info(id: 111094, name: 'NUSHU CHARACTER-1B1F6', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1F6 = "\u{1B1F6}";

    #[Info(id: 111095, name: 'NUSHU CHARACTER-1B1F7', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1F7 = "\u{1B1F7}";

    #[Info(id: 111096, name: 'NUSHU CHARACTER-1B1F8', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1F8 = "\u{1B1F8}";

    #[Info(id: 111097, name: 'NUSHU CHARACTER-1B1F9', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1F9 = "\u{1B1F9}";

    #[Info(id: 111098, name: 'NUSHU CHARACTER-1B1FA', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1FA = "\u{1B1FA}";

    #[Info(id: 111099, name: 'NUSHU CHARACTER-1B1FB', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1FB = "\u{1B1FB}";

    #[Info(id: 111100, name: 'NUSHU CHARACTER-1B1FC', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1FC = "\u{1B1FC}";

    #[Info(id: 111101, name: 'NUSHU CHARACTER-1B1FD', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1FD = "\u{1B1FD}";

    #[Info(id: 111102, name: 'NUSHU CHARACTER-1B1FE', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1FE = "\u{1B1FE}";

    #[Info(id: 111103, name: 'NUSHU CHARACTER-1B1FF', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B1FF = "\u{1B1FF}";

    #[Info(id: 111104, name: 'NUSHU CHARACTER-1B200', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B200 = "\u{1B200}";

    #[Info(id: 111105, name: 'NUSHU CHARACTER-1B201', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B201 = "\u{1B201}";

    #[Info(id: 111106, name: 'NUSHU CHARACTER-1B202', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B202 = "\u{1B202}";

    #[Info(id: 111107, name: 'NUSHU CHARACTER-1B203', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B203 = "\u{1B203}";

    #[Info(id: 111108, name: 'NUSHU CHARACTER-1B204', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B204 = "\u{1B204}";

    #[Info(id: 111109, name: 'NUSHU CHARACTER-1B205', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B205 = "\u{1B205}";

    #[Info(id: 111110, name: 'NUSHU CHARACTER-1B206', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B206 = "\u{1B206}";

    #[Info(id: 111111, name: 'NUSHU CHARACTER-1B207', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B207 = "\u{1B207}";

    #[Info(id: 111112, name: 'NUSHU CHARACTER-1B208', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B208 = "\u{1B208}";

    #[Info(id: 111113, name: 'NUSHU CHARACTER-1B209', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B209 = "\u{1B209}";

    #[Info(id: 111114, name: 'NUSHU CHARACTER-1B20A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B20A = "\u{1B20A}";

    #[Info(id: 111115, name: 'NUSHU CHARACTER-1B20B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B20B = "\u{1B20B}";

    #[Info(id: 111116, name: 'NUSHU CHARACTER-1B20C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B20C = "\u{1B20C}";

    #[Info(id: 111117, name: 'NUSHU CHARACTER-1B20D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B20D = "\u{1B20D}";

    #[Info(id: 111118, name: 'NUSHU CHARACTER-1B20E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B20E = "\u{1B20E}";

    #[Info(id: 111119, name: 'NUSHU CHARACTER-1B20F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B20F = "\u{1B20F}";

    #[Info(id: 111120, name: 'NUSHU CHARACTER-1B210', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B210 = "\u{1B210}";

    #[Info(id: 111121, name: 'NUSHU CHARACTER-1B211', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B211 = "\u{1B211}";

    #[Info(id: 111122, name: 'NUSHU CHARACTER-1B212', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B212 = "\u{1B212}";

    #[Info(id: 111123, name: 'NUSHU CHARACTER-1B213', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B213 = "\u{1B213}";

    #[Info(id: 111124, name: 'NUSHU CHARACTER-1B214', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B214 = "\u{1B214}";

    #[Info(id: 111125, name: 'NUSHU CHARACTER-1B215', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B215 = "\u{1B215}";

    #[Info(id: 111126, name: 'NUSHU CHARACTER-1B216', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B216 = "\u{1B216}";

    #[Info(id: 111127, name: 'NUSHU CHARACTER-1B217', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B217 = "\u{1B217}";

    #[Info(id: 111128, name: 'NUSHU CHARACTER-1B218', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B218 = "\u{1B218}";

    #[Info(id: 111129, name: 'NUSHU CHARACTER-1B219', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B219 = "\u{1B219}";

    #[Info(id: 111130, name: 'NUSHU CHARACTER-1B21A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B21A = "\u{1B21A}";

    #[Info(id: 111131, name: 'NUSHU CHARACTER-1B21B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B21B = "\u{1B21B}";

    #[Info(id: 111132, name: 'NUSHU CHARACTER-1B21C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B21C = "\u{1B21C}";

    #[Info(id: 111133, name: 'NUSHU CHARACTER-1B21D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B21D = "\u{1B21D}";

    #[Info(id: 111134, name: 'NUSHU CHARACTER-1B21E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B21E = "\u{1B21E}";

    #[Info(id: 111135, name: 'NUSHU CHARACTER-1B21F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B21F = "\u{1B21F}";

    #[Info(id: 111136, name: 'NUSHU CHARACTER-1B220', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B220 = "\u{1B220}";

    #[Info(id: 111137, name: 'NUSHU CHARACTER-1B221', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B221 = "\u{1B221}";

    #[Info(id: 111138, name: 'NUSHU CHARACTER-1B222', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B222 = "\u{1B222}";

    #[Info(id: 111139, name: 'NUSHU CHARACTER-1B223', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B223 = "\u{1B223}";

    #[Info(id: 111140, name: 'NUSHU CHARACTER-1B224', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B224 = "\u{1B224}";

    #[Info(id: 111141, name: 'NUSHU CHARACTER-1B225', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B225 = "\u{1B225}";

    #[Info(id: 111142, name: 'NUSHU CHARACTER-1B226', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B226 = "\u{1B226}";

    #[Info(id: 111143, name: 'NUSHU CHARACTER-1B227', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B227 = "\u{1B227}";

    #[Info(id: 111144, name: 'NUSHU CHARACTER-1B228', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B228 = "\u{1B228}";

    #[Info(id: 111145, name: 'NUSHU CHARACTER-1B229', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B229 = "\u{1B229}";

    #[Info(id: 111146, name: 'NUSHU CHARACTER-1B22A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B22A = "\u{1B22A}";

    #[Info(id: 111147, name: 'NUSHU CHARACTER-1B22B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B22B = "\u{1B22B}";

    #[Info(id: 111148, name: 'NUSHU CHARACTER-1B22C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B22C = "\u{1B22C}";

    #[Info(id: 111149, name: 'NUSHU CHARACTER-1B22D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B22D = "\u{1B22D}";

    #[Info(id: 111150, name: 'NUSHU CHARACTER-1B22E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B22E = "\u{1B22E}";

    #[Info(id: 111151, name: 'NUSHU CHARACTER-1B22F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B22F = "\u{1B22F}";

    #[Info(id: 111152, name: 'NUSHU CHARACTER-1B230', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B230 = "\u{1B230}";

    #[Info(id: 111153, name: 'NUSHU CHARACTER-1B231', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B231 = "\u{1B231}";

    #[Info(id: 111154, name: 'NUSHU CHARACTER-1B232', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B232 = "\u{1B232}";

    #[Info(id: 111155, name: 'NUSHU CHARACTER-1B233', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B233 = "\u{1B233}";

    #[Info(id: 111156, name: 'NUSHU CHARACTER-1B234', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B234 = "\u{1B234}";

    #[Info(id: 111157, name: 'NUSHU CHARACTER-1B235', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B235 = "\u{1B235}";

    #[Info(id: 111158, name: 'NUSHU CHARACTER-1B236', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B236 = "\u{1B236}";

    #[Info(id: 111159, name: 'NUSHU CHARACTER-1B237', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B237 = "\u{1B237}";

    #[Info(id: 111160, name: 'NUSHU CHARACTER-1B238', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B238 = "\u{1B238}";

    #[Info(id: 111161, name: 'NUSHU CHARACTER-1B239', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B239 = "\u{1B239}";

    #[Info(id: 111162, name: 'NUSHU CHARACTER-1B23A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B23A = "\u{1B23A}";

    #[Info(id: 111163, name: 'NUSHU CHARACTER-1B23B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B23B = "\u{1B23B}";

    #[Info(id: 111164, name: 'NUSHU CHARACTER-1B23C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B23C = "\u{1B23C}";

    #[Info(id: 111165, name: 'NUSHU CHARACTER-1B23D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B23D = "\u{1B23D}";

    #[Info(id: 111166, name: 'NUSHU CHARACTER-1B23E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B23E = "\u{1B23E}";

    #[Info(id: 111167, name: 'NUSHU CHARACTER-1B23F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B23F = "\u{1B23F}";

    #[Info(id: 111168, name: 'NUSHU CHARACTER-1B240', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B240 = "\u{1B240}";

    #[Info(id: 111169, name: 'NUSHU CHARACTER-1B241', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B241 = "\u{1B241}";

    #[Info(id: 111170, name: 'NUSHU CHARACTER-1B242', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B242 = "\u{1B242}";

    #[Info(id: 111171, name: 'NUSHU CHARACTER-1B243', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B243 = "\u{1B243}";

    #[Info(id: 111172, name: 'NUSHU CHARACTER-1B244', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B244 = "\u{1B244}";

    #[Info(id: 111173, name: 'NUSHU CHARACTER-1B245', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B245 = "\u{1B245}";

    #[Info(id: 111174, name: 'NUSHU CHARACTER-1B246', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B246 = "\u{1B246}";

    #[Info(id: 111175, name: 'NUSHU CHARACTER-1B247', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B247 = "\u{1B247}";

    #[Info(id: 111176, name: 'NUSHU CHARACTER-1B248', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B248 = "\u{1B248}";

    #[Info(id: 111177, name: 'NUSHU CHARACTER-1B249', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B249 = "\u{1B249}";

    #[Info(id: 111178, name: 'NUSHU CHARACTER-1B24A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B24A = "\u{1B24A}";

    #[Info(id: 111179, name: 'NUSHU CHARACTER-1B24B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B24B = "\u{1B24B}";

    #[Info(id: 111180, name: 'NUSHU CHARACTER-1B24C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B24C = "\u{1B24C}";

    #[Info(id: 111181, name: 'NUSHU CHARACTER-1B24D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B24D = "\u{1B24D}";

    #[Info(id: 111182, name: 'NUSHU CHARACTER-1B24E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B24E = "\u{1B24E}";

    #[Info(id: 111183, name: 'NUSHU CHARACTER-1B24F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B24F = "\u{1B24F}";

    #[Info(id: 111184, name: 'NUSHU CHARACTER-1B250', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B250 = "\u{1B250}";

    #[Info(id: 111185, name: 'NUSHU CHARACTER-1B251', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B251 = "\u{1B251}";

    #[Info(id: 111186, name: 'NUSHU CHARACTER-1B252', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B252 = "\u{1B252}";

    #[Info(id: 111187, name: 'NUSHU CHARACTER-1B253', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B253 = "\u{1B253}";

    #[Info(id: 111188, name: 'NUSHU CHARACTER-1B254', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B254 = "\u{1B254}";

    #[Info(id: 111189, name: 'NUSHU CHARACTER-1B255', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B255 = "\u{1B255}";

    #[Info(id: 111190, name: 'NUSHU CHARACTER-1B256', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B256 = "\u{1B256}";

    #[Info(id: 111191, name: 'NUSHU CHARACTER-1B257', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B257 = "\u{1B257}";

    #[Info(id: 111192, name: 'NUSHU CHARACTER-1B258', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B258 = "\u{1B258}";

    #[Info(id: 111193, name: 'NUSHU CHARACTER-1B259', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B259 = "\u{1B259}";

    #[Info(id: 111194, name: 'NUSHU CHARACTER-1B25A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B25A = "\u{1B25A}";

    #[Info(id: 111195, name: 'NUSHU CHARACTER-1B25B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B25B = "\u{1B25B}";

    #[Info(id: 111196, name: 'NUSHU CHARACTER-1B25C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B25C = "\u{1B25C}";

    #[Info(id: 111197, name: 'NUSHU CHARACTER-1B25D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B25D = "\u{1B25D}";

    #[Info(id: 111198, name: 'NUSHU CHARACTER-1B25E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B25E = "\u{1B25E}";

    #[Info(id: 111199, name: 'NUSHU CHARACTER-1B25F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B25F = "\u{1B25F}";

    #[Info(id: 111200, name: 'NUSHU CHARACTER-1B260', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B260 = "\u{1B260}";

    #[Info(id: 111201, name: 'NUSHU CHARACTER-1B261', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B261 = "\u{1B261}";

    #[Info(id: 111202, name: 'NUSHU CHARACTER-1B262', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B262 = "\u{1B262}";

    #[Info(id: 111203, name: 'NUSHU CHARACTER-1B263', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B263 = "\u{1B263}";

    #[Info(id: 111204, name: 'NUSHU CHARACTER-1B264', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B264 = "\u{1B264}";

    #[Info(id: 111205, name: 'NUSHU CHARACTER-1B265', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B265 = "\u{1B265}";

    #[Info(id: 111206, name: 'NUSHU CHARACTER-1B266', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B266 = "\u{1B266}";

    #[Info(id: 111207, name: 'NUSHU CHARACTER-1B267', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B267 = "\u{1B267}";

    #[Info(id: 111208, name: 'NUSHU CHARACTER-1B268', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B268 = "\u{1B268}";

    #[Info(id: 111209, name: 'NUSHU CHARACTER-1B269', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B269 = "\u{1B269}";

    #[Info(id: 111210, name: 'NUSHU CHARACTER-1B26A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B26A = "\u{1B26A}";

    #[Info(id: 111211, name: 'NUSHU CHARACTER-1B26B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B26B = "\u{1B26B}";

    #[Info(id: 111212, name: 'NUSHU CHARACTER-1B26C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B26C = "\u{1B26C}";

    #[Info(id: 111213, name: 'NUSHU CHARACTER-1B26D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B26D = "\u{1B26D}";

    #[Info(id: 111214, name: 'NUSHU CHARACTER-1B26E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B26E = "\u{1B26E}";

    #[Info(id: 111215, name: 'NUSHU CHARACTER-1B26F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B26F = "\u{1B26F}";

    #[Info(id: 111216, name: 'NUSHU CHARACTER-1B270', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B270 = "\u{1B270}";

    #[Info(id: 111217, name: 'NUSHU CHARACTER-1B271', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B271 = "\u{1B271}";

    #[Info(id: 111218, name: 'NUSHU CHARACTER-1B272', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B272 = "\u{1B272}";

    #[Info(id: 111219, name: 'NUSHU CHARACTER-1B273', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B273 = "\u{1B273}";

    #[Info(id: 111220, name: 'NUSHU CHARACTER-1B274', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B274 = "\u{1B274}";

    #[Info(id: 111221, name: 'NUSHU CHARACTER-1B275', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B275 = "\u{1B275}";

    #[Info(id: 111222, name: 'NUSHU CHARACTER-1B276', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B276 = "\u{1B276}";

    #[Info(id: 111223, name: 'NUSHU CHARACTER-1B277', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B277 = "\u{1B277}";

    #[Info(id: 111224, name: 'NUSHU CHARACTER-1B278', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B278 = "\u{1B278}";

    #[Info(id: 111225, name: 'NUSHU CHARACTER-1B279', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B279 = "\u{1B279}";

    #[Info(id: 111226, name: 'NUSHU CHARACTER-1B27A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B27A = "\u{1B27A}";

    #[Info(id: 111227, name: 'NUSHU CHARACTER-1B27B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B27B = "\u{1B27B}";

    #[Info(id: 111228, name: 'NUSHU CHARACTER-1B27C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B27C = "\u{1B27C}";

    #[Info(id: 111229, name: 'NUSHU CHARACTER-1B27D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B27D = "\u{1B27D}";

    #[Info(id: 111230, name: 'NUSHU CHARACTER-1B27E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B27E = "\u{1B27E}";

    #[Info(id: 111231, name: 'NUSHU CHARACTER-1B27F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B27F = "\u{1B27F}";

    #[Info(id: 111232, name: 'NUSHU CHARACTER-1B280', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B280 = "\u{1B280}";

    #[Info(id: 111233, name: 'NUSHU CHARACTER-1B281', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B281 = "\u{1B281}";

    #[Info(id: 111234, name: 'NUSHU CHARACTER-1B282', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B282 = "\u{1B282}";

    #[Info(id: 111235, name: 'NUSHU CHARACTER-1B283', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B283 = "\u{1B283}";

    #[Info(id: 111236, name: 'NUSHU CHARACTER-1B284', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B284 = "\u{1B284}";

    #[Info(id: 111237, name: 'NUSHU CHARACTER-1B285', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B285 = "\u{1B285}";

    #[Info(id: 111238, name: 'NUSHU CHARACTER-1B286', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B286 = "\u{1B286}";

    #[Info(id: 111239, name: 'NUSHU CHARACTER-1B287', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B287 = "\u{1B287}";

    #[Info(id: 111240, name: 'NUSHU CHARACTER-1B288', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B288 = "\u{1B288}";

    #[Info(id: 111241, name: 'NUSHU CHARACTER-1B289', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B289 = "\u{1B289}";

    #[Info(id: 111242, name: 'NUSHU CHARACTER-1B28A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B28A = "\u{1B28A}";

    #[Info(id: 111243, name: 'NUSHU CHARACTER-1B28B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B28B = "\u{1B28B}";

    #[Info(id: 111244, name: 'NUSHU CHARACTER-1B28C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B28C = "\u{1B28C}";

    #[Info(id: 111245, name: 'NUSHU CHARACTER-1B28D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B28D = "\u{1B28D}";

    #[Info(id: 111246, name: 'NUSHU CHARACTER-1B28E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B28E = "\u{1B28E}";

    #[Info(id: 111247, name: 'NUSHU CHARACTER-1B28F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B28F = "\u{1B28F}";

    #[Info(id: 111248, name: 'NUSHU CHARACTER-1B290', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B290 = "\u{1B290}";

    #[Info(id: 111249, name: 'NUSHU CHARACTER-1B291', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B291 = "\u{1B291}";

    #[Info(id: 111250, name: 'NUSHU CHARACTER-1B292', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B292 = "\u{1B292}";

    #[Info(id: 111251, name: 'NUSHU CHARACTER-1B293', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B293 = "\u{1B293}";

    #[Info(id: 111252, name: 'NUSHU CHARACTER-1B294', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B294 = "\u{1B294}";

    #[Info(id: 111253, name: 'NUSHU CHARACTER-1B295', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B295 = "\u{1B295}";

    #[Info(id: 111254, name: 'NUSHU CHARACTER-1B296', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B296 = "\u{1B296}";

    #[Info(id: 111255, name: 'NUSHU CHARACTER-1B297', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B297 = "\u{1B297}";

    #[Info(id: 111256, name: 'NUSHU CHARACTER-1B298', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B298 = "\u{1B298}";

    #[Info(id: 111257, name: 'NUSHU CHARACTER-1B299', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B299 = "\u{1B299}";

    #[Info(id: 111258, name: 'NUSHU CHARACTER-1B29A', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B29A = "\u{1B29A}";

    #[Info(id: 111259, name: 'NUSHU CHARACTER-1B29B', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B29B = "\u{1B29B}";

    #[Info(id: 111260, name: 'NUSHU CHARACTER-1B29C', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B29C = "\u{1B29C}";

    #[Info(id: 111261, name: 'NUSHU CHARACTER-1B29D', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B29D = "\u{1B29D}";

    #[Info(id: 111262, name: 'NUSHU CHARACTER-1B29E', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B29E = "\u{1B29E}";

    #[Info(id: 111263, name: 'NUSHU CHARACTER-1B29F', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B29F = "\u{1B29F}";

    #[Info(id: 111264, name: 'NUSHU CHARACTER-1B2A0', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2A0 = "\u{1B2A0}";

    #[Info(id: 111265, name: 'NUSHU CHARACTER-1B2A1', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2A1 = "\u{1B2A1}";

    #[Info(id: 111266, name: 'NUSHU CHARACTER-1B2A2', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2A2 = "\u{1B2A2}";

    #[Info(id: 111267, name: 'NUSHU CHARACTER-1B2A3', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2A3 = "\u{1B2A3}";

    #[Info(id: 111268, name: 'NUSHU CHARACTER-1B2A4', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2A4 = "\u{1B2A4}";

    #[Info(id: 111269, name: 'NUSHU CHARACTER-1B2A5', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2A5 = "\u{1B2A5}";

    #[Info(id: 111270, name: 'NUSHU CHARACTER-1B2A6', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2A6 = "\u{1B2A6}";

    #[Info(id: 111271, name: 'NUSHU CHARACTER-1B2A7', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2A7 = "\u{1B2A7}";

    #[Info(id: 111272, name: 'NUSHU CHARACTER-1B2A8', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2A8 = "\u{1B2A8}";

    #[Info(id: 111273, name: 'NUSHU CHARACTER-1B2A9', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2A9 = "\u{1B2A9}";

    #[Info(id: 111274, name: 'NUSHU CHARACTER-1B2AA', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2AA = "\u{1B2AA}";

    #[Info(id: 111275, name: 'NUSHU CHARACTER-1B2AB', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2AB = "\u{1B2AB}";

    #[Info(id: 111276, name: 'NUSHU CHARACTER-1B2AC', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2AC = "\u{1B2AC}";

    #[Info(id: 111277, name: 'NUSHU CHARACTER-1B2AD', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2AD = "\u{1B2AD}";

    #[Info(id: 111278, name: 'NUSHU CHARACTER-1B2AE', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2AE = "\u{1B2AE}";

    #[Info(id: 111279, name: 'NUSHU CHARACTER-1B2AF', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2AF = "\u{1B2AF}";

    #[Info(id: 111280, name: 'NUSHU CHARACTER-1B2B0', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2B0 = "\u{1B2B0}";

    #[Info(id: 111281, name: 'NUSHU CHARACTER-1B2B1', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2B1 = "\u{1B2B1}";

    #[Info(id: 111282, name: 'NUSHU CHARACTER-1B2B2', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2B2 = "\u{1B2B2}";

    #[Info(id: 111283, name: 'NUSHU CHARACTER-1B2B3', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2B3 = "\u{1B2B3}";

    #[Info(id: 111284, name: 'NUSHU CHARACTER-1B2B4', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2B4 = "\u{1B2B4}";

    #[Info(id: 111285, name: 'NUSHU CHARACTER-1B2B5', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2B5 = "\u{1B2B5}";

    #[Info(id: 111286, name: 'NUSHU CHARACTER-1B2B6', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2B6 = "\u{1B2B6}";

    #[Info(id: 111287, name: 'NUSHU CHARACTER-1B2B7', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2B7 = "\u{1B2B7}";

    #[Info(id: 111288, name: 'NUSHU CHARACTER-1B2B8', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2B8 = "\u{1B2B8}";

    #[Info(id: 111289, name: 'NUSHU CHARACTER-1B2B9', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2B9 = "\u{1B2B9}";

    #[Info(id: 111290, name: 'NUSHU CHARACTER-1B2BA', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2BA = "\u{1B2BA}";

    #[Info(id: 111291, name: 'NUSHU CHARACTER-1B2BB', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2BB = "\u{1B2BB}";

    #[Info(id: 111292, name: 'NUSHU CHARACTER-1B2BC', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2BC = "\u{1B2BC}";

    #[Info(id: 111293, name: 'NUSHU CHARACTER-1B2BD', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2BD = "\u{1B2BD}";

    #[Info(id: 111294, name: 'NUSHU CHARACTER-1B2BE', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2BE = "\u{1B2BE}";

    #[Info(id: 111295, name: 'NUSHU CHARACTER-1B2BF', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2BF = "\u{1B2BF}";

    #[Info(id: 111296, name: 'NUSHU CHARACTER-1B2C0', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2C0 = "\u{1B2C0}";

    #[Info(id: 111297, name: 'NUSHU CHARACTER-1B2C1', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2C1 = "\u{1B2C1}";

    #[Info(id: 111298, name: 'NUSHU CHARACTER-1B2C2', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2C2 = "\u{1B2C2}";

    #[Info(id: 111299, name: 'NUSHU CHARACTER-1B2C3', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2C3 = "\u{1B2C3}";

    #[Info(id: 111300, name: 'NUSHU CHARACTER-1B2C4', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2C4 = "\u{1B2C4}";

    #[Info(id: 111301, name: 'NUSHU CHARACTER-1B2C5', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2C5 = "\u{1B2C5}";

    #[Info(id: 111302, name: 'NUSHU CHARACTER-1B2C6', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2C6 = "\u{1B2C6}";

    #[Info(id: 111303, name: 'NUSHU CHARACTER-1B2C7', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2C7 = "\u{1B2C7}";

    #[Info(id: 111304, name: 'NUSHU CHARACTER-1B2C8', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2C8 = "\u{1B2C8}";

    #[Info(id: 111305, name: 'NUSHU CHARACTER-1B2C9', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2C9 = "\u{1B2C9}";

    #[Info(id: 111306, name: 'NUSHU CHARACTER-1B2CA', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2CA = "\u{1B2CA}";

    #[Info(id: 111307, name: 'NUSHU CHARACTER-1B2CB', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2CB = "\u{1B2CB}";

    #[Info(id: 111308, name: 'NUSHU CHARACTER-1B2CC', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2CC = "\u{1B2CC}";

    #[Info(id: 111309, name: 'NUSHU CHARACTER-1B2CD', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2CD = "\u{1B2CD}";

    #[Info(id: 111310, name: 'NUSHU CHARACTER-1B2CE', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2CE = "\u{1B2CE}";

    #[Info(id: 111311, name: 'NUSHU CHARACTER-1B2CF', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2CF = "\u{1B2CF}";

    #[Info(id: 111312, name: 'NUSHU CHARACTER-1B2D0', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2D0 = "\u{1B2D0}";

    #[Info(id: 111313, name: 'NUSHU CHARACTER-1B2D1', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2D1 = "\u{1B2D1}";

    #[Info(id: 111314, name: 'NUSHU CHARACTER-1B2D2', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2D2 = "\u{1B2D2}";

    #[Info(id: 111315, name: 'NUSHU CHARACTER-1B2D3', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2D3 = "\u{1B2D3}";

    #[Info(id: 111316, name: 'NUSHU CHARACTER-1B2D4', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2D4 = "\u{1B2D4}";

    #[Info(id: 111317, name: 'NUSHU CHARACTER-1B2D5', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2D5 = "\u{1B2D5}";

    #[Info(id: 111318, name: 'NUSHU CHARACTER-1B2D6', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2D6 = "\u{1B2D6}";

    #[Info(id: 111319, name: 'NUSHU CHARACTER-1B2D7', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2D7 = "\u{1B2D7}";

    #[Info(id: 111320, name: 'NUSHU CHARACTER-1B2D8', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2D8 = "\u{1B2D8}";

    #[Info(id: 111321, name: 'NUSHU CHARACTER-1B2D9', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2D9 = "\u{1B2D9}";

    #[Info(id: 111322, name: 'NUSHU CHARACTER-1B2DA', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2DA = "\u{1B2DA}";

    #[Info(id: 111323, name: 'NUSHU CHARACTER-1B2DB', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2DB = "\u{1B2DB}";

    #[Info(id: 111324, name: 'NUSHU CHARACTER-1B2DC', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2DC = "\u{1B2DC}";

    #[Info(id: 111325, name: 'NUSHU CHARACTER-1B2DD', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2DD = "\u{1B2DD}";

    #[Info(id: 111326, name: 'NUSHU CHARACTER-1B2DE', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2DE = "\u{1B2DE}";

    #[Info(id: 111327, name: 'NUSHU CHARACTER-1B2DF', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2DF = "\u{1B2DF}";

    #[Info(id: 111328, name: 'NUSHU CHARACTER-1B2E0', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2E0 = "\u{1B2E0}";

    #[Info(id: 111329, name: 'NUSHU CHARACTER-1B2E1', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2E1 = "\u{1B2E1}";

    #[Info(id: 111330, name: 'NUSHU CHARACTER-1B2E2', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2E2 = "\u{1B2E2}";

    #[Info(id: 111331, name: 'NUSHU CHARACTER-1B2E3', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2E3 = "\u{1B2E3}";

    #[Info(id: 111332, name: 'NUSHU CHARACTER-1B2E4', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2E4 = "\u{1B2E4}";

    #[Info(id: 111333, name: 'NUSHU CHARACTER-1B2E5', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2E5 = "\u{1B2E5}";

    #[Info(id: 111334, name: 'NUSHU CHARACTER-1B2E6', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2E6 = "\u{1B2E6}";

    #[Info(id: 111335, name: 'NUSHU CHARACTER-1B2E7', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2E7 = "\u{1B2E7}";

    #[Info(id: 111336, name: 'NUSHU CHARACTER-1B2E8', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2E8 = "\u{1B2E8}";

    #[Info(id: 111337, name: 'NUSHU CHARACTER-1B2E9', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2E9 = "\u{1B2E9}";

    #[Info(id: 111338, name: 'NUSHU CHARACTER-1B2EA', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2EA = "\u{1B2EA}";

    #[Info(id: 111339, name: 'NUSHU CHARACTER-1B2EB', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2EB = "\u{1B2EB}";

    #[Info(id: 111340, name: 'NUSHU CHARACTER-1B2EC', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2EC = "\u{1B2EC}";

    #[Info(id: 111341, name: 'NUSHU CHARACTER-1B2ED', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2ED = "\u{1B2ED}";

    #[Info(id: 111342, name: 'NUSHU CHARACTER-1B2EE', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2EE = "\u{1B2EE}";

    #[Info(id: 111343, name: 'NUSHU CHARACTER-1B2EF', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2EF = "\u{1B2EF}";

    #[Info(id: 111344, name: 'NUSHU CHARACTER-1B2F0', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2F0 = "\u{1B2F0}";

    #[Info(id: 111345, name: 'NUSHU CHARACTER-1B2F1', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2F1 = "\u{1B2F1}";

    #[Info(id: 111346, name: 'NUSHU CHARACTER-1B2F2', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2F2 = "\u{1B2F2}";

    #[Info(id: 111347, name: 'NUSHU CHARACTER-1B2F3', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2F3 = "\u{1B2F3}";

    #[Info(id: 111348, name: 'NUSHU CHARACTER-1B2F4', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2F4 = "\u{1B2F4}";

    #[Info(id: 111349, name: 'NUSHU CHARACTER-1B2F5', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2F5 = "\u{1B2F5}";

    #[Info(id: 111350, name: 'NUSHU CHARACTER-1B2F6', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2F6 = "\u{1B2F6}";

    #[Info(id: 111351, name: 'NUSHU CHARACTER-1B2F7', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2F7 = "\u{1B2F7}";

    #[Info(id: 111352, name: 'NUSHU CHARACTER-1B2F8', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2F8 = "\u{1B2F8}";

    #[Info(id: 111353, name: 'NUSHU CHARACTER-1B2F9', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2F9 = "\u{1B2F9}";

    #[Info(id: 111354, name: 'NUSHU CHARACTER-1B2FA', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2FA = "\u{1B2FA}";

    #[Info(id: 111355, name: 'NUSHU CHARACTER-1B2FB', category: Cat::Other_Letter)]
    case NUSHU_CHARACTER_1B2FB = "\u{1B2FB}";
}
