<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Old_Uyghur: string
{
    #[Info(id: 0x10F70, name: 'OLD UYGHUR LETTER ALEPH', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_ALEPH = "\u{10F70}";

    #[Info(id: 0x10F71, name: 'OLD UYGHUR LETTER BETH', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_BETH = "\u{10F71}";

    #[Info(id: 0x10F72, name: 'OLD UYGHUR LETTER GIMEL-HETH', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_GIMEL_HETH = "\u{10F72}";

    #[Info(id: 0x10F73, name: 'OLD UYGHUR LETTER WAW', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_WAW = "\u{10F73}";

    #[Info(id: 0x10F74, name: 'OLD UYGHUR LETTER ZAYIN', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_ZAYIN = "\u{10F74}";

    #[Info(id: 0x10F75, name: 'OLD UYGHUR LETTER FINAL HETH', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_FINAL_HETH = "\u{10F75}";

    #[Info(id: 0x10F76, name: 'OLD UYGHUR LETTER YODH', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_YODH = "\u{10F76}";

    #[Info(id: 0x10F77, name: 'OLD UYGHUR LETTER KAPH', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_KAPH = "\u{10F77}";

    #[Info(id: 0x10F78, name: 'OLD UYGHUR LETTER LAMEDH', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_LAMEDH = "\u{10F78}";

    #[Info(id: 0x10F79, name: 'OLD UYGHUR LETTER MEM', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_MEM = "\u{10F79}";

    #[Info(id: 0x10F7A, name: 'OLD UYGHUR LETTER NUN', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_NUN = "\u{10F7A}";

    #[Info(id: 0x10F7B, name: 'OLD UYGHUR LETTER SAMEKH', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_SAMEKH = "\u{10F7B}";

    #[Info(id: 0x10F7C, name: 'OLD UYGHUR LETTER PE', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_PE = "\u{10F7C}";

    #[Info(id: 0x10F7D, name: 'OLD UYGHUR LETTER SADHE', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_SADHE = "\u{10F7D}";

    #[Info(id: 0x10F7E, name: 'OLD UYGHUR LETTER RESH', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_RESH = "\u{10F7E}";

    #[Info(id: 0x10F7F, name: 'OLD UYGHUR LETTER SHIN', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_SHIN = "\u{10F7F}";

    #[Info(id: 0x10F80, name: 'OLD UYGHUR LETTER TAW', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_TAW = "\u{10F80}";

    #[Info(id: 0x10F81, name: 'OLD UYGHUR LETTER LESH', category: Cat::Other_Letter)]
    case OLD_UYGHUR_LETTER_LESH = "\u{10F81}";

    #[Info(id: 0x10F82, name: 'OLD UYGHUR COMBINING DOT ABOVE', category: Cat::Nonspacing_Mark)]
    case OLD_UYGHUR_COMBINING_DOT_ABOVE = "\u{10F82}";

    #[Info(id: 0x10F83, name: 'OLD UYGHUR COMBINING DOT BELOW', category: Cat::Nonspacing_Mark)]
    case OLD_UYGHUR_COMBINING_DOT_BELOW = "\u{10F83}";

    #[Info(id: 0x10F84, name: 'OLD UYGHUR COMBINING TWO DOTS ABOVE', category: Cat::Nonspacing_Mark)]
    case OLD_UYGHUR_COMBINING_TWO_DOTS_ABOVE = "\u{10F84}";

    #[Info(id: 0x10F85, name: 'OLD UYGHUR COMBINING TWO DOTS BELOW', category: Cat::Nonspacing_Mark)]
    case OLD_UYGHUR_COMBINING_TWO_DOTS_BELOW = "\u{10F85}";

    #[Info(id: 0x10F86, name: 'OLD UYGHUR PUNCTUATION BAR', category: Cat::Other_Punctuation)]
    case OLD_UYGHUR_PUNCTUATION_BAR = "\u{10F86}";

    #[Info(id: 0x10F87, name: 'OLD UYGHUR PUNCTUATION TWO BARS', category: Cat::Other_Punctuation)]
    case OLD_UYGHUR_PUNCTUATION_TWO_BARS = "\u{10F87}";

    #[Info(id: 0x10F88, name: 'OLD UYGHUR PUNCTUATION TWO DOTS', category: Cat::Other_Punctuation)]
    case OLD_UYGHUR_PUNCTUATION_TWO_DOTS = "\u{10F88}";

    #[Info(id: 0x10F89, name: 'OLD UYGHUR PUNCTUATION FOUR DOTS', category: Cat::Other_Punctuation)]
    case OLD_UYGHUR_PUNCTUATION_FOUR_DOTS = "\u{10F89}";
}
