<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Phagspa: string
{
    #[Info(id: 0xA840, name: 'PHAGS-PA LETTER KA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_KA = "\u{A840}";

    #[Info(id: 0xA841, name: 'PHAGS-PA LETTER KHA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_KHA = "\u{A841}";

    #[Info(id: 0xA842, name: 'PHAGS-PA LETTER GA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_GA = "\u{A842}";

    #[Info(id: 0xA843, name: 'PHAGS-PA LETTER NGA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_NGA = "\u{A843}";

    #[Info(id: 0xA844, name: 'PHAGS-PA LETTER CA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_CA = "\u{A844}";

    #[Info(id: 0xA845, name: 'PHAGS-PA LETTER CHA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_CHA = "\u{A845}";

    #[Info(id: 0xA846, name: 'PHAGS-PA LETTER JA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_JA = "\u{A846}";

    #[Info(id: 0xA847, name: 'PHAGS-PA LETTER NYA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_NYA = "\u{A847}";

    #[Info(id: 0xA848, name: 'PHAGS-PA LETTER TA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_TA = "\u{A848}";

    #[Info(id: 0xA849, name: 'PHAGS-PA LETTER THA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_THA = "\u{A849}";

    #[Info(id: 0xA84A, name: 'PHAGS-PA LETTER DA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_DA = "\u{A84A}";

    #[Info(id: 0xA84B, name: 'PHAGS-PA LETTER NA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_NA = "\u{A84B}";

    #[Info(id: 0xA84C, name: 'PHAGS-PA LETTER PA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_PA = "\u{A84C}";

    #[Info(id: 0xA84D, name: 'PHAGS-PA LETTER PHA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_PHA = "\u{A84D}";

    #[Info(id: 0xA84E, name: 'PHAGS-PA LETTER BA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_BA = "\u{A84E}";

    #[Info(id: 0xA84F, name: 'PHAGS-PA LETTER MA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_MA = "\u{A84F}";

    #[Info(id: 0xA850, name: 'PHAGS-PA LETTER TSA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_TSA = "\u{A850}";

    #[Info(id: 0xA851, name: 'PHAGS-PA LETTER TSHA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_TSHA = "\u{A851}";

    #[Info(id: 0xA852, name: 'PHAGS-PA LETTER DZA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_DZA = "\u{A852}";

    #[Info(id: 0xA853, name: 'PHAGS-PA LETTER WA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_WA = "\u{A853}";

    #[Info(id: 0xA854, name: 'PHAGS-PA LETTER ZHA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_ZHA = "\u{A854}";

    #[Info(id: 0xA855, name: 'PHAGS-PA LETTER ZA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_ZA = "\u{A855}";

    #[Info(id: 0xA856, name: 'PHAGS-PA LETTER SMALL A', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_SMALL_A = "\u{A856}";

    #[Info(id: 0xA857, name: 'PHAGS-PA LETTER YA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_YA = "\u{A857}";

    #[Info(id: 0xA858, name: 'PHAGS-PA LETTER RA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_RA = "\u{A858}";

    #[Info(id: 0xA859, name: 'PHAGS-PA LETTER LA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_LA = "\u{A859}";

    #[Info(id: 0xA85A, name: 'PHAGS-PA LETTER SHA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_SHA = "\u{A85A}";

    #[Info(id: 0xA85B, name: 'PHAGS-PA LETTER SA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_SA = "\u{A85B}";

    #[Info(id: 0xA85C, name: 'PHAGS-PA LETTER HA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_HA = "\u{A85C}";

    #[Info(id: 0xA85D, name: 'PHAGS-PA LETTER A', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_A = "\u{A85D}";

    #[Info(id: 0xA85E, name: 'PHAGS-PA LETTER I', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_I = "\u{A85E}";

    #[Info(id: 0xA85F, name: 'PHAGS-PA LETTER U', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_U = "\u{A85F}";

    #[Info(id: 0xA860, name: 'PHAGS-PA LETTER E', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_E = "\u{A860}";

    #[Info(id: 0xA861, name: 'PHAGS-PA LETTER O', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_O = "\u{A861}";

    #[Info(id: 0xA862, name: 'PHAGS-PA LETTER QA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_QA = "\u{A862}";

    #[Info(id: 0xA863, name: 'PHAGS-PA LETTER XA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_XA = "\u{A863}";

    #[Info(id: 0xA864, name: 'PHAGS-PA LETTER FA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_FA = "\u{A864}";

    #[Info(id: 0xA865, name: 'PHAGS-PA LETTER GGA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_GGA = "\u{A865}";

    #[Info(id: 0xA866, name: 'PHAGS-PA LETTER EE', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_EE = "\u{A866}";

    #[Info(id: 0xA867, name: 'PHAGS-PA SUBJOINED LETTER WA', category: Cat::Other_Letter)]
    case PHAGS_PA_SUBJOINED_LETTER_WA = "\u{A867}";

    #[Info(id: 0xA868, name: 'PHAGS-PA SUBJOINED LETTER YA', category: Cat::Other_Letter)]
    case PHAGS_PA_SUBJOINED_LETTER_YA = "\u{A868}";

    #[Info(id: 0xA869, name: 'PHAGS-PA LETTER TTA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_TTA = "\u{A869}";

    #[Info(id: 0xA86A, name: 'PHAGS-PA LETTER TTHA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_TTHA = "\u{A86A}";

    #[Info(id: 0xA86B, name: 'PHAGS-PA LETTER DDA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_DDA = "\u{A86B}";

    #[Info(id: 0xA86C, name: 'PHAGS-PA LETTER NNA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_NNA = "\u{A86C}";

    #[Info(id: 0xA86D, name: 'PHAGS-PA LETTER ALTERNATE YA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_ALTERNATE_YA = "\u{A86D}";

    #[Info(id: 0xA86E, name: 'PHAGS-PA LETTER VOICELESS SHA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_VOICELESS_SHA = "\u{A86E}";

    #[Info(id: 0xA86F, name: 'PHAGS-PA LETTER VOICED HA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_VOICED_HA = "\u{A86F}";

    #[Info(id: 0xA870, name: 'PHAGS-PA LETTER ASPIRATED FA', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_ASPIRATED_FA = "\u{A870}";

    #[Info(id: 0xA871, name: 'PHAGS-PA SUBJOINED LETTER RA', category: Cat::Other_Letter)]
    case PHAGS_PA_SUBJOINED_LETTER_RA = "\u{A871}";

    #[Info(id: 0xA872, name: 'PHAGS-PA SUPERFIXED LETTER RA', category: Cat::Other_Letter)]
    case PHAGS_PA_SUPERFIXED_LETTER_RA = "\u{A872}";

    #[Info(id: 0xA873, name: 'PHAGS-PA LETTER CANDRABINDU', category: Cat::Other_Letter)]
    case PHAGS_PA_LETTER_CANDRABINDU = "\u{A873}";

    #[Info(id: 0xA874, name: 'PHAGS-PA SINGLE HEAD MARK', category: Cat::Other_Punctuation)]
    case PHAGS_PA_SINGLE_HEAD_MARK = "\u{A874}";

    #[Info(id: 0xA875, name: 'PHAGS-PA DOUBLE HEAD MARK', category: Cat::Other_Punctuation)]
    case PHAGS_PA_DOUBLE_HEAD_MARK = "\u{A875}";

    #[Info(id: 0xA876, name: 'PHAGS-PA MARK SHAD', category: Cat::Other_Punctuation)]
    case PHAGS_PA_MARK_SHAD = "\u{A876}";

    #[Info(id: 0xA877, name: 'PHAGS-PA MARK DOUBLE SHAD', category: Cat::Other_Punctuation)]
    case PHAGS_PA_MARK_DOUBLE_SHAD = "\u{A877}";
}
