<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Runic: string
{
    #[Info(id: 0x16A0, name: 'RUNIC LETTER FEHU FEOH FE F', category: Cat::Other_Letter)]
    case RUNIC_LETTER_FEHU_FEOH_FE_F = "\u{16A0}";

    #[Info(id: 0x16A1, name: 'RUNIC LETTER V', category: Cat::Other_Letter)]
    case RUNIC_LETTER_V = "\u{16A1}";

    #[Info(id: 0x16A2, name: 'RUNIC LETTER URUZ UR U', category: Cat::Other_Letter)]
    case RUNIC_LETTER_URUZ_UR_U = "\u{16A2}";

    #[Info(id: 0x16A3, name: 'RUNIC LETTER YR', category: Cat::Other_Letter)]
    case RUNIC_LETTER_YR = "\u{16A3}";

    #[Info(id: 0x16A4, name: 'RUNIC LETTER Y', category: Cat::Other_Letter)]
    case RUNIC_LETTER_Y = "\u{16A4}";

    #[Info(id: 0x16A5, name: 'RUNIC LETTER W', category: Cat::Other_Letter)]
    case RUNIC_LETTER_W = "\u{16A5}";

    #[Info(id: 0x16A6, name: 'RUNIC LETTER THURISAZ THURS THORN', category: Cat::Other_Letter)]
    case RUNIC_LETTER_THURISAZ_THURS_THORN = "\u{16A6}";

    #[Info(id: 0x16A7, name: 'RUNIC LETTER ETH', category: Cat::Other_Letter)]
    case RUNIC_LETTER_ETH = "\u{16A7}";

    #[Info(id: 0x16A8, name: 'RUNIC LETTER ANSUZ A', category: Cat::Other_Letter)]
    case RUNIC_LETTER_ANSUZ_A = "\u{16A8}";

    #[Info(id: 0x16A9, name: 'RUNIC LETTER OS O', category: Cat::Other_Letter)]
    case RUNIC_LETTER_OS_O = "\u{16A9}";

    #[Info(id: 0x16AA, name: 'RUNIC LETTER AC A', category: Cat::Other_Letter)]
    case RUNIC_LETTER_AC_A = "\u{16AA}";

    #[Info(id: 0x16AB, name: 'RUNIC LETTER AESC', category: Cat::Other_Letter)]
    case RUNIC_LETTER_AESC = "\u{16AB}";

    #[Info(id: 0x16AC, name: 'RUNIC LETTER LONG-BRANCH-OSS O', category: Cat::Other_Letter)]
    case RUNIC_LETTER_LONG_BRANCH_OSS_O = "\u{16AC}";

    #[Info(id: 0x16AD, name: 'RUNIC LETTER SHORT-TWIG-OSS O', category: Cat::Other_Letter)]
    case RUNIC_LETTER_SHORT_TWIG_OSS_O = "\u{16AD}";

    #[Info(id: 0x16AE, name: 'RUNIC LETTER O', category: Cat::Other_Letter)]
    case RUNIC_LETTER_O = "\u{16AE}";

    #[Info(id: 0x16AF, name: 'RUNIC LETTER OE', category: Cat::Other_Letter)]
    case RUNIC_LETTER_OE = "\u{16AF}";

    #[Info(id: 0x16B0, name: 'RUNIC LETTER ON', category: Cat::Other_Letter)]
    case RUNIC_LETTER_ON = "\u{16B0}";

    #[Info(id: 0x16B1, name: 'RUNIC LETTER RAIDO RAD REID R', category: Cat::Other_Letter)]
    case RUNIC_LETTER_RAIDO_RAD_REID_R = "\u{16B1}";

    #[Info(id: 0x16B2, name: 'RUNIC LETTER KAUNA', category: Cat::Other_Letter)]
    case RUNIC_LETTER_KAUNA = "\u{16B2}";

    #[Info(id: 0x16B3, name: 'RUNIC LETTER CEN', category: Cat::Other_Letter)]
    case RUNIC_LETTER_CEN = "\u{16B3}";

    #[Info(id: 0x16B4, name: 'RUNIC LETTER KAUN K', category: Cat::Other_Letter)]
    case RUNIC_LETTER_KAUN_K = "\u{16B4}";

    #[Info(id: 0x16B5, name: 'RUNIC LETTER G', category: Cat::Other_Letter)]
    case RUNIC_LETTER_G = "\u{16B5}";

    #[Info(id: 0x16B6, name: 'RUNIC LETTER ENG', category: Cat::Other_Letter)]
    case RUNIC_LETTER_ENG = "\u{16B6}";

    #[Info(id: 0x16B7, name: 'RUNIC LETTER GEBO GYFU G', category: Cat::Other_Letter)]
    case RUNIC_LETTER_GEBO_GYFU_G = "\u{16B7}";

    #[Info(id: 0x16B8, name: 'RUNIC LETTER GAR', category: Cat::Other_Letter)]
    case RUNIC_LETTER_GAR = "\u{16B8}";

    #[Info(id: 0x16B9, name: 'RUNIC LETTER WUNJO WYNN W', category: Cat::Other_Letter)]
    case RUNIC_LETTER_WUNJO_WYNN_W = "\u{16B9}";

    #[Info(id: 0x16BA, name: 'RUNIC LETTER HAGLAZ H', category: Cat::Other_Letter)]
    case RUNIC_LETTER_HAGLAZ_H = "\u{16BA}";

    #[Info(id: 0x16BB, name: 'RUNIC LETTER HAEGL H', category: Cat::Other_Letter)]
    case RUNIC_LETTER_HAEGL_H = "\u{16BB}";

    #[Info(id: 0x16BC, name: 'RUNIC LETTER LONG-BRANCH-HAGALL H', category: Cat::Other_Letter)]
    case RUNIC_LETTER_LONG_BRANCH_HAGALL_H = "\u{16BC}";

    #[Info(id: 0x16BD, name: 'RUNIC LETTER SHORT-TWIG-HAGALL H', category: Cat::Other_Letter)]
    case RUNIC_LETTER_SHORT_TWIG_HAGALL_H = "\u{16BD}";

    #[Info(id: 0x16BE, name: 'RUNIC LETTER NAUDIZ NYD NAUD N', category: Cat::Other_Letter)]
    case RUNIC_LETTER_NAUDIZ_NYD_NAUD_N = "\u{16BE}";

    #[Info(id: 0x16BF, name: 'RUNIC LETTER SHORT-TWIG-NAUD N', category: Cat::Other_Letter)]
    case RUNIC_LETTER_SHORT_TWIG_NAUD_N = "\u{16BF}";

    #[Info(id: 0x16C0, name: 'RUNIC LETTER DOTTED-N', category: Cat::Other_Letter)]
    case RUNIC_LETTER_DOTTED_N = "\u{16C0}";

    #[Info(id: 0x16C1, name: 'RUNIC LETTER ISAZ IS ISS I', category: Cat::Other_Letter)]
    case RUNIC_LETTER_ISAZ_IS_ISS_I = "\u{16C1}";

    #[Info(id: 0x16C2, name: 'RUNIC LETTER E', category: Cat::Other_Letter)]
    case RUNIC_LETTER_E = "\u{16C2}";

    #[Info(id: 0x16C3, name: 'RUNIC LETTER JERAN J', category: Cat::Other_Letter)]
    case RUNIC_LETTER_JERAN_J = "\u{16C3}";

    #[Info(id: 0x16C4, name: 'RUNIC LETTER GER', category: Cat::Other_Letter)]
    case RUNIC_LETTER_GER = "\u{16C4}";

    #[Info(id: 0x16C5, name: 'RUNIC LETTER LONG-BRANCH-AR AE', category: Cat::Other_Letter)]
    case RUNIC_LETTER_LONG_BRANCH_AR_AE = "\u{16C5}";

    #[Info(id: 0x16C6, name: 'RUNIC LETTER SHORT-TWIG-AR A', category: Cat::Other_Letter)]
    case RUNIC_LETTER_SHORT_TWIG_AR_A = "\u{16C6}";

    #[Info(id: 0x16C7, name: 'RUNIC LETTER IWAZ EOH', category: Cat::Other_Letter)]
    case RUNIC_LETTER_IWAZ_EOH = "\u{16C7}";

    #[Info(id: 0x16C8, name: 'RUNIC LETTER PERTHO PEORTH P', category: Cat::Other_Letter)]
    case RUNIC_LETTER_PERTHO_PEORTH_P = "\u{16C8}";

    #[Info(id: 0x16C9, name: 'RUNIC LETTER ALGIZ EOLHX', category: Cat::Other_Letter)]
    case RUNIC_LETTER_ALGIZ_EOLHX = "\u{16C9}";

    #[Info(id: 0x16CA, name: 'RUNIC LETTER SOWILO S', category: Cat::Other_Letter)]
    case RUNIC_LETTER_SOWILO_S = "\u{16CA}";

    #[Info(id: 0x16CB, name: 'RUNIC LETTER SIGEL LONG-BRANCH-SOL S', category: Cat::Other_Letter)]
    case RUNIC_LETTER_SIGEL_LONG_BRANCH_SOL_S = "\u{16CB}";

    #[Info(id: 0x16CC, name: 'RUNIC LETTER SHORT-TWIG-SOL S', category: Cat::Other_Letter)]
    case RUNIC_LETTER_SHORT_TWIG_SOL_S = "\u{16CC}";

    #[Info(id: 0x16CD, name: 'RUNIC LETTER C', category: Cat::Other_Letter)]
    case RUNIC_LETTER_C = "\u{16CD}";

    #[Info(id: 0x16CE, name: 'RUNIC LETTER Z', category: Cat::Other_Letter)]
    case RUNIC_LETTER_Z = "\u{16CE}";

    #[Info(id: 0x16CF, name: 'RUNIC LETTER TIWAZ TIR TYR T', category: Cat::Other_Letter)]
    case RUNIC_LETTER_TIWAZ_TIR_TYR_T = "\u{16CF}";

    #[Info(id: 0x16D0, name: 'RUNIC LETTER SHORT-TWIG-TYR T', category: Cat::Other_Letter)]
    case RUNIC_LETTER_SHORT_TWIG_TYR_T = "\u{16D0}";

    #[Info(id: 0x16D1, name: 'RUNIC LETTER D', category: Cat::Other_Letter)]
    case RUNIC_LETTER_D = "\u{16D1}";

    #[Info(id: 0x16D2, name: 'RUNIC LETTER BERKANAN BEORC BJARKAN B', category: Cat::Other_Letter)]
    case RUNIC_LETTER_BERKANAN_BEORC_BJARKAN_B = "\u{16D2}";

    #[Info(id: 0x16D3, name: 'RUNIC LETTER SHORT-TWIG-BJARKAN B', category: Cat::Other_Letter)]
    case RUNIC_LETTER_SHORT_TWIG_BJARKAN_B = "\u{16D3}";

    #[Info(id: 0x16D4, name: 'RUNIC LETTER DOTTED-P', category: Cat::Other_Letter)]
    case RUNIC_LETTER_DOTTED_P = "\u{16D4}";

    #[Info(id: 0x16D5, name: 'RUNIC LETTER OPEN-P', category: Cat::Other_Letter)]
    case RUNIC_LETTER_OPEN_P = "\u{16D5}";

    #[Info(id: 0x16D6, name: 'RUNIC LETTER EHWAZ EH E', category: Cat::Other_Letter)]
    case RUNIC_LETTER_EHWAZ_EH_E = "\u{16D6}";

    #[Info(id: 0x16D7, name: 'RUNIC LETTER MANNAZ MAN M', category: Cat::Other_Letter)]
    case RUNIC_LETTER_MANNAZ_MAN_M = "\u{16D7}";

    #[Info(id: 0x16D8, name: 'RUNIC LETTER LONG-BRANCH-MADR M', category: Cat::Other_Letter)]
    case RUNIC_LETTER_LONG_BRANCH_MADR_M = "\u{16D8}";

    #[Info(id: 0x16D9, name: 'RUNIC LETTER SHORT-TWIG-MADR M', category: Cat::Other_Letter)]
    case RUNIC_LETTER_SHORT_TWIG_MADR_M = "\u{16D9}";

    #[Info(id: 0x16DA, name: 'RUNIC LETTER LAUKAZ LAGU LOGR L', category: Cat::Other_Letter)]
    case RUNIC_LETTER_LAUKAZ_LAGU_LOGR_L = "\u{16DA}";

    #[Info(id: 0x16DB, name: 'RUNIC LETTER DOTTED-L', category: Cat::Other_Letter)]
    case RUNIC_LETTER_DOTTED_L = "\u{16DB}";

    #[Info(id: 0x16DC, name: 'RUNIC LETTER INGWAZ', category: Cat::Other_Letter)]
    case RUNIC_LETTER_INGWAZ = "\u{16DC}";

    #[Info(id: 0x16DD, name: 'RUNIC LETTER ING', category: Cat::Other_Letter)]
    case RUNIC_LETTER_ING = "\u{16DD}";

    #[Info(id: 0x16DE, name: 'RUNIC LETTER DAGAZ DAEG D', category: Cat::Other_Letter)]
    case RUNIC_LETTER_DAGAZ_DAEG_D = "\u{16DE}";

    #[Info(id: 0x16DF, name: 'RUNIC LETTER OTHALAN ETHEL O', category: Cat::Other_Letter)]
    case RUNIC_LETTER_OTHALAN_ETHEL_O = "\u{16DF}";

    #[Info(id: 0x16E0, name: 'RUNIC LETTER EAR', category: Cat::Other_Letter)]
    case RUNIC_LETTER_EAR = "\u{16E0}";

    #[Info(id: 0x16E1, name: 'RUNIC LETTER IOR', category: Cat::Other_Letter)]
    case RUNIC_LETTER_IOR = "\u{16E1}";

    #[Info(id: 0x16E2, name: 'RUNIC LETTER CWEORTH', category: Cat::Other_Letter)]
    case RUNIC_LETTER_CWEORTH = "\u{16E2}";

    #[Info(id: 0x16E3, name: 'RUNIC LETTER CALC', category: Cat::Other_Letter)]
    case RUNIC_LETTER_CALC = "\u{16E3}";

    #[Info(id: 0x16E4, name: 'RUNIC LETTER CEALC', category: Cat::Other_Letter)]
    case RUNIC_LETTER_CEALC = "\u{16E4}";

    #[Info(id: 0x16E5, name: 'RUNIC LETTER STAN', category: Cat::Other_Letter)]
    case RUNIC_LETTER_STAN = "\u{16E5}";

    #[Info(id: 0x16E6, name: 'RUNIC LETTER LONG-BRANCH-YR', category: Cat::Other_Letter)]
    case RUNIC_LETTER_LONG_BRANCH_YR = "\u{16E6}";

    #[Info(id: 0x16E7, name: 'RUNIC LETTER SHORT-TWIG-YR', category: Cat::Other_Letter)]
    case RUNIC_LETTER_SHORT_TWIG_YR = "\u{16E7}";

    #[Info(id: 0x16E8, name: 'RUNIC LETTER ICELANDIC-YR', category: Cat::Other_Letter)]
    case RUNIC_LETTER_ICELANDIC_YR = "\u{16E8}";

    #[Info(id: 0x16E9, name: 'RUNIC LETTER Q', category: Cat::Other_Letter)]
    case RUNIC_LETTER_Q = "\u{16E9}";

    #[Info(id: 0x16EA, name: 'RUNIC LETTER X', category: Cat::Other_Letter)]
    case RUNIC_LETTER_X = "\u{16EA}";

    #[Info(id: 0x16EB, name: 'RUNIC SINGLE PUNCTUATION', category: Cat::Other_Punctuation)]
    case RUNIC_SINGLE_PUNCTUATION = "\u{16EB}";

    #[Info(id: 0x16EC, name: 'RUNIC MULTIPLE PUNCTUATION', category: Cat::Other_Punctuation)]
    case RUNIC_MULTIPLE_PUNCTUATION = "\u{16EC}";

    #[Info(id: 0x16ED, name: 'RUNIC CROSS PUNCTUATION', category: Cat::Other_Punctuation)]
    case RUNIC_CROSS_PUNCTUATION = "\u{16ED}";

    #[Info(id: 0x16EE, name: 'RUNIC ARLAUG SYMBOL', category: Cat::Letter_Number)]
    case RUNIC_ARLAUG_SYMBOL = "\u{16EE}";

    #[Info(id: 0x16EF, name: 'RUNIC TVIMADUR SYMBOL', category: Cat::Letter_Number)]
    case RUNIC_TVIMADUR_SYMBOL = "\u{16EF}";

    #[Info(id: 0x16F0, name: 'RUNIC BELGTHOR SYMBOL', category: Cat::Letter_Number)]
    case RUNIC_BELGTHOR_SYMBOL = "\u{16F0}";

    #[Info(id: 0x16F1, name: 'RUNIC LETTER K', category: Cat::Other_Letter)]
    case RUNIC_LETTER_K = "\u{16F1}";

    #[Info(id: 0x16F2, name: 'RUNIC LETTER SH', category: Cat::Other_Letter)]
    case RUNIC_LETTER_SH = "\u{16F2}";

    #[Info(id: 0x16F3, name: 'RUNIC LETTER OO', category: Cat::Other_Letter)]
    case RUNIC_LETTER_OO = "\u{16F3}";

    #[Info(id: 0x16F4, name: 'RUNIC LETTER FRANKS CASKET OS', category: Cat::Other_Letter)]
    case RUNIC_LETTER_FRANKS_CASKET_OS = "\u{16F4}";

    #[Info(id: 0x16F5, name: 'RUNIC LETTER FRANKS CASKET IS', category: Cat::Other_Letter)]
    case RUNIC_LETTER_FRANKS_CASKET_IS = "\u{16F5}";

    #[Info(id: 0x16F6, name: 'RUNIC LETTER FRANKS CASKET EH', category: Cat::Other_Letter)]
    case RUNIC_LETTER_FRANKS_CASKET_EH = "\u{16F6}";

    #[Info(id: 0x16F7, name: 'RUNIC LETTER FRANKS CASKET AC', category: Cat::Other_Letter)]
    case RUNIC_LETTER_FRANKS_CASKET_AC = "\u{16F7}";

    #[Info(id: 0x16F8, name: 'RUNIC LETTER FRANKS CASKET AESC', category: Cat::Other_Letter)]
    case RUNIC_LETTER_FRANKS_CASKET_AESC = "\u{16F8}";
}
