<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Saurashtra: string
{
    #[Info(id: 0xA880, name: 'SAURASHTRA SIGN ANUSVARA', category: Cat::Spacing_Mark)]
    case SAURASHTRA_SIGN_ANUSVARA = "\u{A880}";

    #[Info(id: 0xA881, name: 'SAURASHTRA SIGN VISARGA', category: Cat::Spacing_Mark)]
    case SAURASHTRA_SIGN_VISARGA = "\u{A881}";

    #[Info(id: 0xA882, name: 'SAURASHTRA LETTER A', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_A = "\u{A882}";

    #[Info(id: 0xA883, name: 'SAURASHTRA LETTER AA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_AA = "\u{A883}";

    #[Info(id: 0xA884, name: 'SAURASHTRA LETTER I', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_I = "\u{A884}";

    #[Info(id: 0xA885, name: 'SAURASHTRA LETTER II', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_II = "\u{A885}";

    #[Info(id: 0xA886, name: 'SAURASHTRA LETTER U', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_U = "\u{A886}";

    #[Info(id: 0xA887, name: 'SAURASHTRA LETTER UU', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_UU = "\u{A887}";

    #[Info(id: 0xA888, name: 'SAURASHTRA LETTER VOCALIC R', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_VOCALIC_R = "\u{A888}";

    #[Info(id: 0xA889, name: 'SAURASHTRA LETTER VOCALIC RR', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_VOCALIC_RR = "\u{A889}";

    #[Info(id: 0xA88A, name: 'SAURASHTRA LETTER VOCALIC L', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_VOCALIC_L = "\u{A88A}";

    #[Info(id: 0xA88B, name: 'SAURASHTRA LETTER VOCALIC LL', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_VOCALIC_LL = "\u{A88B}";

    #[Info(id: 0xA88C, name: 'SAURASHTRA LETTER E', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_E = "\u{A88C}";

    #[Info(id: 0xA88D, name: 'SAURASHTRA LETTER EE', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_EE = "\u{A88D}";

    #[Info(id: 0xA88E, name: 'SAURASHTRA LETTER AI', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_AI = "\u{A88E}";

    #[Info(id: 0xA88F, name: 'SAURASHTRA LETTER O', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_O = "\u{A88F}";

    #[Info(id: 0xA890, name: 'SAURASHTRA LETTER OO', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_OO = "\u{A890}";

    #[Info(id: 0xA891, name: 'SAURASHTRA LETTER AU', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_AU = "\u{A891}";

    #[Info(id: 0xA892, name: 'SAURASHTRA LETTER KA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_KA = "\u{A892}";

    #[Info(id: 0xA893, name: 'SAURASHTRA LETTER KHA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_KHA = "\u{A893}";

    #[Info(id: 0xA894, name: 'SAURASHTRA LETTER GA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_GA = "\u{A894}";

    #[Info(id: 0xA895, name: 'SAURASHTRA LETTER GHA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_GHA = "\u{A895}";

    #[Info(id: 0xA896, name: 'SAURASHTRA LETTER NGA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_NGA = "\u{A896}";

    #[Info(id: 0xA897, name: 'SAURASHTRA LETTER CA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_CA = "\u{A897}";

    #[Info(id: 0xA898, name: 'SAURASHTRA LETTER CHA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_CHA = "\u{A898}";

    #[Info(id: 0xA899, name: 'SAURASHTRA LETTER JA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_JA = "\u{A899}";

    #[Info(id: 0xA89A, name: 'SAURASHTRA LETTER JHA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_JHA = "\u{A89A}";

    #[Info(id: 0xA89B, name: 'SAURASHTRA LETTER NYA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_NYA = "\u{A89B}";

    #[Info(id: 0xA89C, name: 'SAURASHTRA LETTER TTA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_TTA = "\u{A89C}";

    #[Info(id: 0xA89D, name: 'SAURASHTRA LETTER TTHA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_TTHA = "\u{A89D}";

    #[Info(id: 0xA89E, name: 'SAURASHTRA LETTER DDA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_DDA = "\u{A89E}";

    #[Info(id: 0xA89F, name: 'SAURASHTRA LETTER DDHA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_DDHA = "\u{A89F}";

    #[Info(id: 0xA8A0, name: 'SAURASHTRA LETTER NNA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_NNA = "\u{A8A0}";

    #[Info(id: 0xA8A1, name: 'SAURASHTRA LETTER TA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_TA = "\u{A8A1}";

    #[Info(id: 0xA8A2, name: 'SAURASHTRA LETTER THA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_THA = "\u{A8A2}";

    #[Info(id: 0xA8A3, name: 'SAURASHTRA LETTER DA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_DA = "\u{A8A3}";

    #[Info(id: 0xA8A4, name: 'SAURASHTRA LETTER DHA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_DHA = "\u{A8A4}";

    #[Info(id: 0xA8A5, name: 'SAURASHTRA LETTER NA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_NA = "\u{A8A5}";

    #[Info(id: 0xA8A6, name: 'SAURASHTRA LETTER PA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_PA = "\u{A8A6}";

    #[Info(id: 0xA8A7, name: 'SAURASHTRA LETTER PHA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_PHA = "\u{A8A7}";

    #[Info(id: 0xA8A8, name: 'SAURASHTRA LETTER BA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_BA = "\u{A8A8}";

    #[Info(id: 0xA8A9, name: 'SAURASHTRA LETTER BHA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_BHA = "\u{A8A9}";

    #[Info(id: 0xA8AA, name: 'SAURASHTRA LETTER MA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_MA = "\u{A8AA}";

    #[Info(id: 0xA8AB, name: 'SAURASHTRA LETTER YA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_YA = "\u{A8AB}";

    #[Info(id: 0xA8AC, name: 'SAURASHTRA LETTER RA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_RA = "\u{A8AC}";

    #[Info(id: 0xA8AD, name: 'SAURASHTRA LETTER LA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_LA = "\u{A8AD}";

    #[Info(id: 0xA8AE, name: 'SAURASHTRA LETTER VA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_VA = "\u{A8AE}";

    #[Info(id: 0xA8AF, name: 'SAURASHTRA LETTER SHA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_SHA = "\u{A8AF}";

    #[Info(id: 0xA8B0, name: 'SAURASHTRA LETTER SSA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_SSA = "\u{A8B0}";

    #[Info(id: 0xA8B1, name: 'SAURASHTRA LETTER SA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_SA = "\u{A8B1}";

    #[Info(id: 0xA8B2, name: 'SAURASHTRA LETTER HA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_HA = "\u{A8B2}";

    #[Info(id: 0xA8B3, name: 'SAURASHTRA LETTER LLA', category: Cat::Other_Letter)]
    case SAURASHTRA_LETTER_LLA = "\u{A8B3}";

    #[Info(id: 0xA8B4, name: 'SAURASHTRA CONSONANT SIGN HAARU', category: Cat::Spacing_Mark)]
    case SAURASHTRA_CONSONANT_SIGN_HAARU = "\u{A8B4}";

    #[Info(id: 0xA8B5, name: 'SAURASHTRA VOWEL SIGN AA', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_AA = "\u{A8B5}";

    #[Info(id: 0xA8B6, name: 'SAURASHTRA VOWEL SIGN I', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_I = "\u{A8B6}";

    #[Info(id: 0xA8B7, name: 'SAURASHTRA VOWEL SIGN II', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_II = "\u{A8B7}";

    #[Info(id: 0xA8B8, name: 'SAURASHTRA VOWEL SIGN U', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_U = "\u{A8B8}";

    #[Info(id: 0xA8B9, name: 'SAURASHTRA VOWEL SIGN UU', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_UU = "\u{A8B9}";

    #[Info(id: 0xA8BA, name: 'SAURASHTRA VOWEL SIGN VOCALIC R', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_VOCALIC_R = "\u{A8BA}";

    #[Info(id: 0xA8BB, name: 'SAURASHTRA VOWEL SIGN VOCALIC RR', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_VOCALIC_RR = "\u{A8BB}";

    #[Info(id: 0xA8BC, name: 'SAURASHTRA VOWEL SIGN VOCALIC L', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_VOCALIC_L = "\u{A8BC}";

    #[Info(id: 0xA8BD, name: 'SAURASHTRA VOWEL SIGN VOCALIC LL', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_VOCALIC_LL = "\u{A8BD}";

    #[Info(id: 0xA8BE, name: 'SAURASHTRA VOWEL SIGN E', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_E = "\u{A8BE}";

    #[Info(id: 0xA8BF, name: 'SAURASHTRA VOWEL SIGN EE', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_EE = "\u{A8BF}";

    #[Info(id: 0xA8C0, name: 'SAURASHTRA VOWEL SIGN AI', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_AI = "\u{A8C0}";

    #[Info(id: 0xA8C1, name: 'SAURASHTRA VOWEL SIGN O', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_O = "\u{A8C1}";

    #[Info(id: 0xA8C2, name: 'SAURASHTRA VOWEL SIGN OO', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_OO = "\u{A8C2}";

    #[Info(id: 0xA8C3, name: 'SAURASHTRA VOWEL SIGN AU', category: Cat::Spacing_Mark)]
    case SAURASHTRA_VOWEL_SIGN_AU = "\u{A8C3}";

    #[Info(id: 0xA8C4, name: 'SAURASHTRA SIGN VIRAMA', category: Cat::Nonspacing_Mark)]
    case SAURASHTRA_SIGN_VIRAMA = "\u{A8C4}";

    #[Info(id: 0xA8C5, name: 'SAURASHTRA SIGN CANDRABINDU', category: Cat::Nonspacing_Mark)]
    case SAURASHTRA_SIGN_CANDRABINDU = "\u{A8C5}";

    #[Info(id: 0xA8CE, name: 'SAURASHTRA DANDA', category: Cat::Other_Punctuation)]
    case SAURASHTRA_DANDA = "\u{A8CE}";

    #[Info(id: 0xA8CF, name: 'SAURASHTRA DOUBLE DANDA', category: Cat::Other_Punctuation)]
    case SAURASHTRA_DOUBLE_DANDA = "\u{A8CF}";

    #[Info(id: 0xA8D0, name: 'SAURASHTRA DIGIT ZERO', category: Cat::Decimal_Number)]
    case SAURASHTRA_DIGIT_ZERO = "\u{A8D0}";

    #[Info(id: 0xA8D1, name: 'SAURASHTRA DIGIT ONE', category: Cat::Decimal_Number)]
    case SAURASHTRA_DIGIT_ONE = "\u{A8D1}";

    #[Info(id: 0xA8D2, name: 'SAURASHTRA DIGIT TWO', category: Cat::Decimal_Number)]
    case SAURASHTRA_DIGIT_TWO = "\u{A8D2}";

    #[Info(id: 0xA8D3, name: 'SAURASHTRA DIGIT THREE', category: Cat::Decimal_Number)]
    case SAURASHTRA_DIGIT_THREE = "\u{A8D3}";

    #[Info(id: 0xA8D4, name: 'SAURASHTRA DIGIT FOUR', category: Cat::Decimal_Number)]
    case SAURASHTRA_DIGIT_FOUR = "\u{A8D4}";

    #[Info(id: 0xA8D5, name: 'SAURASHTRA DIGIT FIVE', category: Cat::Decimal_Number)]
    case SAURASHTRA_DIGIT_FIVE = "\u{A8D5}";

    #[Info(id: 0xA8D6, name: 'SAURASHTRA DIGIT SIX', category: Cat::Decimal_Number)]
    case SAURASHTRA_DIGIT_SIX = "\u{A8D6}";

    #[Info(id: 0xA8D7, name: 'SAURASHTRA DIGIT SEVEN', category: Cat::Decimal_Number)]
    case SAURASHTRA_DIGIT_SEVEN = "\u{A8D7}";

    #[Info(id: 0xA8D8, name: 'SAURASHTRA DIGIT EIGHT', category: Cat::Decimal_Number)]
    case SAURASHTRA_DIGIT_EIGHT = "\u{A8D8}";

    #[Info(id: 0xA8D9, name: 'SAURASHTRA DIGIT NINE', category: Cat::Decimal_Number)]
    case SAURASHTRA_DIGIT_NINE = "\u{A8D9}";
}
