<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Siddham: string
{
    #[Info(id: 71040, name: 'SIDDHAM LETTER A', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_A = "\u{11580}";

    #[Info(id: 71041, name: 'SIDDHAM LETTER AA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_AA = "\u{11581}";

    #[Info(id: 71042, name: 'SIDDHAM LETTER I', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_I = "\u{11582}";

    #[Info(id: 71043, name: 'SIDDHAM LETTER II', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_II = "\u{11583}";

    #[Info(id: 71044, name: 'SIDDHAM LETTER U', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_U = "\u{11584}";

    #[Info(id: 71045, name: 'SIDDHAM LETTER UU', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_UU = "\u{11585}";

    #[Info(id: 71046, name: 'SIDDHAM LETTER VOCALIC R', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_VOCALIC_R = "\u{11586}";

    #[Info(id: 71047, name: 'SIDDHAM LETTER VOCALIC RR', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_VOCALIC_RR = "\u{11587}";

    #[Info(id: 71048, name: 'SIDDHAM LETTER VOCALIC L', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_VOCALIC_L = "\u{11588}";

    #[Info(id: 71049, name: 'SIDDHAM LETTER VOCALIC LL', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_VOCALIC_LL = "\u{11589}";

    #[Info(id: 71050, name: 'SIDDHAM LETTER E', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_E = "\u{1158A}";

    #[Info(id: 71051, name: 'SIDDHAM LETTER AI', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_AI = "\u{1158B}";

    #[Info(id: 71052, name: 'SIDDHAM LETTER O', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_O = "\u{1158C}";

    #[Info(id: 71053, name: 'SIDDHAM LETTER AU', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_AU = "\u{1158D}";

    #[Info(id: 71054, name: 'SIDDHAM LETTER KA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_KA = "\u{1158E}";

    #[Info(id: 71055, name: 'SIDDHAM LETTER KHA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_KHA = "\u{1158F}";

    #[Info(id: 71056, name: 'SIDDHAM LETTER GA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_GA = "\u{11590}";

    #[Info(id: 71057, name: 'SIDDHAM LETTER GHA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_GHA = "\u{11591}";

    #[Info(id: 71058, name: 'SIDDHAM LETTER NGA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_NGA = "\u{11592}";

    #[Info(id: 71059, name: 'SIDDHAM LETTER CA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_CA = "\u{11593}";

    #[Info(id: 71060, name: 'SIDDHAM LETTER CHA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_CHA = "\u{11594}";

    #[Info(id: 71061, name: 'SIDDHAM LETTER JA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_JA = "\u{11595}";

    #[Info(id: 71062, name: 'SIDDHAM LETTER JHA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_JHA = "\u{11596}";

    #[Info(id: 71063, name: 'SIDDHAM LETTER NYA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_NYA = "\u{11597}";

    #[Info(id: 71064, name: 'SIDDHAM LETTER TTA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_TTA = "\u{11598}";

    #[Info(id: 71065, name: 'SIDDHAM LETTER TTHA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_TTHA = "\u{11599}";

    #[Info(id: 71066, name: 'SIDDHAM LETTER DDA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_DDA = "\u{1159A}";

    #[Info(id: 71067, name: 'SIDDHAM LETTER DDHA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_DDHA = "\u{1159B}";

    #[Info(id: 71068, name: 'SIDDHAM LETTER NNA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_NNA = "\u{1159C}";

    #[Info(id: 71069, name: 'SIDDHAM LETTER TA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_TA = "\u{1159D}";

    #[Info(id: 71070, name: 'SIDDHAM LETTER THA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_THA = "\u{1159E}";

    #[Info(id: 71071, name: 'SIDDHAM LETTER DA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_DA = "\u{1159F}";

    #[Info(id: 71072, name: 'SIDDHAM LETTER DHA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_DHA = "\u{115A0}";

    #[Info(id: 71073, name: 'SIDDHAM LETTER NA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_NA = "\u{115A1}";

    #[Info(id: 71074, name: 'SIDDHAM LETTER PA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_PA = "\u{115A2}";

    #[Info(id: 71075, name: 'SIDDHAM LETTER PHA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_PHA = "\u{115A3}";

    #[Info(id: 71076, name: 'SIDDHAM LETTER BA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_BA = "\u{115A4}";

    #[Info(id: 71077, name: 'SIDDHAM LETTER BHA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_BHA = "\u{115A5}";

    #[Info(id: 71078, name: 'SIDDHAM LETTER MA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_MA = "\u{115A6}";

    #[Info(id: 71079, name: 'SIDDHAM LETTER YA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_YA = "\u{115A7}";

    #[Info(id: 71080, name: 'SIDDHAM LETTER RA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_RA = "\u{115A8}";

    #[Info(id: 71081, name: 'SIDDHAM LETTER LA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_LA = "\u{115A9}";

    #[Info(id: 71082, name: 'SIDDHAM LETTER VA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_VA = "\u{115AA}";

    #[Info(id: 71083, name: 'SIDDHAM LETTER SHA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_SHA = "\u{115AB}";

    #[Info(id: 71084, name: 'SIDDHAM LETTER SSA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_SSA = "\u{115AC}";

    #[Info(id: 71085, name: 'SIDDHAM LETTER SA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_SA = "\u{115AD}";

    #[Info(id: 71086, name: 'SIDDHAM LETTER HA', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_HA = "\u{115AE}";

    #[Info(id: 71087, name: 'SIDDHAM VOWEL SIGN AA', category: Cat::Spacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_AA = "\u{115AF}";

    #[Info(id: 71088, name: 'SIDDHAM VOWEL SIGN I', category: Cat::Spacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_I = "\u{115B0}";

    #[Info(id: 71089, name: 'SIDDHAM VOWEL SIGN II', category: Cat::Spacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_II = "\u{115B1}";

    #[Info(id: 71090, name: 'SIDDHAM VOWEL SIGN U', category: Cat::Nonspacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_U = "\u{115B2}";

    #[Info(id: 71091, name: 'SIDDHAM VOWEL SIGN UU', category: Cat::Nonspacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_UU = "\u{115B3}";

    #[Info(id: 71092, name: 'SIDDHAM VOWEL SIGN VOCALIC R', category: Cat::Nonspacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_VOCALIC_R = "\u{115B4}";

    #[Info(id: 71093, name: 'SIDDHAM VOWEL SIGN VOCALIC RR', category: Cat::Nonspacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_VOCALIC_RR = "\u{115B5}";

    #[Info(id: 71096, name: 'SIDDHAM VOWEL SIGN E', category: Cat::Spacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_E = "\u{115B8}";

    #[Info(id: 71097, name: 'SIDDHAM VOWEL SIGN AI', category: Cat::Spacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_AI = "\u{115B9}";

    #[Info(id: 71098, name: 'SIDDHAM VOWEL SIGN O', category: Cat::Spacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_O = "\u{115BA}";

    #[Info(id: 71099, name: 'SIDDHAM VOWEL SIGN AU', category: Cat::Spacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_AU = "\u{115BB}";

    #[Info(id: 71100, name: 'SIDDHAM SIGN CANDRABINDU', category: Cat::Nonspacing_Mark)]
    case SIDDHAM_SIGN_CANDRABINDU = "\u{115BC}";

    #[Info(id: 71101, name: 'SIDDHAM SIGN ANUSVARA', category: Cat::Nonspacing_Mark)]
    case SIDDHAM_SIGN_ANUSVARA = "\u{115BD}";

    #[Info(id: 71102, name: 'SIDDHAM SIGN VISARGA', category: Cat::Spacing_Mark)]
    case SIDDHAM_SIGN_VISARGA = "\u{115BE}";

    #[Info(id: 71103, name: 'SIDDHAM SIGN VIRAMA', category: Cat::Nonspacing_Mark)]
    case SIDDHAM_SIGN_VIRAMA = "\u{115BF}";

    #[Info(id: 71104, name: 'SIDDHAM SIGN NUKTA', category: Cat::Nonspacing_Mark)]
    case SIDDHAM_SIGN_NUKTA = "\u{115C0}";

    #[Info(id: 71105, name: 'SIDDHAM SIGN SIDDHAM', category: Cat::Other_Punctuation)]
    case SIDDHAM_SIGN_SIDDHAM = "\u{115C1}";

    #[Info(id: 71106, name: 'SIDDHAM DANDA', category: Cat::Other_Punctuation)]
    case SIDDHAM_DANDA = "\u{115C2}";

    #[Info(id: 71107, name: 'SIDDHAM DOUBLE DANDA', category: Cat::Other_Punctuation)]
    case SIDDHAM_DOUBLE_DANDA = "\u{115C3}";

    #[Info(id: 71108, name: 'SIDDHAM SEPARATOR DOT', category: Cat::Other_Punctuation)]
    case SIDDHAM_SEPARATOR_DOT = "\u{115C4}";

    #[Info(id: 71109, name: 'SIDDHAM SEPARATOR BAR', category: Cat::Other_Punctuation)]
    case SIDDHAM_SEPARATOR_BAR = "\u{115C5}";

    #[Info(id: 71110, name: 'SIDDHAM REPETITION MARK-1', category: Cat::Other_Punctuation)]
    case SIDDHAM_REPETITION_MARK_1 = "\u{115C6}";

    #[Info(id: 71111, name: 'SIDDHAM REPETITION MARK-2', category: Cat::Other_Punctuation)]
    case SIDDHAM_REPETITION_MARK_2 = "\u{115C7}";

    #[Info(id: 71112, name: 'SIDDHAM REPETITION MARK-3', category: Cat::Other_Punctuation)]
    case SIDDHAM_REPETITION_MARK_3 = "\u{115C8}";

    #[Info(id: 71113, name: 'SIDDHAM END OF TEXT MARK', category: Cat::Other_Punctuation)]
    case SIDDHAM_END_OF_TEXT_MARK = "\u{115C9}";

    #[Info(id: 71114, name: 'SIDDHAM SECTION MARK WITH TRIDENT AND U-SHAPED ORNAMENTS', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_WITH_TRIDENT_AND_U_SHAPED_ORNAMENTS = "\u{115CA}";

    #[Info(id: 71115, name: 'SIDDHAM SECTION MARK WITH TRIDENT AND DOTTED CRESCENTS', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_WITH_TRIDENT_AND_DOTTED_CRESCENTS = "\u{115CB}";

    #[Info(id: 71116, name: 'SIDDHAM SECTION MARK WITH RAYS AND DOTTED CRESCENTS', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_WITH_RAYS_AND_DOTTED_CRESCENTS = "\u{115CC}";

    #[Info(id: 71117, name: 'SIDDHAM SECTION MARK WITH RAYS AND DOTTED DOUBLE CRESCENTS', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_WITH_RAYS_AND_DOTTED_DOUBLE_CRESCENTS = "\u{115CD}";

    #[Info(id: 71118, name: 'SIDDHAM SECTION MARK WITH RAYS AND DOTTED TRIPLE CRESCENTS', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_WITH_RAYS_AND_DOTTED_TRIPLE_CRESCENTS = "\u{115CE}";

    #[Info(id: 71119, name: 'SIDDHAM SECTION MARK DOUBLE RING', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_DOUBLE_RING = "\u{115CF}";

    #[Info(id: 71120, name: 'SIDDHAM SECTION MARK DOUBLE RING WITH RAYS', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_DOUBLE_RING_WITH_RAYS = "\u{115D0}";

    #[Info(id: 71121, name: 'SIDDHAM SECTION MARK WITH DOUBLE CRESCENTS', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_WITH_DOUBLE_CRESCENTS = "\u{115D1}";

    #[Info(id: 71122, name: 'SIDDHAM SECTION MARK WITH TRIPLE CRESCENTS', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_WITH_TRIPLE_CRESCENTS = "\u{115D2}";

    #[Info(id: 71123, name: 'SIDDHAM SECTION MARK WITH QUADRUPLE CRESCENTS', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_WITH_QUADRUPLE_CRESCENTS = "\u{115D3}";

    #[Info(id: 71124, name: 'SIDDHAM SECTION MARK WITH SEPTUPLE CRESCENTS', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_WITH_SEPTUPLE_CRESCENTS = "\u{115D4}";

    #[Info(id: 71125, name: 'SIDDHAM SECTION MARK WITH CIRCLES AND RAYS', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_WITH_CIRCLES_AND_RAYS = "\u{115D5}";

    #[Info(id: 71126, name: 'SIDDHAM SECTION MARK WITH CIRCLES AND TWO ENCLOSURES', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_WITH_CIRCLES_AND_TWO_ENCLOSURES = "\u{115D6}";

    #[Info(id: 71127, name: 'SIDDHAM SECTION MARK WITH CIRCLES AND FOUR ENCLOSURES', category: Cat::Other_Punctuation)]
    case SIDDHAM_SECTION_MARK_WITH_CIRCLES_AND_FOUR_ENCLOSURES = "\u{115D7}";

    #[Info(id: 71128, name: 'SIDDHAM LETTER THREE-CIRCLE ALTERNATE I', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_THREE_CIRCLE_ALTERNATE_I = "\u{115D8}";

    #[Info(id: 71129, name: 'SIDDHAM LETTER TWO-CIRCLE ALTERNATE I', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_TWO_CIRCLE_ALTERNATE_I = "\u{115D9}";

    #[Info(id: 71130, name: 'SIDDHAM LETTER TWO-CIRCLE ALTERNATE II', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_TWO_CIRCLE_ALTERNATE_II = "\u{115DA}";

    #[Info(id: 71131, name: 'SIDDHAM LETTER ALTERNATE U', category: Cat::Other_Letter)]
    case SIDDHAM_LETTER_ALTERNATE_U = "\u{115DB}";

    #[Info(id: 71132, name: 'SIDDHAM VOWEL SIGN ALTERNATE U', category: Cat::Nonspacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_ALTERNATE_U = "\u{115DC}";

    #[Info(id: 71133, name: 'SIDDHAM VOWEL SIGN ALTERNATE UU', category: Cat::Nonspacing_Mark)]
    case SIDDHAM_VOWEL_SIGN_ALTERNATE_UU = "\u{115DD}";
}
