<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '15.1.0')]
enum Syriac_Supplement: string
{
    #[Info(id: 0x860, name: 'SYRIAC LETTER MALAYALAM NGA', category: Cat::Other_Letter)]
    case SYRIAC_LETTER_MALAYALAM_NGA = "\u{860}";

    #[Info(id: 0x861, name: 'SYRIAC LETTER MALAYALAM JA', category: Cat::Other_Letter)]
    case SYRIAC_LETTER_MALAYALAM_JA = "\u{861}";

    #[Info(id: 0x862, name: 'SYRIAC LETTER MALAYALAM NYA', category: Cat::Other_Letter)]
    case SYRIAC_LETTER_MALAYALAM_NYA = "\u{862}";

    #[Info(id: 0x863, name: 'SYRIAC LETTER MALAYALAM TTA', category: Cat::Other_Letter)]
    case SYRIAC_LETTER_MALAYALAM_TTA = "\u{863}";

    #[Info(id: 0x864, name: 'SYRIAC LETTER MALAYALAM NNA', category: Cat::Other_Letter)]
    case SYRIAC_LETTER_MALAYALAM_NNA = "\u{864}";

    #[Info(id: 0x865, name: 'SYRIAC LETTER MALAYALAM NNNA', category: Cat::Other_Letter)]
    case SYRIAC_LETTER_MALAYALAM_NNNA = "\u{865}";

    #[Info(id: 0x866, name: 'SYRIAC LETTER MALAYALAM BHA', category: Cat::Other_Letter)]
    case SYRIAC_LETTER_MALAYALAM_BHA = "\u{866}";

    #[Info(id: 0x867, name: 'SYRIAC LETTER MALAYALAM RA', category: Cat::Other_Letter)]
    case SYRIAC_LETTER_MALAYALAM_RA = "\u{867}";

    #[Info(id: 0x868, name: 'SYRIAC LETTER MALAYALAM LLA', category: Cat::Other_Letter)]
    case SYRIAC_LETTER_MALAYALAM_LLA = "\u{868}";

    #[Info(id: 0x869, name: 'SYRIAC LETTER MALAYALAM LLLA', category: Cat::Other_Letter)]
    case SYRIAC_LETTER_MALAYALAM_LLLA = "\u{869}";

    #[Info(id: 0x86A, name: 'SYRIAC LETTER MALAYALAM SSA', category: Cat::Other_Letter)]
    case SYRIAC_LETTER_MALAYALAM_SSA = "\u{86A}";
}
