<?php

/*
 * Please DO NOT edit this file manually!
 * It has been generated automatically by MLUnipoints\Build\CodepointsBuilder
 */

declare(strict_types=1);

namespace MLUnipoints\Codepoint;

use MLUnipoints\Category as Cat;
use MLUnipoints\Info\CodepointInfo as Info;
use MLUnipoints\Info\UnicodeInfo;

#[UnicodeInfo(unicodeVersion: '16.0.0')]
enum Yi_Radicals: string
{
    #[Info(id: 0xA490, name: 'YI RADICAL QOT', category: Cat::Other_Symbol)]
    case YI_RADICAL_QOT = "\u{A490}";

    #[Info(id: 0xA491, name: 'YI RADICAL LI', category: Cat::Other_Symbol)]
    case YI_RADICAL_LI = "\u{A491}";

    #[Info(id: 0xA492, name: 'YI RADICAL KIT', category: Cat::Other_Symbol)]
    case YI_RADICAL_KIT = "\u{A492}";

    #[Info(id: 0xA493, name: 'YI RADICAL NYIP', category: Cat::Other_Symbol)]
    case YI_RADICAL_NYIP = "\u{A493}";

    #[Info(id: 0xA494, name: 'YI RADICAL CYP', category: Cat::Other_Symbol)]
    case YI_RADICAL_CYP = "\u{A494}";

    #[Info(id: 0xA495, name: 'YI RADICAL SSI', category: Cat::Other_Symbol)]
    case YI_RADICAL_SSI = "\u{A495}";

    #[Info(id: 0xA496, name: 'YI RADICAL GGOP', category: Cat::Other_Symbol)]
    case YI_RADICAL_GGOP = "\u{A496}";

    #[Info(id: 0xA497, name: 'YI RADICAL GEP', category: Cat::Other_Symbol)]
    case YI_RADICAL_GEP = "\u{A497}";

    #[Info(id: 0xA498, name: 'YI RADICAL MI', category: Cat::Other_Symbol)]
    case YI_RADICAL_MI = "\u{A498}";

    #[Info(id: 0xA499, name: 'YI RADICAL HXIT', category: Cat::Other_Symbol)]
    case YI_RADICAL_HXIT = "\u{A499}";

    #[Info(id: 0xA49A, name: 'YI RADICAL LYR', category: Cat::Other_Symbol)]
    case YI_RADICAL_LYR = "\u{A49A}";

    #[Info(id: 0xA49B, name: 'YI RADICAL BBUT', category: Cat::Other_Symbol)]
    case YI_RADICAL_BBUT = "\u{A49B}";

    #[Info(id: 0xA49C, name: 'YI RADICAL MOP', category: Cat::Other_Symbol)]
    case YI_RADICAL_MOP = "\u{A49C}";

    #[Info(id: 0xA49D, name: 'YI RADICAL YO', category: Cat::Other_Symbol)]
    case YI_RADICAL_YO = "\u{A49D}";

    #[Info(id: 0xA49E, name: 'YI RADICAL PUT', category: Cat::Other_Symbol)]
    case YI_RADICAL_PUT = "\u{A49E}";

    #[Info(id: 0xA49F, name: 'YI RADICAL HXUO', category: Cat::Other_Symbol)]
    case YI_RADICAL_HXUO = "\u{A49F}";

    #[Info(id: 0xA4A0, name: 'YI RADICAL TAT', category: Cat::Other_Symbol)]
    case YI_RADICAL_TAT = "\u{A4A0}";

    #[Info(id: 0xA4A1, name: 'YI RADICAL GA', category: Cat::Other_Symbol)]
    case YI_RADICAL_GA = "\u{A4A1}";

    #[Info(id: 0xA4A2, name: 'YI RADICAL ZUP', category: Cat::Other_Symbol)]
    case YI_RADICAL_ZUP = "\u{A4A2}";

    #[Info(id: 0xA4A3, name: 'YI RADICAL CYT', category: Cat::Other_Symbol)]
    case YI_RADICAL_CYT = "\u{A4A3}";

    #[Info(id: 0xA4A4, name: 'YI RADICAL DDUR', category: Cat::Other_Symbol)]
    case YI_RADICAL_DDUR = "\u{A4A4}";

    #[Info(id: 0xA4A5, name: 'YI RADICAL BUR', category: Cat::Other_Symbol)]
    case YI_RADICAL_BUR = "\u{A4A5}";

    #[Info(id: 0xA4A6, name: 'YI RADICAL GGUO', category: Cat::Other_Symbol)]
    case YI_RADICAL_GGUO = "\u{A4A6}";

    #[Info(id: 0xA4A7, name: 'YI RADICAL NYOP', category: Cat::Other_Symbol)]
    case YI_RADICAL_NYOP = "\u{A4A7}";

    #[Info(id: 0xA4A8, name: 'YI RADICAL TU', category: Cat::Other_Symbol)]
    case YI_RADICAL_TU = "\u{A4A8}";

    #[Info(id: 0xA4A9, name: 'YI RADICAL OP', category: Cat::Other_Symbol)]
    case YI_RADICAL_OP = "\u{A4A9}";

    #[Info(id: 0xA4AA, name: 'YI RADICAL JJUT', category: Cat::Other_Symbol)]
    case YI_RADICAL_JJUT = "\u{A4AA}";

    #[Info(id: 0xA4AB, name: 'YI RADICAL ZOT', category: Cat::Other_Symbol)]
    case YI_RADICAL_ZOT = "\u{A4AB}";

    #[Info(id: 0xA4AC, name: 'YI RADICAL PYT', category: Cat::Other_Symbol)]
    case YI_RADICAL_PYT = "\u{A4AC}";

    #[Info(id: 0xA4AD, name: 'YI RADICAL HMO', category: Cat::Other_Symbol)]
    case YI_RADICAL_HMO = "\u{A4AD}";

    #[Info(id: 0xA4AE, name: 'YI RADICAL YIT', category: Cat::Other_Symbol)]
    case YI_RADICAL_YIT = "\u{A4AE}";

    #[Info(id: 0xA4AF, name: 'YI RADICAL VUR', category: Cat::Other_Symbol)]
    case YI_RADICAL_VUR = "\u{A4AF}";

    #[Info(id: 0xA4B0, name: 'YI RADICAL SHY', category: Cat::Other_Symbol)]
    case YI_RADICAL_SHY = "\u{A4B0}";

    #[Info(id: 0xA4B1, name: 'YI RADICAL VEP', category: Cat::Other_Symbol)]
    case YI_RADICAL_VEP = "\u{A4B1}";

    #[Info(id: 0xA4B2, name: 'YI RADICAL ZA', category: Cat::Other_Symbol)]
    case YI_RADICAL_ZA = "\u{A4B2}";

    #[Info(id: 0xA4B3, name: 'YI RADICAL JO', category: Cat::Other_Symbol)]
    case YI_RADICAL_JO = "\u{A4B3}";

    #[Info(id: 0xA4B4, name: 'YI RADICAL NZUP', category: Cat::Other_Symbol)]
    case YI_RADICAL_NZUP = "\u{A4B4}";

    #[Info(id: 0xA4B5, name: 'YI RADICAL JJY', category: Cat::Other_Symbol)]
    case YI_RADICAL_JJY = "\u{A4B5}";

    #[Info(id: 0xA4B6, name: 'YI RADICAL GOT', category: Cat::Other_Symbol)]
    case YI_RADICAL_GOT = "\u{A4B6}";

    #[Info(id: 0xA4B7, name: 'YI RADICAL JJIE', category: Cat::Other_Symbol)]
    case YI_RADICAL_JJIE = "\u{A4B7}";

    #[Info(id: 0xA4B8, name: 'YI RADICAL WO', category: Cat::Other_Symbol)]
    case YI_RADICAL_WO = "\u{A4B8}";

    #[Info(id: 0xA4B9, name: 'YI RADICAL DU', category: Cat::Other_Symbol)]
    case YI_RADICAL_DU = "\u{A4B9}";

    #[Info(id: 0xA4BA, name: 'YI RADICAL SHUR', category: Cat::Other_Symbol)]
    case YI_RADICAL_SHUR = "\u{A4BA}";

    #[Info(id: 0xA4BB, name: 'YI RADICAL LIE', category: Cat::Other_Symbol)]
    case YI_RADICAL_LIE = "\u{A4BB}";

    #[Info(id: 0xA4BC, name: 'YI RADICAL CY', category: Cat::Other_Symbol)]
    case YI_RADICAL_CY = "\u{A4BC}";

    #[Info(id: 0xA4BD, name: 'YI RADICAL CUOP', category: Cat::Other_Symbol)]
    case YI_RADICAL_CUOP = "\u{A4BD}";

    #[Info(id: 0xA4BE, name: 'YI RADICAL CIP', category: Cat::Other_Symbol)]
    case YI_RADICAL_CIP = "\u{A4BE}";

    #[Info(id: 0xA4BF, name: 'YI RADICAL HXOP', category: Cat::Other_Symbol)]
    case YI_RADICAL_HXOP = "\u{A4BF}";

    #[Info(id: 0xA4C0, name: 'YI RADICAL SHAT', category: Cat::Other_Symbol)]
    case YI_RADICAL_SHAT = "\u{A4C0}";

    #[Info(id: 0xA4C1, name: 'YI RADICAL ZUR', category: Cat::Other_Symbol)]
    case YI_RADICAL_ZUR = "\u{A4C1}";

    #[Info(id: 0xA4C2, name: 'YI RADICAL SHOP', category: Cat::Other_Symbol)]
    case YI_RADICAL_SHOP = "\u{A4C2}";

    #[Info(id: 0xA4C3, name: 'YI RADICAL CHE', category: Cat::Other_Symbol)]
    case YI_RADICAL_CHE = "\u{A4C3}";

    #[Info(id: 0xA4C4, name: 'YI RADICAL ZZIET', category: Cat::Other_Symbol)]
    case YI_RADICAL_ZZIET = "\u{A4C4}";

    #[Info(id: 0xA4C5, name: 'YI RADICAL NBIE', category: Cat::Other_Symbol)]
    case YI_RADICAL_NBIE = "\u{A4C5}";

    #[Info(id: 0xA4C6, name: 'YI RADICAL KE', category: Cat::Other_Symbol)]
    case YI_RADICAL_KE = "\u{A4C6}";
}
