name: Tests

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main
  repository_dispatch:
    types:
      - tests

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        include:
          -
            os: ubuntu-latest
            php-version: "8.2"
            check-cs: true
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: ${{ matrix.check-cs && 'php-cs-fixer:v3,' || '' }} composer:v2
          coverage: none
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Cache PHP-CS-Fixer
        if: matrix.check-cs
        uses: actions/cache@v4
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.os }}-${{ matrix.php-version }}-phpcsfixer
      -
        name: Install Composer dependencies
        run: composer update --optimize-autoloader --no-progress --ansi --no-interaction
      -
        name: Build
        run: ./bin/unipoints build
      -
        name: Check built assets
        if: startsWith(matrix.os, 'windows') == false
        run: |
          if ! git diff --exit-code --name-status; then
            echo "::error file=$(git diff --name-status | head -n 1)::PLEASE RUN bin/unipoints build"
            exit 1
          fi
      -
        name: Check PHP coding style
        if: matrix.check-cs
        run: composer run-script phpcs -- --ansi --no-interaction --dry-run --diff --show-progress=none
      -
        name: PHPUnit
        run: composer run-script test -- --colors=always
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: docs-src/package-lock.json
      -
        name: Install NPM dependencies
        run: cd docs-src && npm ci
      -
        name: Check coding style
        run: cd docs-src && npm run-script lint
      -
        name: Build
        run: cd docs-src && npm run-script build
      -
        name: Check changes
        id: check-changes
        if: github.repository == 'mlocati/unipoints' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
            if ! git diff --exit-code --name-status; then
                echo "commit=yes" >>"$GITHUB_OUTPUT"
            fi
      -
        name: Push changes
        if: steps.check-changes.outputs.commit == 'yes'
        run: |
            git config user.name GitHub
            git config user.email noreply@github.com
            git add --all
            git commit -m 'Rebuilding docs'
            git push
