name: Tests

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main
  repository_dispatch:
    types:
      - ci

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: php-cs-fixer:v3, composer:v2
          coverage: none
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Composer dependencies
        run: composer update --prefer-lowest --optimize-autoloader --no-progress --ansi --no-interaction
      - name: Build
        run: ./bin/unipoints build
      - name: Check PHP coding style
        if: startsWith(matrix.os, 'ubuntu') && matrix.php-version == '8.2'
        run: composer run-script phpcs -- --ansi --no-interaction --dry-run --diff
      - name: PHPUnit
        run: composer run-script test -- --colors=always
      - name: Check changes
        id: check-changes
        if: startsWith(matrix.os, 'ubuntu') && matrix.php-version == '8.2' && github.repository == 'mlocati/unipoints' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          if ! git diff --exit-code --name-status; then
            echo "commit=yes" >>"$GITHUB_OUTPUT"
          fi
      - name: Push changes
        if: steps.check-changes.outputs.commit == 'yes'
        run: |
          git config user.name 'Michele Locati'
          git config user.email 'michele@locati.it'
          git add --all
          git commit -m 'Automatic update built assets'
          git push
